feat: add empty state method for test
paradigmxyz/reth pull request #10045
Opened 2024-08-02 21:13 UTC by mvares

Follow up #10040

2024-08-02 21:14 UTC, mvares commented
cc @mattsse

2024-08-02 22:21 UTC, mattsse requested changes

2024-08-02 22:21 UTC, mattsse commented on crates/chain-state/src/in_memory.rs
> +    }
I'd like to make this a function of `CanonicalInMemoryState` itself so you can do `CanonicalInMemoryState::empty()`

2024-08-05 09:31 UTC, onbjerg approved these changes

2024-08-05 09:37 UTC, mattsse approved these changes

2024-08-05 09:58 UTC, merged