feat: ForkChoiceSubscriptions for BlockchainProvider && NoopProvidor
paradigmxyz/reth pull request #10056
Opened 2024-08-03 16:33 UTC by royvardhan

Ref [9521](https://github.com/paradigmxyz/reth/issues/9521)

2024-08-03 19:39 UTC, emhane requested changes

2024-08-03 19:39 UTC, emhane commented on crates/storage/provider/src/providers/mod.rs
> +                return self.pending_with_provider(pending);
please revert these unrelated changes. use the nightly formatter for reth `cargo +nightly fmt`. you can also use shortcut `make lint`.

2024-08-05 10:01 UTC, mattsse requested changes

2024-08-05 10:01 UTC, mattsse commented on crates/blockchain-tree/src/blockchain_tree.rs
please undo the extra `;`

2024-08-05 11:18 UTC, royvardhan commented on crates/blockchain-tree/src/blockchain_tree.rs
Done

2024-08-08 11:44 UTC, mattsse requested changes
hmm, after looking at this again, I'd like to take one step back and only implement this for `BlockChainProvider` and Noop.

blockchainprovider then should use these channels to obtain the listeners, 
https://github.com/paradigmxyz/reth/blob/e907f0eab0d90f286f2197ee8935f10817ff1edf/crates/chain-state/src/chain_info.rs#L139-L144

which means we also need to change this type slightly

https://github.com/paradigmxyz/reth/blob/e907f0eab0d90f286f2197ee8935f10817ff1edf/crates/chain-state/src/notifications.rs#L146-L146

2024-08-09 06:00 UTC, closed without merging