Feat/9521
paradigmxyz/reth pull request #10231
Opened 2024-08-09 06:04 UTC by royvardhan

2024-08-09 12:12 UTC, mattsse requested changes
last naming nits

2024-08-09 12:12 UTC, mattsse commented on crates/chain-state/src/chain_info.rs
> +    pub fn subscribe_to_fork_choice(&self) -> watch::Receiver<Option<SealedHeader>> {
```suggestion
    pub fn subscribe_to_safe_block(&self) -> watch::Receiver<Option<SealedHeader>> {
```

2024-08-09 12:12 UTC, mattsse commented on crates/storage/provider/src/providers/mod.rs
> +    fn subscribe_to_fork_choice(&self) -> ForkChoiceNotifications {
we should actually rename this to safe and and finalized

2024-08-09 16:06 UTC, royvardhan commented
Looks good? @mattsse

2024-08-10 14:20 UTC, mattsse approved these changes
nice work

2024-08-10 14:48 UTC, merged