fix: prevents tx spams that breaks the instant miner
paradigmxyz/reth pull request #10365
Opened 2024-08-16 12:46 UTC by mvares

Fixes #10333

FYI @mattsse

2024-08-17 17:05 UTC, rkrasiuk requested changes

2024-08-17 17:05 UTC, rkrasiuk commented on crates/consensus/auto-seal/src/mode.rs
> +                }
you should try to fit any remaining transaction instead of breaking from the loop here

2024-08-17 17:05 UTC, rkrasiuk commented on crates/consensus/auto-seal/src/mode.rs
> +                if next_gas > ETHEREUM_BLOCK_GAS_LIMIT {
this should be checked against `chain_spec.max_gas_limit` and not default one

2024-08-17 17:09 UTC, mattsse reviewed
we made this change as a hack on the other branch but the issue with this is that this isn't optimal because it skips transactions this should ideally be solved during mining, but there are currently a lot of limitations.

need to think what the best solution here is

2024-08-17 17:15 UTC, mvares commented
> we made this change as a hack on the other branch but the issue with this is that this isn't optimal because it skips transactions this should ideally be solved during mining, but there are currently a lot of limitations.
> 
> need to think what the best solution here is

of course

2024-09-09 17:33 UTC, mattsse commented
it turns out we cant do this because this doesn't utilize block space properly

the auto miner will be solved differently soon https://github.com/paradigmxyz/reth/issues/10714

2024-09-09 17:33 UTC, closed without merging