fix: getAccount
paradigmxyz/reth pull request #10402
Opened 2024-08-20 17:41 UTC by greged93

After checking out the implementation of the endpoint by Geth and Nethermind, I believe we should be returning an `None` value if the account if not found in the state.

## Example: 

```
curl https://docs-demo.quiknode.pro/ \                                                                                                                                                                                                                                    130 ↵
  --header 'Content-Type: application/json' \
  --data '{
      "method": "eth_getAccount",
      "params":["0x8D97689C9818892B700e27F316cc3E41e17fBebf", "latest"],
      "id": 1,
      "jsonrpc": "2.0"
}'
```

Returns `null`.

2024-08-20 18:22 UTC, mattsse requested changes
nice, smol nits

2024-08-20 18:22 UTC, mattsse commented on crates/rpc/rpc-eth-api/src/helpers/state.rs
> +            if let Some(account) = account {
styl nit:

let use `let Some() else {return Ok(None)}` here to get rid of the scope

2024-08-20 18:22 UTC, mattsse commented on crates/rpc/rpc/src/eth/helpers/state.rs
> +            alloy_consensus::Account { code_hash: KECCAK_EMPTY, ..Default::default() };
I believe this is available from the reth-rpc-types crate so we don't need the alloy-consensus dep here

2024-08-20 18:22 UTC, mattsse commented on crates/rpc/rpc/src/eth/helpers/state.rs
this test case can also be added as an additional call here

https://github.com/paradigmxyz/reth/blob/72ed7a9b0812fb03b87be9e3877713dc06b7dc91/crates/rpc/rpc-builder/tests/it/http.rs#L177-L177

2024-08-20 20:23 UTC, emhane approved these changes

2024-08-20 20:23 UTC, emhane commented on crates/rpc/rpc-eth-api/src/helpers/state.rs
> +                    .map_err(Self::Error::from_eth_err)?;
fix this whitespace pls, try command `make lint`

2024-08-20 20:26 UTC, emhane commented on crates/rpc/rpc-eth-api/src/helpers/state.rs
> +                    .map_err(Self::Error::from_eth_err)?;
nvm, duplicate of https://github.com/paradigmxyz/reth/pull/10402/files#r1723751263

2024-08-21 07:40 UTC, mattsse approved these changes

2024-08-21 07:54 UTC, merged