chore(trie): remove `PrefixSetMut::contains`
paradigmxyz/reth pull request #10466
Opened 2024-08-22 19:10 UTC by rkrasiuk

## Description

Remove `PrefixSetMut::contains` given that this is a mutable collection not intended for searching.

2024-08-22 19:11 UTC, rkrasiuk commented on crates/trie/trie/src/prefix_set.rs
> -    sorted: bool,
should always be treated as unsorted

2024-08-23 01:43 UTC, mattsse requested changes
don't love the `Abstraction` suffix, be looks like we already use this this for PrefixSet

2024-08-23 01:43 UTC, mattsse commented on crates/trie/trie/benches/prefix_set.rs
> +pub trait PrefixSetMutAbstraction: Default {
needs docs

2024-08-23 03:48 UTC, rkrasiuk commented
@mattsse doesn't matter really since this is only for benching

2024-08-23 05:48 UTC, mattsse approved these changes
gotcha

2024-08-23 06:01 UTC, merged