Improved the rpc error for nonce two low #10464
paradigmxyz/reth pull request #10511
Opened 2024-08-25 13:50 UTC by i-sangh

ref #10464

The current error wasn't very helpful: nonce too low

So ideally it should now be:

nonce too low: next nonce 72, tx nonce 71

2024-08-25 14:47 UTC, emhane requested changes

2024-08-25 14:47 UTC, emhane commented on crates/rpc/rpc-eth-types/src/error.rs
>      #[error("nonce too low")]
```suggestion
    #[error("nonce too low: got {tx}, expected {state}")]
```

2024-08-25 14:51 UTC, emhane commented
make sure to run lint with `nightly` tool chain, otherwise a bunch of semicolons are added that we don't want, try command `make lint`

2024-08-25 16:20 UTC, emhane approved these changes

2024-08-26 09:54 UTC, mattsse requested changes
one more suggestion

2024-08-26 09:54 UTC, mattsse commented on crates/rpc/rpc-eth-types/src/error.rs
> +            InvalidTransactionError::NonceNotConsistent => Self::NonceTooLow { tx: 0, state: 0},
I think we can also add these fields to the `NonceNotConsistent` error variant

https://github.com/paradigmxyz/reth/blob/29058ad7ee64d993de6c301a9d688002cb698f03/crates/transaction-pool/src/validate/eth.rs#L338-L344

2024-08-26 09:54 UTC, mattsse commented on crates/rpc/rpc-eth-types/src/error.rs
> +            ),
this doesn't look right, why this change?

2024-08-28 05:21 UTC, i-sangh commented
error.rs & eth.rs

2024-08-28 05:21 UTC, closed without merging

2024-08-28 08:00 UTC, mattsse commented
why was this closed @i-sangh ? this was on track and almost ready

2024-09-04 22:08 UTC, emnul commented
Happy to fork and continue work on on this one @mattsse