Feat: Extend BuiltPayload type
paradigmxyz/reth pull request #10583
Opened 2024-08-27 23:15 UTC by malik672

closes #10436

2024-08-28 08:25 UTC, emhane commented
what unblocks this issue @mattsse ?

2024-08-28 19:02 UTC, onbjerg requested changes

2024-08-28 19:02 UTC, onbjerg commented on crates/optimism/payload/src/payload.rs
> +        (self).receipts.clone()
```suggestion
        self.receipts.clone()
```

2024-08-28 19:02 UTC, onbjerg commented on crates/optimism/payload/src/payload.rs
> +    fn receipts(&self) -> Vec<Receipt> {
same here, should return `&[Receipt]` (and below)

2024-08-28 19:02 UTC, onbjerg commented on crates/optimism/payload/src/builder.rs
> +        // Create an EVM instance
this is an empty block, so we don't need to execute anything here. we simply return no receipts

2024-08-28 19:02 UTC, onbjerg commented on crates/ethereum/payload/src/lib.rs
> +        let mut evm = self.evm_config.evm(db);
this is an empty block, so we simply need to return no receipts here, no need to execute anything

2024-08-29 10:51 UTC, onbjerg requested changes
getting there!

2024-08-29 10:51 UTC, onbjerg commented on crates/ethereum/payload/src/lib.rs
> +        reth_basic_payload_builder::MissingPayloadBehaviour::RaceEmptyPayload
please remove this unrelated change:)

2024-08-29 10:51 UTC, onbjerg commented on crates/ethereum/payload/src/lib.rs
> +        Ok(EthBuiltPayload::new(attributes.payload_id(), sealed_block, U256::ZERO, [].to_vec()))
```suggestion
        Ok(EthBuiltPayload::new(attributes.payload_id(), sealed_block, U256::ZERO, Vec::new())))
```
nit

2024-08-29 10:51 UTC, onbjerg commented on crates/ethereum/payload/src/lib.rs
> +    let receipts_pay: Vec<Receipt> = receipts.iter().flatten().cloned().collect();
since we don't use `receipts` again after this, we can do `into_iter` and avoid the clone

2024-08-29 10:51 UTC, onbjerg commented on crates/optimism/payload/src/builder.rs
> +    let receipts_pay: Vec<Receipt> = receipts.iter().flatten().cloned().collect();
same as above

2024-08-29 10:51 UTC, onbjerg commented on crates/payload/builder/src/test_utils.rs
> +            [].to_vec(),
nit

```suggestion
            Vec::new(),
```

2024-08-29 11:35 UTC, onbjerg approved these changes
lgtm

2024-08-31 17:40 UTC, merged