Add support for eth/69 (EIP-7642)
paradigmxyz/reth pull request #10684
Opened 2024-09-04 01:52 UTC by malik672

this still like the half incomplete part of the code
@mattsse I have ideas on how they should be implemented but I don't think they might necessarily be what is wanted

2024-09-04 14:29 UTC, mattsse requested changes
this is hard to review because it contains unrelated changes (your previous pr)

this pr should only focus on new types and not change any implementation logic because 69 is not used yet

2024-09-04 16:31 UTC, malik672 commented on crates/net/eth-wire-types/src/version.rs
> +    pub const LATEST: Self = Self::Eth69;
@mattsse yes, I know. I'm writing this one for eventually when eth69 gets introduced, will complete the new types in a separate branch and pull a pr now, can I make this a draft till then?

2024-09-20 00:28 UTC, onbjerg commented
Hey @malik672, what's the current status on this? :blush:

2024-09-20 02:18 UTC, emhane commented
could https://github.com/paradigmxyz/reth/issues/10659 pls be addressed in many small prs? think it shouldn't be a problem to get the code compiling without doing all at once

2024-10-24 09:58 UTC, mattsse reviewed
the 69 is still in the works and is breaking, so we can't really apply it like this.

because this drifted quite a bit, I'm closing this because I think it's easier to first introduce the new 69 types before integrating it

2024-10-24 09:58 UTC, closed without merging