Split insert block function
paradigmxyz/reth pull request #10762
Opened 2024-09-07 00:52 UTC by elijahhampton

Creates two functions "insert_block_additional_data" and "insert_block_header_and_transaction_data" to split insert_block.

2024-09-11 12:31 UTC, mattsse reviewed
imo this makes sense, wdyt @Rjected 

could you please undo the additional ;?

2024-09-13 18:42 UTC, Rjected requested changes
awesome! I just have a few questions

2024-09-13 18:42 UTC, Rjected commented on crates/storage/provider/src/providers/database/provider.rs
> +        durations_recorder: &mut metrics::DurationsRecorder,
let's use the full import at the top:
```rust
import metrics::DurationsRecorder
```

2024-09-13 18:42 UTC, Rjected commented on crates/storage/provider/src/providers/database/provider.rs
> +        self.insert_block_additional_data(block, &mut durations_recorder)?;
do we need to clone here? or can we make `insert_block_header_and_transaction_data` accept `&SealedBlockWithSenders`

2024-09-13 18:44 UTC, Rjected commented on crates/storage/provider/src/traits/block.rs
> +        durations_recorder: &mut metrics::DurationsRecorder,
I also don't think this needs to accept a `&mut metrics::DurationsRecorder`, we can just initialize it as `DurationsRecorder::default()` in each method's implementation, similar to how we do it now in `insert_block`

2024-09-13 18:47 UTC, Rjected commented on crates/storage/provider/src/traits/block.rs
> +        durations_recorder: &mut metrics::DurationsRecorder,
actually nevermind, this interface is correct

2024-10-14 22:52 UTC, elijahhampton commented
@mattsse Are there other changes you would like to see for this PR?

2024-10-21 17:26 UTC, Rjected approved these changes
@elijahhampton sorry for not getting back to the review in a timely manner, this looks good to me! Should just need a rebase to solve merge conflicts

2024-10-26 00:57 UTC, elijahhampton commented
> @elijahhampton sorry for not getting back to the review in a timely manner, this looks good to me! Should just need a rebase to solve merge conflicts

Sweet. Good to go.

2024-11-12 04:11 UTC, Rjected commented
just trying to make sure we can merge this - I accidentally re-introduced the methods that were removed from https://github.com/paradigmxyz/reth/pull/12367, so we just need to use the traits for those again

2024-11-26 02:09 UTC, Rjected commented
sorry for not getting to this in time, this was my fault :( 

closing this because I think https://github.com/paradigmxyz/reth/issues/9959 is actually solved by https://github.com/paradigmxyz/reth/pull/12694 and its integration

2024-11-26 02:09 UTC, closed without merging