Handle non-default cargo target dir
paradigmxyz/reth pull request #10775
Opened 2024-09-08 12:05 UTC by estensen

Currently working from a Mac Mini with not so much internal storage, so using an external m.2 NVMe to store generated artifacts.

On main:
```
❯ make update-book-cli
cargo build --bin reth --features "jemalloc asm-keccak"
   Compiling reth-node-core v1.0.6 (/Users/estensen/Developer/reth/crates/node/core)
   Compiling reth-exex v1.0.6 (/Users/estensen/Developer/reth/crates/exex/exex)
   Compiling reth-rpc-builder v1.0.6 (/Users/estensen/Developer/reth/crates/rpc/rpc-builder)
   Compiling reth-stages v1.0.6 (/Users/estensen/Developer/reth/crates/stages/stages)
   Compiling reth-consensus-debug-client v1.0.6 (/Users/estensen/Developer/reth/crates/consensus/debug-client)
   Compiling reth-node-events v1.0.6 (/Users/estensen/Developer/reth/crates/node/events)
   Compiling reth-node-builder v1.0.6 (/Users/estensen/Developer/reth/crates/node/builder)
   Compiling reth-cli-commands v1.0.6 (/Users/estensen/Developer/reth/crates/cli/commands)
   Compiling reth-node-ethereum v1.0.6 (/Users/estensen/Developer/reth/crates/ethereum/node)
   Compiling reth v1.0.6 (/Users/estensen/Developer/reth/bin/reth)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 58.58s
Updating book cli doc...
Running: $ ./book/cli/help.rs --root-dir ./book/ --root-indentation 2 --root-summary --out-dir ./book/cli/ target/debug/reth
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
     Running `/Volumes/WD_BLACK_SN750_2TB/target/debug/help --root-dir ./book/ --root-indentation 2 --root-summary --out-dir ./book/cli/ target/debug/reth`
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
make: *** [update-book-cli] Error 1
```

this pr:
```
❯ make update-book-cli
cargo build --bin reth --features "jemalloc asm-keccak"
   Compiling reth-node-core v1.0.6 (/Users/estensen/Developer/reth/crates/node/core)
   Compiling reth-exex v1.0.6 (/Users/estensen/Developer/reth/crates/exex/exex)
   Compiling reth-rpc-builder v1.0.6 (/Users/estensen/Developer/reth/crates/rpc/rpc-builder)
   Compiling reth-stages v1.0.6 (/Users/estensen/Developer/reth/crates/stages/stages)
   Compiling reth-consensus-debug-client v1.0.6 (/Users/estensen/Developer/reth/crates/consensus/debug-client)
   Compiling reth-node-events v1.0.6 (/Users/estensen/Developer/reth/crates/node/events)
   Compiling reth-node-builder v1.0.6 (/Users/estensen/Developer/reth/crates/node/builder)
   Compiling reth-cli-commands v1.0.6 (/Users/estensen/Developer/reth/crates/cli/commands)
   Compiling reth-node-ethereum v1.0.6 (/Users/estensen/Developer/reth/crates/ethereum/node)
   Compiling reth v1.0.6 (/Users/estensen/Developer/reth/bin/reth)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 18.56s
Updating book cli doc...
Running: $ ./book/cli/help.rs --root-dir ./book/ --root-indentation 2 --root-summary --out-dir ./book/cli/ /Volumes/WD_BLACK_SN750_2TB/target/debug/reth
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.15s
     Running `/Volumes/WD_BLACK_SN750_2TB/target/debug/help --root-dir ./book/ --root-indentation 2 --root-summary --out-dir ./book/cli/ /Volumes/WD_BLACK_SN750_2TB/target/debug/reth`
```

2024-09-09 12:53 UTC, onbjerg requested changes
does this work w/o `CARGO_TARGET_DIR` set?

2024-09-11 10:11 UTC, estensen commented
> does this work w/o `CARGO_TARGET_DIR` set?

Now it should for for both cases

2024-09-11 10:13 UTC, shekhirin commented on Makefile
> +BUILD_PATH := $(if $(CARGO_TARGET_DIR),$(CARGO_TARGET_DIR),target)
a simple 
```suggestion
CARGO_TARGET_DIR ?= target
```
should do, and then replace the `BUILD_PATH` with `CARGO_TARGET_DIR` everywhere below

2024-09-18 22:35 UTC, onbjerg approved these changes
tysm for this!

2024-09-18 22:47 UTC, merged