fix(storage): add `FileDataReader` & `MmapDataReader` to `NippyJar`
paradigmxyz/reth pull request #10792
Opened 2024-09-09 18:17 UTC by joshieDo

* Adds `FileDataReader` which as the name suggests, does not use mmap
* Adds `DefaultDataReader`: windows will be `FileDataReader`, others `MmapDataReader` 

Windows mmap behaviour differs from unix, and there have been issues in the past. Some I was able to repro (eg. trying to remove a file with a mmap handle open gives out an error), others not so much (eg. writing to a file while a mmap is open https://github.com/paradigmxyz/reth/issues/10689). I've also had unexpected behaviour where written data was not flushed/sync_all just because the mmap handle was open, but it wouldnt even panic.

So for now I think the safest is to disable mmap usage from windows.

2024-09-10 10:48 UTC, shekhirin approved these changes

2024-09-10 10:48 UTC, shekhirin commented on crates/storage/nippy-jar/src/cursor.rs
> +                _file_buffer.as_deref().expect("qed")
can't we just cast `buffer` into the required type? this look weird

2024-09-11 10:28 UTC, mattsse requested changes
I get why we need this, but if we're using the data functions based on another trait function then this should be properly documented

2024-09-11 10:28 UTC, mattsse commented on crates/storage/nippy-jar/src/reader.rs
> +pub type DefaultDataReader = MmapDataReader;
why is this different, needs docs

2024-09-11 10:28 UTC, mattsse commented on crates/storage/nippy-jar/src/reader.rs
> +        unimplemented!()
I think this is a decent sized footgun

2024-09-11 10:28 UTC, mattsse commented on crates/storage/nippy-jar/src/reader.rs
> +    fn data_ref(&self, range: Range<usize>) -> &[u8];
this needs better docs, not obvious that this is allowed to panic

2024-09-11 10:28 UTC, mattsse commented on crates/storage/nippy-jar/src/cursor.rs
> +            } else {
let's please add more docs here, because this is danger zone

2024-09-11 10:28 UTC, mattsse commented on crates/storage/nippy-jar/src/cursor.rs
> +            let mut _file_buffer = None;
this looks very weird

isn't this just cow with extra steps?

2024-09-11 12:05 UTC, mattsse requested changes
last pedantic nits

2024-09-11 12:05 UTC, mattsse commented on crates/storage/nippy-jar/src/reader.rs
> +    /// If the reader does not support returning the data range as a slice of bytes.
this must reference the function above and the caller must ensure that this type supports data_ref before calling this

2024-09-11 12:05 UTC, mattsse commented on crates/storage/nippy-jar/src/reader.rs
> +        unimplemented!()
can we use a panic message instead here

2024-09-12 02:35 UTC, mattsse approved these changes

2024-10-24 00:13 UTC, onbjerg commented
cc @joshieDo, status on this?

2025-02-17 02:03 UTC, closed without merging