feat: allow syncing `op-mainnet` with only state and without importing blocks/receipts
paradigmxyz/reth pull request #10850
Opened 2024-09-11 20:28 UTC by joshieDo

Running optimism mainnet is an hard endeavour since on top of state (14G uncompressed / 4GB compressed), one needs to export (from op-geth) and import blocks (103G / 43G) and receipts (173G / 71G). The process of acquiring this historical data is also quite troublesome.

On top of that, these blocks cannot even be executed, so they are there only for historical/RPC purposes.

Proposing adding `op-reth init-state --chain optimism --without-ovm world_trie.jsonl`  which just imports state and readies the chain for syncing.

It will generate a dummy chain (with no transactions) up the last OVM block header. It then, appends the real Bedrock block. Takes around 90seconds and 14G which come from inserting >100_000_000 empty headers.

2024-09-12 22:19 UTC, emhane commented
will be great for testing

2024-09-16 10:14 UTC, shekhirin commented on crates/optimism/cli/src/commands/init_state/bedrock.rs
> +/// first valid Bedrock block.
```suggestion
/// Creates a dummy chain (with no transactions) up to the last OVM block and appends the
/// first valid Bedrock block.
```

2024-09-16 10:14 UTC, shekhirin commented on crates/optimism/cli/src/commands/init_state/mod.rs
> +    /// }
```suggestion
    /// Must contain accounts in following format, additional account fields are ignored
    /// ```
    /// {
    ///     "balance": "\<balance\>",
    ///     "nonce": \<nonce\>,
    ///     "code": "\<bytecode\>",
    ///     "storage": {
    ///         "\<key\>": "\<value\>",
    ///         ..
    ///     },
    ///     "address": "\<address\>",
    /// }
    /// ```
    /// Must also contain `{ "root": \<state-root\> }` as first line.
```

2024-09-16 10:14 UTC, shekhirin commented on crates/optimism/primitives/src/bedrock.rs
> +];
can we have it as just once `BLOCK_NUMS_REPLAYED_TX` array with hardcoded block numbers and comments on each line?

2024-09-16 10:14 UTC, shekhirin commented on crates/optimism/primitives/src/bedrock.rs
> +pub fn is_dup_tx(block_number: u64) -> bool {
do we need this? don't see it used anywhere

2024-09-16 10:24 UTC, shekhirin commented on crates/optimism/primitives/src/bedrock.rs
> +];
oh right i see

2024-09-16 10:24 UTC, shekhirin approved these changes

2024-09-16 12:59 UTC, emhane reviewed
We need to edit rpc for this too, any queries made for blocks in the ovm range, need to return an error. Alternatively, we need to add docs explaining that rpc responses may return undefined behaviour. Needs to include an exhaustive list of the rpc endpoints that are effected, and how, so that no one bases their scraping on this. Maybe logging a warning "don't use rpc for scraping" if op mainnet is started with dummy blocks, is sufficient.

2024-09-18 12:22 UTC, gakonst reviewed
Super supportive and something we should have done from the beginning

2024-09-18 16:19 UTC, mattsse requested changes
a few more suggestions and nits

2024-09-18 16:19 UTC, mattsse commented on book/run/sync-op-mainnet.md
> +**Bedrock state is required.** It can be exported from [op-geth](https://github.com/testinprod-io/op-erigon/blob/pcw109550/bedrock-db-migration/bedrock-migration.md#export-state) (**.jsonl**) or down
can we rephrase this that it becomes obvious that this is just the state snapshot at the bedrock block

2024-09-18 16:19 UTC, mattsse commented on crates/optimism/cli/src/commands/init_state/bedrock.rs
> +        );
this should include a message because will panic

2024-09-18 16:19 UTC, mattsse commented on crates/optimism/cli/src/commands/init_state/bedrock.rs
> +fn append_dummy_chain(sf_provider: &StaticFileProvider) -> Result<(), eyre::Error> {
can we make this accept the target as argument, could be useful in the future

2024-09-18 16:19 UTC, mattsse commented on crates/optimism/cli/src/commands/init_state/bedrock.rs
> +    rayon::scope(|s| {
this should be fine because this is the only thing we're running, even if this does a lot of IO.

still would prefer regular thread for this.

2024-09-18 16:53 UTC, mattsse approved these changes

2024-09-18 17:22 UTC, merged