fix(storage): dont skip consistency checks for `op-mainnet` if using minimal bootstrap
paradigmxyz/reth pull request #11099
Opened 2024-09-21 21:11 UTC by joshieDo

reverting https://github.com/paradigmxyz/reth/pull/9737

Storage consistency ensures that:
* The number of receipts/headers/transactions that the DB expects to exist are the same number as existing on static files.
* Transaction and block ranges in static files match the number of rows.

Currently, OVM import of receipts seems to be broken  (https://github.com/paradigmxyz/reth/issues/10580, https://github.com/paradigmxyz/reth/issues/9739) (https://github.com/paradigmxyz/reth/issues/9725).

Any node that synced to the tip after https://github.com/paradigmxyz/reth/pull/9737 may be inconsistent (from a historical storage pov), and disabling this skip entirely would break them. Static files are not a database, so a migration may be possible, but more complex.

For now, leaving this check disabled for nodes which imported the ovm historical data (use [minimal bootstrap](https://reth.rs/run/sync-op-mainnet.html#minimal-bootstrap) instead). **But it's important to understand that a sudden crash of the node MAY break it.**

2024-09-22 12:31 UTC, emhane requested changes
this will fail for ovm chain

2024-09-22 12:41 UTC, emhane commented
blocked by https://github.com/paradigmxyz/reth/issues/9739

2024-09-22 13:29 UTC, emhane requested changes

2024-09-22 13:29 UTC, emhane commented on crates/storage/provider/src/providers/static_file/manager.rs
> +                    "bee7192e575af30420cae0c7776304ac196077ee72b048970549e4f08e875453"
please define as constant in `reth_optimism_primitives::bedrock`

2024-09-22 14:25 UTC, emhane approved these changes

2024-09-22 15:26 UTC, emhane commented on crates/storage/provider/src/providers/static_file/manager.rs
> +            reth_chainspec::Chain::optimism_mainnet() &&
why make this more complicated syntax?

2024-09-24 15:08 UTC, mattsse approved these changes

2024-09-24 15:08 UTC, mattsse commented on crates/storage/provider/src/providers/static_file/manager.rs
> +        #[cfg(feature = "optimism")]
we can keep this cfg, but not strictly required because not expensive to check and only reachable by op mainnet

2024-09-24 15:25 UTC, merged