chore: Remove ChainSpec from PayloadConfig
paradigmxyz/reth pull request #11103
Opened 2024-09-22 04:03 UTC by garwahl

Closes https://github.com/paradigmxyz/reth/issues/10951

2024-09-22 04:07 UTC, garwahl reviewed
Raised this draft to get some guidance as removing `chainspec` seems to break a few things, keen to understand either where we can pull it from or replace usages with something equiv. cc @mattsse

2024-09-22 04:07 UTC, garwahl commented on crates/ethereum/payload/src/lib.rs
> +    // TODO (garwah): Figure out how to replace this check now that chain spec has been removed.
@mattsse It looks like `chainspec` is used heavily to determine what hardforks are active here, or threaded down eg. https://github.com/paradigmxyz/reth/blob/afac7e04af1534604bac6c76af71f2e886c605ae/crates/evm/src/system_calls/eip4788.rs#L74-L76

Do we have an alternative here for these checks or could we pull a chainspec from somewhere else?

2024-09-22 04:07 UTC, garwahl commented on examples/custom-engine-types/src/main.rs
>          <reth_ethereum_payload_builder::EthereumPayloadBuilder as PayloadBuilder<Pool, Client>>::build_empty_payload(&reth_ethereum_payload_builder::EthereumPayloadBuilder::new(EthEvmConfig::new(chai
Similar issue here, it looks like pulling out `chainspec` will break instantiating a EthEvmConfig, any guidance here?

2024-09-22 06:29 UTC, garwahl commented on crates/ethereum/payload/src/lib.rs
> +    // TODO (garwah): Figure out how to replace this check now that chain spec has been removed.
Alternatively, we move the `EthereumHardForks` helper methods off ChainSpec onto something else

2024-09-23 11:33 UTC, mattsse requested changes
I see, you can work around this by requiring that the client is also `ChainSpecProvider`

https://github.com/paradigmxyz/reth/blob/242a3ab06befbd06a51cad1602ca80df6930a4cb/crates/ethereum/payload/src/lib.rs#L90-L90

which should work because this is a chainspec provider

2024-09-25 06:25 UTC, mattsse approved these changes

2024-09-25 06:59 UTC, merged