Copy tests in reth_execution_types::chain to reth-evm-optimism
paradigmxyz/reth pull request #11115
Opened 2024-09-23 02:13 UTC by 0xriazaka

2024-09-23 03:43 UTC, onbjerg requested changes, later dismissed

2024-09-23 03:43 UTC, onbjerg commented on crates/optimism/evm/src/lib.rs
> +        let receipt1 = Receipt {
this is missing the deposit nonce and deposit receipt version fields which are unique to optimism

2024-09-23 09:03 UTC, mattsse requested changes
ty, this is helpful, the only thing we need to do is as pointed out, also port the additional optimism receipt fields

2024-09-24 09:28 UTC, mattsse approved these changes

2024-09-24 09:40 UTC, mattsse requested changes
this does not compile yet, needs same changes, like private API on `Chain`

2024-09-25 23:04 UTC, 0xriazaka commented
> this does not compile yet, needs same changes, like private API on `Chain`

wdm with "same changes"

2024-09-26 15:43 UTC, emhane approved these changes

2024-10-08 11:25 UTC, emhane commented
how's it going with this, need any help?

2024-10-15 18:48 UTC, mattsse approved these changes

2024-10-15 21:01 UTC, merged