chore(op): unify crate name reth-optimism-*
paradigmxyz/reth pull request #11223
Opened 2024-09-25 17:35 UTC by nkysg

most optimism crate name are reth-optimism-* except reth-evm-optimism and reth-node-optimism. This just unify using reth-optimism-*

2024-09-26 15:34 UTC, emhane commented
I prefer `op-reth` tbh @mattsse , we talked ab it some time back, wdyt?

2024-09-26 15:43 UTC, mattsse requested changes
I like this, this makes it consistent with the other components.

we can do the same for ethereum.

2024-09-26 15:43 UTC, mattsse commented on .github/assets/check_wasm.sh
> +  reth-optimism-evm
these need to be moved to correct alph. position

2024-09-28 10:49 UTC, mattsse approved these changes

2024-09-28 11:10 UTC, merged