feat: add `get_in_memory_or_storage_by_block` to `BlockchainProvider2`
paradigmxyz/reth pull request #11384
Opened 2024-10-01 15:05 UTC by joshieDo

* Refactor logic into a single method, similar to others get_in_memory_or_storage methods
* fixes race condition on `BlockchainProvider2::history_by_block_hash`

2024-10-01 18:34 UTC, Rjected requested changes
this is nice, I have one comment nit and one question about if we should add to the API.

2024-10-01 18:34 UTC, Rjected commented on crates/storage/provider/src/providers/blockchain_provider.rs
> +        &self,
Would like if the comment referred to "persistent storage", I first interpreted this as EVM storage for some reason, even though it doesn't make sense to interpret it that way

2024-10-01 18:34 UTC, Rjected commented on crates/storage/provider/src/providers/blockchain_provider.rs
> +    }
This makes me wonder if we should just have a method that does the:
```
        if let Some(block_state) = block_state {
            return fetch_from_block_state(block_state)
        }
        fetch_from_db(self.database_provider_ro()?)
```
part, and provide `by_block_hash` or `by_block_num` methods so we don't have to go from number -> id -> match to number. same for hash -> id -> hash

2024-10-01 21:02 UTC, mattsse approved these changes
lgtm

2024-10-01 21:18 UTC, Rjected commented on crates/storage/provider/src/providers/blockchain_provider.rs
> +    }
makes sense

2024-10-01 21:18 UTC, Rjected approved these changes

2024-10-02 08:55 UTC, fgimenez approved these changes

2024-10-02 09:29 UTC, merged