wip: Optimize Sender Recovery Process
paradigmxyz/reth pull request #11385
Opened 2024-10-01 15:09 UTC by TheDhejavu

An attempt to solve resolve this: https://github.com/paradigmxyz/reth/issues/10835

## Idea?
Spawn two std::threads: a Producer and a Consumer. The Producer prepares and sends batch chunks, while the Consumer processes chunks using the global raynon workers. Preallocate channels for each batch chunk range. Lastly,
the main thread collects and processes results, handling both successful completions and potential errors.

2024-10-02 10:04 UTC, TheDhejavu commented
Failing tests. working on fixing that.

2024-10-02 16:26 UTC, TheDhejavu commented
cc @joshieDo @mattsse

2024-10-04 09:19 UTC, mattsse requested changes
cool, this is exactly what we had in mind, ty

some doc nits, and @joshieDo sanity check

2024-10-04 09:19 UTC, mattsse commented on crates/stages/stages/src/stages/sender_recovery.rs
> +fn setup_range_recovery<Provider>(
can we add some docs here, ideally this fn name should mention spawn

2024-10-05 13:05 UTC, mattsse approved these changes
nice, tysm!

pending @joshieDo

2024-10-10 15:50 UTC, joshieDo approved these changes

2024-10-18 14:41 UTC, TheDhejavu commented
is there anything left to do here cc @mattsse @joshieDo

2024-10-18 15:17 UTC, mattsse commented
sorry forgot about to pull the trigger on this one

2024-10-18 15:32 UTC, merged