feat(cli): add `db get` subcommand
paradigmxyz/reth pull request #1139
Opened 2023-02-02 14:14 UTC by gnapoli23

Add `db get` subcommand to get info of a specific table.

This is a draft, so i would like to have some other guidance on how to use `seek_exact`, considered that it should be also used as method for `db list`, as specified in #612 

Fixes #1023

2023-02-03 00:52 UTC, gakonst commented on bin/reth/src/db/mod.rs
> +    fn get<T:Table>(&mut self, idx: usize) {
```suggestion
    fn get<T:Table>(&mut self, idx: T::Key) -> T::VAlue {
```

This should be the table's key and you should just do `self.db.view(|tx| tx.get(key))` as far as i can tell

2023-02-09 21:27 UTC, gakonst requested changes
lmk if you're gonna take this on in the next days, else would like to complete/close

2023-02-09 21:27 UTC, gakonst commented on bin/reth/src/db/mod.rs
> +                    }
all of this should just be doing `get` and use a macro like the `View` command

2023-02-11 12:30 UTC, gnapoli23 commented
> lmk if you're gonna take this on in the next days, else would like to complete/close

Sorry I can't, currently OOO, have no access to my workstation.

2023-02-12 02:00 UTC, gakonst commented
sounds good - closing for now to clean things up and we'll take over or we can revisit hwen ur back

2023-02-12 02:00 UTC, closed without merging