feat(consensus): clique
paradigmxyz/reth pull request #1151
Opened 2023-02-03 10:09 UTC by rkrasiuk

Implementation of Clique proof-of-authority consensus protocol.

2023-02-05 07:01 UTC, gakonst commented
Where do we need this & how?

2023-02-10 14:05 UTC, mattsse requested changes
this is a ton of stuff.

there are some changes that touch existing code base, which is fine imo.

not particularly familiar with clique.
test look good, is this also covered in hive?

2023-02-10 14:05 UTC, mattsse commented on crates/consensus/src/clique/utils.rs
> +
```suggestion
```

2023-02-10 14:05 UTC, mattsse commented on crates/net/ecies/src/algorithm.rs
> +        println!("RECOVERY >> {:?}", RecoveryId::from_i32(sigdata[64] as i32)?);
rm?

2023-02-10 14:11 UTC, rkrasiuk commented
hive doesn't test clique explicitly, but it's required to be able participate in rpc test suite

2023-02-11 05:52 UTC, gakonst commented
The main way I'd be convinced into merging this as a large chunk would be if we actually had a Hive test which did not pass w/o this PR and passed with this PR. So let's try to get there?

2023-02-11 10:01 UTC, rkrasiuk commented
@gakonst we did agree on it, just didn't finalize the scope

2023-03-03 06:48 UTC, rkrasiuk commented
closing as stale and not planned for now

2023-03-17 13:55 UTC, mattsse commented
as assumed we need this

2023-03-17 13:55 UTC, closed without merging