chore(net): support multiple eth protocol versions.
paradigmxyz/reth pull request #1152
Opened 2023-02-03 10:11 UTC by jinsankim

Closes #1101 

### Motivation
> we're announcing support for eth66/67 by default in Hello but only check for a single version in the eth Status handshake

### Direction
> we add a list of versions as a separate parameter to the handshake function

### Alternative idea to direction
* overwrite SharedCapability::Eth.version, from UnauthedP2PStream.handshake(), to status.version

### Note
* `geth` negotiates `eth` protocol and it selects `highest` version.
https://github.com/ethereum/go-ethereum/blob/d0a4989a8def7e6bad182d1513e8d4a093c1672d/cmd/devp2p/internal/ethtest/helpers.go#L130-L132
* We also already have the same logic at
https://github.com/paradigmxyz/reth/blob/a55e7fd9b5b40acce3030a9366285947455138be/crates/net/eth-wire/src/p2pstream.rs#L562-L567
* With this simple change, I'm success to handshake w/ Eth66.
* I expect it might mitigate the `MismatchedProtocolVersion` issue before #791 is completed.

2023-02-03 10:26 UTC, mattsse approved these changes
ty

pending @Rjected

2023-02-03 10:26 UTC, mattsse commented on crates/net/network/src/session/mod.rs
> +    let status = Status { version: p2p_stream.shared_capability().version(), ..status };
this looks correct.

2023-02-03 19:51 UTC, gakonst requested changes
please add a test for this, agree with the fix, testing the PR now

2023-02-04 12:21 UTC, jinsankim commented
> please add a test for this, agree with the fix, testing the PR now

follow it up w/ b4d688081dee7352f3154147275302b506fab20f

2023-02-04 20:30 UTC, gakonst approved these changes

2023-02-04 20:30 UTC, merged