perf(rpc): add optional block argument to `trace_block_until_with_inspector`
paradigmxyz/reth pull request #11631
Opened 2024-10-10 10:11 UTC by joshieDo

perf: by having `trace_block_until_with_inspector` accept a `SealedBlockWithSenders` we only have to fetch each block once on `trace_filter`

bug fix: passed `block_id` on `trace_filter` should be `hash` and not `number` or a reorg race scenario near the tip might give weird results

2024-10-10 15:22 UTC, emhane approved these changes

2024-10-14 14:22 UTC, mattsse requested changes
this makes sense, but we need to update the trait docs for this

2024-10-14 14:22 UTC, mattsse commented on crates/rpc/rpc-eth-api/src/helpers/trace.rs
> +        block: Option<Arc<SealedBlockWithSenders>>,
isn't this now just either?

2024-10-15 08:24 UTC, mattsse approved these changes

2024-10-15 13:19 UTC, merged