chore(clippy): enable if_then_some_else_none lint
paradigmxyz/reth pull request #11679
Opened 2024-10-12 08:01 UTC by jsvisa

use `bool::then{_some}` to replace the `if true {Some(xxx)} else {None}` code more concise. ref https://rust-lang.github.io/rust-clippy/master/#/if_then_some_else_none

2024-10-12 12:45 UTC, onbjerg approved these changes

2024-10-12 13:16 UTC, mattsse requested changes

2024-10-12 13:20 UTC, jsvisa commented on crates/ethereum-forks/src/forkid.rs
Yeah, it's not completely related, so let me make a separate PR.

2024-10-12 13:21 UTC, jsvisa commented on crates/storage/db/src/implementation/mdbx/mod.rs
> +        #[allow(clippy::if_then_some_else_none)] // can't use ? in closure
haven't use this method before, I'll have a try.

2024-10-13 01:06 UTC, Rjected approved these changes
lgtm pending @mattsse

2024-10-14 13:43 UTC, mattsse approved these changes

2024-10-14 16:00 UTC, merged