primitives: rm redundant functions for `Transaction`
paradigmxyz/reth pull request #11747
Opened 2024-10-15 13:56 UTC by tcoratger

Related https://github.com/paradigmxyz/reth/pull/11727#discussion_r1800017963

2024-10-15 14:26 UTC, mattsse requested changes
why do we need `Transaction as _`?

these prs should be done on a per function basis to make fast progress because these prs are conflict magents in case we need to change something.

I'd like to hold off on the input fn until we're sure we don't use this anywhere where this change will be expensive

2024-10-15 14:50 UTC, tcoratger commented
> why do we need `Transaction as _`?
> 
> these prs should be done on a per function basis to make fast progress because these prs are conflict magents in case we need to change something.
> 
> I'd like to hold off on the input fn until we're sure we don't use this anywhere where this change will be expensive

@mattsse Understood, just opened a separate PR here https://github.com/paradigmxyz/reth/pull/11751, let me know if:
- You want me to do multiple PRs
- Or now that it's done keep this one and just remove what I did for the `input` function and keep it as before to prevent a bad use case?

2024-10-15 15:30 UTC, mattsse commented
this one's fine if we don't remove the input fn

2024-10-15 15:38 UTC, emhane approved these changes

2024-10-15 15:38 UTC, emhane commented on crates/rpc/rpc-types-compat/src/transaction/mod.rs
> +    let input = tx.transaction.input().to_vec().into();
disagree, it makes sense to return a slice and let the caller clone. in many places only the slice is needed.

2024-10-15 15:55 UTC, tcoratger commented on crates/primitives/src/transaction/mod.rs
> +        assert_eq!(tx.input(), hex!("1b55ba3a"));
```suggestion
assert_eq!(tx.input().as_ref(), hex!("1b55ba3a"));
```

2024-10-15 15:55 UTC, tcoratger commented on crates/rpc/rpc-types-compat/src/transaction/mod.rs
> +    let input = tx.transaction.input().to_vec().into();
```suggestion
    let input = tx.transaction.input().clone();
```

2024-10-15 15:55 UTC, tcoratger commented on crates/rpc/rpc/src/eth/helpers/signer.rs
> +        assert_eq!(message.to_vec(), txn_signed.unwrap().input().to_vec());
```suggestion
        assert_eq!(Bytes::from(message.to_vec()), txn_signed.unwrap().input().0);
```

2024-10-15 15:55 UTC, tcoratger commented on crates/rpc/rpc/src/eth/helpers/types.rs
> +                input: signed_tx.input().to_vec().into(),
```suggestion
                input: signed_tx.input().clone(),
```

2024-10-15 15:55 UTC, tcoratger commented on crates/transaction-pool/src/traits.rs
> +        self.transaction.input()
```suggestion
        self.transaction.input().as_ref()
```

2024-10-15 16:05 UTC, tcoratger commented on crates/rpc/rpc-types-compat/src/transaction/mod.rs
> +    let input = tx.transaction.input().to_vec().into();
@mattsse I feel like in the few cases I changed here it was more about simplifying usage than making it heavier but you're right it's better to specify the situation for this specific `input` function and decide something in a separate PR. So I reverted the changes made to this function so we can merge the PR and then see what we do for `input`.

2024-10-15 16:06 UTC, tcoratger commented
> this one's fine if we don't remove the input fn

@mattsse done, ready to review/merge

2024-10-15 17:21 UTC, mattsse commented on crates/rpc/rpc-types-compat/src/transaction/mod.rs
> +    let input = tx.transaction.input().to_vec().into();
this matters when we no longer need the slice but need to get `Bytes`, then this suddenly becomes expensive for no reason.

I agree that we can keep input -> slice but should have another function that returns `Bytes` for this usecase

2024-10-15 17:22 UTC, mattsse commented
pedantic clippy, otherwise lgtm

2024-10-15 22:48 UTC, tcoratger commented
> pedantic clippy, otherwise lgtm

@mattsse should be fixed

2024-10-15 22:51 UTC, tcoratger commented on crates/rpc/rpc-types-compat/src/transaction/mod.rs
> +    let input = tx.transaction.input().to_vec().into();
Yeah was thinking about the same dual approach, will open a follow up PR directly after this one is merged

2024-10-16 10:53 UTC, mattsse approved these changes

2024-10-16 12:06 UTC, mattsse commented
@tcoratger this drifted slightly and needs a small rebase

2024-10-16 12:20 UTC, tcoratger commented
> @tcoratger this drifted slightly and needs a small rebase

@mattsse should be fixed, ready to merge :)

2024-10-16 20:49 UTC, merged