feat: Introduce trait for OpTransaction
paradigmxyz/reth pull request #11745
Opened 2024-10-15 10:49 UTC by hoank101

Closed #11736

2024-10-15 14:28 UTC, mattsse requested changes

2024-10-15 14:28 UTC, mattsse commented on crates/primitives/src/transaction/mod.rs
> +impl DepositTransaction for Transaction {
please use full paths here and avoid the additonal feature gated import

2024-10-15 14:37 UTC, hoank101 commented on Cargo.toml
yeah, just for testing, will update new version

2024-10-15 14:44 UTC, hoank101 commented on crates/optimism/evm/src/execute.rs
> +use op_alloy_consensus::DepositTransaction;
thank you, i just update code

2024-10-26 10:55 UTC, hoank101 commented
hi @mattsse can you help me review, now not blocked

2024-10-29 14:14 UTC, mattsse approved these changes
lgtm

2024-10-29 14:49 UTC, merged