feat(cli): add ChainSpecParser type to rethCli
paradigmxyz/reth pull request #11772
Opened 2024-10-15 21:34 UTC by aroralanuk

I've added added  `ChainSpecParser` type to `RethCli` trait and updated the `NodeCommand` struct to use this instead.

Fixes https://github.com/paradigmxyz/reth/issues/11770

2024-10-16 07:59 UTC, mattsse requested changes

2024-10-16 07:59 UTC, mattsse commented on crates/cli/commands/src/node.rs
I want to do this is a separate pr, once we're happy with the rethcli and we've figured out better ergonomics, so please keep this as before for now

2024-10-16 07:59 UTC, mattsse commented on crates/cli/cli/src/lib.rs
> +    type ChainSpecParser: ChainSpecParser;
this is good!

2024-10-16 16:11 UTC, aroralanuk commented on crates/cli/commands/src/node.rs
Done!

2024-10-16 16:19 UTC, mattsse approved these changes

2024-10-16 16:45 UTC, aroralanuk commented
Sorry again :|

2024-10-17 16:21 UTC, aroralanuk commented
this can also be merged now @mattsse

2024-10-17 16:50 UTC, merged