feat(payload): introduce payload freezing for predetermined blocks
paradigmxyz/reth pull request #11790
Opened 2024-10-16 11:12 UTC by hoank101

Closed #11783

2024-10-16 11:15 UTC, mattsse requested changes

2024-10-16 11:15 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +pub enum PayloadState<P> {
ah cool this is actually better, but let's change the variants a bit to

```rust
Missing,
Best(P),
Frozen(P), 
```

2024-10-16 11:15 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +            if this.pending_block.is_none() && !matches!(this.best_payload, PayloadState::Frozen(_))
I want this as a function instead of the matches macro

2024-10-16 20:21 UTC, mattsse requested changes
a few more suggestions

2024-10-16 20:21 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +        }
we should return here and instead check this before we call this

2024-10-16 20:21 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +    }
this should be moved to PayloadState type, then we don't need any of the above

2024-10-16 20:21 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +        };
I also want to move this to a function of PayloadState instead

2024-10-16 20:21 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +        };
I also want to move this to a function of PayloadState instead

2024-10-16 20:21 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +}
this should be moved below the BasicPayloadJob type and impl

2024-10-16 20:21 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +    }
this should be moved to PayloadState type, then we don't need any of the above

2024-10-16 20:21 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +    }
this should be moved to PayloadState type, then we don't need any of the above

2024-10-16 20:21 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +        };
I also want to move this to a function of PayloadState instead

2024-10-16 20:21 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +}
this should be moved below the BasicPayloadJob type and impl

2024-10-17 03:00 UTC, hoank101 commented
thank @mattsse i just update

2024-10-17 13:17 UTC, mattsse requested changes
last nits

2024-10-17 13:17 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +    }
this fn is redundant because this is just `payload().cloned()`
so we can remove this

2024-10-17 13:17 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +            None => {
style nit: use if let Some here

2024-10-18 16:08 UTC, hoank101 commented
@mattsse help me review it, thank

2024-10-24 06:09 UTC, mattsse approved these changes
cool, very clean, nice work!

2024-10-24 06:43 UTC, merged