feat(rpc): Add flags to disable read tx timeout
paradigmxyz/reth pull request #11856
Opened 2024-10-17 21:06 UTC by 0x00101010

https://github.com/paradigmxyz/reth/issues/11672

Add a flag to disable read tx timeout for long running APIs like `debug_executionWitness`, `eth_getProof`, etc

2024-10-18 15:03 UTC, shekhirin approved these changes
LGTM, but would also appreciate @mattsse or @joshieDo review, I don't have full confidence that these places are the only ones where we need to pass this argument to.

2024-10-21 12:58 UTC, shekhirin requested changes
.

2024-10-22 01:26 UTC, joshieDo approved these changes

2024-10-22 10:07 UTC, mattsse approved these changes
lgtm, pending @shekhirin

2024-10-22 10:43 UTC, shekhirin approved these changes

2024-10-22 12:58 UTC, merged