feat: update el requests for devnet 4
paradigmxyz/reth pull request #11865
Opened 2024-10-18 01:42 UTC by onbjerg

2024-10-18 03:44 UTC, onbjerg commented
This also requires a lot of changes in op-alloy it seems. Seems like there were a lot of breaking changes in this alloy bump :)

2024-10-18 14:30 UTC, mattsse requested changes

2024-10-18 14:30 UTC, mattsse commented on crates/rpc/rpc-api/src/engine.rs
> +    async fn get_payload_v4(&self, payload_id: PayloadId) -> RpcResult<Engine::ExecutionPayloadV3>;
this must be V4 right?

2024-10-18 14:40 UTC, mattsse approved these changes

2024-10-18 14:40 UTC, mattsse commented on crates/ethereum/engine-primitives/src/payload.rs
> +            .unwrap_or_default();
this isn't ideal but works for vanilla payload builder, can improve later

2024-10-18 22:17 UTC, onbjerg commented
Not going to use https://github.com/alloy-rs/alloy/pull/1517 in this PR, but will create a follow up issue and work on it after to clean it up a bit.

2024-10-19 12:48 UTC, mattsse approved these changes

2024-10-19 12:48 UTC, mattsse commented on bin/reth/src/commands/debug_cmd/replay_engine.rs
> +                        beacon_engine_handle.new_payload(payload, cancun_fields, None).await?;
will take care of in followup

2024-10-19 13:04 UTC, merged