Refactor of state_change functionality
paradigmxyz/reth pull request #11878
Opened 2024-10-18 16:40 UTC by Gerson2102

This PR is addressing the refactor specified on this issue: #11818

2024-10-18 16:45 UTC, Gerson2102 commented
I'm not sure if this is what I had to do. I left a comment on the corresponding issue.

2024-10-18 19:34 UTC, mattsse requested changes
yep this is the first step, next step is removing the old file and updating the imports of where these functions are used

2024-10-18 22:59 UTC, Gerson2102 commented
Got it, lmk what you think now.

2024-10-19 08:47 UTC, mattsse requested changes
this looks good ty,

but I don't want to include the extra `;` please undo these

2024-10-19 08:47 UTC, mattsse commented on crates/engine/util/src/reorg.rs
please undo the extra `;` :)

2024-10-19 14:23 UTC, Gerson2102 commented
Got it @mattsse, lmk what u think now mate.

2024-10-19 15:22 UTC, mattsse approved these changes

2024-10-19 15:22 UTC, mattsse commented on crates/engine/util/src/reorg.rs
> +            continue;
```suggestion
            continue
```

2024-10-19 15:22 UTC, mattsse commented on crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
> +                continue;
```suggestion
                continue
```

2024-10-19 16:17 UTC, merged