primitives: use alloy eth conversion constants
paradigmxyz/reth pull request #11892
Opened 2024-10-19 09:35 UTC by tcoratger

2024-10-19 09:39 UTC, mattsse approved these changes

2024-10-19 15:01 UTC, onbjerg approved these changes
lgtm, needs a rebase though (sorry about that)

2024-10-19 15:48 UTC, tcoratger commented
> lgtm, needs a rebase though (sorry about that)

@onbjerg no problem, done :)

2024-10-20 00:37 UTC, onbjerg requested changes, later dismissed

2024-10-20 00:37 UTC, onbjerg commented on crates/ethereum/evm/src/strategy.rs
> +//! Ethereum block execution strategy,
needs to be removed, it's not on main

2024-10-20 07:38 UTC, tcoratger commented on crates/ethereum/evm/src/strategy.rs
> +//! Ethereum block execution strategy,
oups done

2024-10-20 22:00 UTC, tcoratger commented
@onbjerg Should be ready now, sorry for back and forth

2024-10-21 12:35 UTC, emhane approved these changes

2024-10-22 10:34 UTC, mattsse approved these changes

2024-10-22 10:34 UTC, merged