docs: update grafana docs
paradigmxyz/reth pull request #11908
Opened 2024-10-20 18:27 UTC by greged93

Update Grafana docs to detail how to upgrade dashboards.

@Rjected

2024-10-20 19:25 UTC, onbjerg requested changes

2024-10-20 19:25 UTC, onbjerg commented on etc/README.md
> +2. Access Grafana:
just use `1.` on all of these so we dont need to update them all the time. markdown will automatically convert them on render

2024-10-21 07:36 UTC, onbjerg requested changes

2024-10-21 07:56 UTC, greged93 commented on etc/README.md
> +If you are running Reth and Grafana outside of docker, and wish to import new Grafana dashboards or update a dashboard:
the issue with the [docker](https://github.com/paradigmxyz/reth/blob/main/etc/docker-compose.yml) provided in `etc` is that it sets the dashboards as provisioned dashboards, which prevents you from deleting them. Pulling the updated dashboards and restarting the Grafana service however worked fine

2024-10-21 09:42 UTC, onbjerg approved these changes

2024-10-21 09:58 UTC, merged