test(prune): add unit tests for `ReceiptsLogPruneConfig`
paradigmxyz/reth pull request #11916
Opened 2024-10-21 09:04 UTC by tcoratger

2024-10-24 05:27 UTC, mattsse requested changes
lgtm, ty

pending rm println

2024-10-24 05:27 UTC, mattsse commented on crates/prune/types/src/mode.rs
> +                println!("iciiiiiiiii: {}", tip - distance);
leftover

2024-10-24 05:47 UTC, tcoratger commented on crates/prune/types/src/mode.rs
> +                println!("iciiiiiiiii: {}", tip - distance);
oups sorry removed

2024-10-25 13:33 UTC, tcoratger commented
hey @mattsse nice bump here, anything missing?

2024-10-29 14:57 UTC, mattsse approved these changes

2024-10-29 15:12 UTC, merged