expose budgets for p2p via cli
paradigmxyz/reth pull request #11953
Opened 2024-10-22 03:41 UTC by stevencartavia

Hello @emhane !

This is a wip for #11637. I'm trying to follow the same steps as `max-pending-imports` from `crates/node/core/src/args/network.rs`, but the budgets are not showing up in the CLI. I'm uncertain if this is the right approach or if there's a better path to take.

2024-10-22 09:50 UTC, mattsse reviewed
are these really meaningful?

I'm skeptical that we should allow configure those via cli

2024-10-22 10:14 UTC, emhane requested changes
some more user friendly names and help to start with. good job so far! are you sure you rebuilt the code before running with `--help` in order to see the new flags?

2024-10-22 10:14 UTC, emhane commented on crates/node/core/src/args/network.rs
> +    pub budget_try_drain_swarm: u32,
```suggestion
    /// Budget for draining all ingress traffic, eth [and other capability] messages, and p2p connection updates. When the node has stabilised at max peer count, work done by an iteration in this stream will, to the most part, be accounted for by ingress traffic.
    pub budget_all_ingress: u32,
```

2024-10-22 10:14 UTC, emhane commented on crates/node/core/src/args/network.rs
> +    pub budget_try_drain_pending_pool_imports: u32,
```suggestion
    /// Budget for advancing import of transaction batches into pool.
    pub budget_pool_imports: u32,
```

2024-10-22 10:14 UTC, emhane commented on crates/node/core/src/args/network.rs
> +    pub budget_try_drain_pool_imports: u32,
```suggestion
    /// Budget for propagating transactions that have successfully been imported into pool.
    pub budget_propagate_gossip: u32,
```

2024-10-22 14:40 UTC, stevencartavia commented
> some more user friendly names and help to start with. good job so far! are you sure you rebuilt the code before running with `--help` in order to see the new flags?

yes, with `cargo build`, is there another way I should be building it?

2024-10-27 07:42 UTC, stevencartavia commented
@emhane, could you provide any insight into why this check failed? Thanks!

2024-10-27 07:49 UTC, emhane commented
> @emhane, could you provide any insight into why this check failed? Thanks!

check that you don't have any other white space other than newlines, in between the flags in the book, i.e. it could be that the cursor isn't at the margin on each new line but in fact some spaces into the page. hope that makes sense.

2024-10-27 08:39 UTC, stevencartavia commented
> > @emhane, could you provide any insight into why this check failed? Thanks!
> 
> check that you don't have any other white space other than newlines, in between the flags in the book, i.e. it could be that the cursor isn't at the margin on each empty new line but in fact some spaces into the page. hope that makes sense.

thank you!

2024-11-12 13:47 UTC, mattsse reviewed
this isn't useful as cli options

2024-11-12 13:47 UTC, closed without merging