feat: introduce iterator for default_ethereum_payload function
paradigmxyz/reth pull request #11978
Opened 2024-10-22 19:11 UTC by edisontim

Closes #11889

2024-10-22 19:12 UTC, edisontim commented
@mattsse, is this what you had in mind?

2024-10-24 05:24 UTC, mattsse requested changes
cool, only have style nits

2024-10-24 05:24 UTC, mattsse commented on crates/ethereum/payload/src/lib.rs
> +pub fn default_ethereum_payload<EvmConfig, Pool, Client, IteratorClosure>(
let's just name this F
```suggestion
pub fn default_ethereum_payload<EvmConfig, Pool, Client, F>(
```

2024-10-24 05:24 UTC, mattsse commented on crates/ethereum/payload/src/lib.rs
> +    build_best_txs_closure: IteratorClosure,
```suggestion
    best_txs: IteratorClosure,
```

2024-10-24 05:24 UTC, mattsse commented on crates/ethereum/payload/src/lib.rs
> +    Box<dyn BestTransactions<Item = Arc<ValidPoolTransaction<Transaction>>>>;
let's make this generic over pool

`type BestTransactionsFor<Pool> = Box<dyn BestTransactions<Item = Arc<ValidPoolTransaction<<Pool as TransactionPool>::Transaction>>>>`

2024-10-24 05:24 UTC, mattsse commented on crates/ethereum/payload/src/lib.rs
> +        let iterator_closure = |attributes| pool.best_transactions_with_attributes(attributes);
we don't need a tmp var for this and can make this the argument directly

2024-10-24 05:24 UTC, mattsse commented on crates/ethereum/payload/src/lib.rs
> +            iterator_closure,
same here

2024-10-25 11:48 UTC, mattsse approved these changes
great

2024-10-25 12:04 UTC, merged