Improve debug_traceBlock performance
paradigmxyz/reth pull request #11979
Opened 2024-10-22 19:18 UTC by lakshya-sky

Fixes #11066

2024-10-23 13:41 UTC, mattsse requested changes
cool, left some suggestions

2024-10-24 04:45 UTC, emhane approved these changes
lgtm

2024-10-26 07:30 UTC, mattsse approved these changes
lgtm, ty

2024-10-26 07:30 UTC, mattsse commented on crates/rpc/rpc/src/debug.rs
> +                        let mut inspector = shared_inspector.get_or_insert(TracingInspector::new(
ah turns out we can't easily do this because we need the config

2024-10-26 07:59 UTC, merged