TransactionsHandle propagation commands should not adhere to caching
paradigmxyz/reth pull request #12079
Opened 2024-10-25 15:05 UTC by Parikalp-Bhardwaj

Closes #12033

**Description:**
This pull request addresses the issue where manual propagation commands in `TransactionsHandle` were adhering to caching, preventing forced broadcasts. The following changes have been made:

- **Added `CachePolicy` Enum:**
  Introduced a `CachePolicy` enum with variants `IgnoreCache` and `RespectCache` to control caching behavior during transaction propagation.

- **Modified Propagation Methods:**
  Updated methods such as `propagate_full_transactions_to_peer`, `propagate_hashes_to`, and `propagate_transactions` to accept a `CachePolicy` parameter.

- **Updated Manual Propagation Commands:**
  In the `on_command` method, manual propagation commands now use `CachePolicy::IgnoreCache` to bypass the cache, allowing forced broadcasts.

- **Ensured Regular Propagation Respects Cache:**
  Regular propagation commands continue to use `CachePolicy::RespectCache`, maintaining the caching mechanism to optimize network usage.

- **Updated Tests:**
  Modified existing tests and added new ones to cover scenarios with both cache policies, ensuring that the caching behavior is as expected.

Please review the changes and let me know if any adjustments are needed.

2024-10-25 17:57 UTC, mattsse requested changes
cool, functionally this is correct.

only have style nits

2024-10-25 17:57 UTC, mattsse commented on crates/net/network/src/transactions/mod.rs
>                  }
let's convert this into an if by adding a `fn is_forced` instead

2024-10-25 17:57 UTC, mattsse commented on crates/net/network/src/transactions/mod.rs
> +}
I'd like to rename this slightly to something like

```rust
enum PropgateKind {
  /// Default propgation mode, filters out txs that we already sent or received
  Basic,
  /// Always propagate, even if we already sent or received the txs.
  Forced,
}

2024-10-26 16:09 UTC, mattsse requested changes
ah, I see we already have an enum that is used with that name.

we need a new enum just for this, with the two variants. this should not change the existing enum

2024-10-26 19:33 UTC, Parikalp-Bhardwaj commented
@mattsse done, Created a new enum `PropgateKind` with the two variants.

2024-10-27 14:57 UTC, mattsse approved these changes

2024-10-27 15:24 UTC, merged