Osiris/fix payload
paradigmxyz/reth pull request #12089
Opened 2024-10-26 01:04 UTC by 0xOsiris

Attempt at Fixing #11729 

This PR addresses #12071 as well, and is stacked on top of #11730.

Trying to get this over the finish line.

2024-10-26 16:31 UTC, mattsse requested changes
this is great tysm

but I'd like to introduce all payload id changes separately

2024-10-26 16:31 UTC, mattsse commented on crates/ethereum/engine-primitives/src/payload.rs
I'd like to limit this pr to just the additional field in the fcu enum, because for the payload id we already have https://github.com/paradigmxyz/reth/pull/11730

2024-10-26 16:31 UTC, mattsse commented on crates/optimism/payload/src/payload.rs
I'd like to do this separately and only introduce the new enum variant field in this one

2024-10-26 16:31 UTC, mattsse commented on crates/optimism/payload/src/payload.rs
> +    fn test_payload_id_parity_op_geth() {
these are great though, so please open this as a separate one.

2024-10-26 16:31 UTC, mattsse commented on crates/payload/primitives/src/lib.rs
> +    V4 = 4,
yep we can solve this like this

2024-10-26 19:19 UTC, 0xOsiris commented
> this is great tysm
> 
> but I'd like to introduce all payload id changes separately

Sounds good, @mattsse Just reverted the changes related to the payload id

2024-10-28 12:00 UTC, mattsse approved these changes
lgtm,

next pr would be, adding the version as additional to

https://github.com/paradigmxyz/reth/blob/1b0f625f1d315473b86fc38153a7c5ed27d27ffa/crates/payload/primitives/src/traits.rs#L85-L88

then we can finally get the other pr over the line

2024-10-28 12:00 UTC, merged