refactor: without-evm cli option in reth
paradigmxyz/reth pull request #12134
Opened 2024-10-28 11:56 UTC by debjit-bw

Fixes #12090

Added CLI command to `init-state` without previously having to import blocks/receipts.

In order to try it out, you can use the following:
* [Example value for --header](https://github.com/debjit-bw/reth/blob/6cf525abb072cc20f95f29ef065412de6e6b55ea/header.rlp)
* [Example .jsonl state](https://github.com/debjit-bw/reth/blob/6cf525abb072cc20f95f29ef065412de6e6b55ea/test_dump.jsonl)

The optimism-specific implementation for op-geth hasn't been removed/modified.

2024-10-28 13:33 UTC, mattsse requested changes
hmm, this does now add the an additional command that isn't very useful for the regular ethereum CLI.

my idea for this was more like converting the existing pre-bedrock functions so that they are reusable and then move them as additional functions into the commands crate and optionally also include them into the init state command.

but this left the pre-bedrock functions untouched so far

2024-10-28 14:19 UTC, debjit-bw commented
A unit test failed with this message:

```
The hosted runner: RethRunner_4145f40b940a lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

2024-10-29 05:13 UTC, joshieDo approved these changes
some nits, but lgtm

mind adding the example as an actual test of `setup_without_evm` ?

2024-10-29 07:51 UTC, debjit-bw commented on crates/optimism/cli/src/commands/init_state.rs
> +                ));
lol mp, just pushed the fix

2024-10-29 08:35 UTC, debjit-bw commented
@mattsse can you have a look?

2024-10-29 10:59 UTC, mattsse approved these changes
lgtm

2024-10-29 10:59 UTC, mattsse commented on crates/cli/commands/src/init_state/mod.rs
> +    without_evm: bool,
```suggestion
    pub without_evm: bool,
```

2024-10-29 11:30 UTC, merged