feat: make js-tracer feature optional for node builder crate
paradigmxyz/reth pull request #12178
Opened 2024-10-29 22:11 UTC by edisontim

2024-10-30 11:35 UTC, mattsse requested changes
need some clarification on the issue first to proceed here

2024-10-30 11:35 UTC, mattsse commented on crates/node/builder/Cargo.toml
> +js-tracer = ["reth-rpc/js-tracer"]
this should go above test-utils

2024-10-30 13:03 UTC, mattsse requested changes
we also need to enable this in the node crates for ethereum and optimism to actually enable this:

https://github.com/paradigmxyz/reth/blob/129f3ba9116da0fcbfafb78e66b7a0163e5464d3/crates/optimism/node/Cargo.toml#L23-L23

https://github.com/paradigmxyz/reth/blob/129f3ba9116da0fcbfafb78e66b7a0163e5464d3/crates/ethereum/node/Cargo.toml#L19-L19

2024-10-30 13:56 UTC, edisontim commented
> we also need to enable this in the node crates for ethereum and optimism to actually enable this:
> 
> https://github.com/paradigmxyz/reth/blob/129f3ba9116da0fcbfafb78e66b7a0163e5464d3/crates/optimism/node/Cargo.toml#L23-L23
> 
> https://github.com/paradigmxyz/reth/blob/129f3ba9116da0fcbfafb78e66b7a0163e5464d3/crates/ethereum/node/Cargo.toml#L19-L19

Sure! Should I make this a default when building or also opt is as a feature?

2024-10-30 16:16 UTC, storopoli commented
> > we also need to enable this in the node crates for ethereum and optimism to actually enable this:
> > https://github.com/paradigmxyz/reth/blob/129f3ba9116da0fcbfafb78e66b7a0163e5464d3/crates/optimism/node/Cargo.toml#L23-L23
> > 
> > https://github.com/paradigmxyz/reth/blob/129f3ba9116da0fcbfafb78e66b7a0163e5464d3/crates/ethereum/node/Cargo.toml#L19-L19
> 
> Sure! Should I make this a default or also make it as a feature in optimism and eth crate? `reth-node-builder = { workspace = true, features = ["js-tracer"] }` or
> 
> ```
> js-tracer = [
> 	"reth-node-builder/js-tracer"
> ]
> ```

If possible make it all a feature and opt-in.
The `boa` machinery should, in my humble opinion, be opt-in.
It really increases the compile time for users and also for everything that it encompasses such as CI for example.

2024-10-30 16:20 UTC, delbonis commented
I'm also needing this.  This should be opt-in, at the very least because (as it is right now) it makes API consumer have to build the whole JS engine even when they don't use it.  I don't know if there's some issue with the crate hierarchy that makes the exposing the types in the API necessitate building the engine crates, that seems strange.

2024-11-08 21:04 UTC, edisontim commented
Hey @mattsse, i think this is ready for review if you could have a look :)

2024-11-09 07:45 UTC, mattsse commented
> I don't know if there's some issue with the crate hierarchy that makes the exposing the types in the API necessitate building the engine crates, that seems strange.

could please elaborate, which crates exactly @delbonis

2024-11-09 07:48 UTC, mattsse requested changes
this still removes js-tracer support from the binary because now it is no longer enabled.

we either need this for ethereum node and optimism node by default or must enable this in the binary.

2024-11-12 15:13 UTC, edisontim commented
> this still removes js-tracer support from the binary because now it is no longer enabled.
> 
> we either need this for ethereum node and optimism node by default or must enable this in the binary.

Done !

2024-11-12 15:29 UTC, mattsse requested changes
we also n

2024-11-12 15:29 UTC, mattsse commented on bin/reth/Cargo.toml
we need this for the optimimism/bin as well

2024-11-29 08:49 UTC, storopoli commented
friendly bump 😄

2024-11-29 13:09 UTC, mattsse commented
thanks, wrapping up here now

2024-11-29 14:15 UTC, mattsse approved these changes

2024-11-29 14:29 UTC, merged

2024-11-29 17:43 UTC, storopoli commented
Nice thanks! :)
When does `reth` releases a new version?