txpool: added a helper to filter pending txns by predicate
paradigmxyz/reth pull request #12204
Opened 2024-10-30 16:36 UTC by lakshya-sky

2024-10-30 19:31 UTC, mattsse requested changes

2024-10-30 19:31 UTC, mattsse commented on crates/transaction-pool/src/traits.rs
> +    }
this is great, but in order to optimize this I'd like to not use a default impl here and instead also go through the layers, see 
get_pending_transactions_by_sender for reference

2024-11-01 03:12 UTC, lakshya-sky commented
@mattsse ready for review.

2024-11-01 11:10 UTC, mattsse approved these changes

2024-11-01 11:10 UTC, mattsse commented
clippy unrelated

2024-11-01 11:10 UTC, merged