feat: track buffered outgoing messages
paradigmxyz/reth pull request #12220
Opened 2024-10-30 23:54 UTC by caglaryucekaya

Closes #12203

2024-10-31 10:33 UTC, mattsse requested changes
nits

2024-10-31 10:33 UTC, mattsse commented on crates/net/network/src/session/active.rs
> +    count: Gauge,
looking at the ordering in Gaugefn impl for Atomic I believe this should work and not result in overflows

2024-10-31 19:59 UTC, caglaryucekaya commented on crates/net/network/src/session/active.rs
> +    pub fn pop_front(&mut self) -> Option<OutgoingMessage> {
Done

2024-10-31 19:59 UTC, caglaryucekaya commented on crates/net/network/src/session/active.rs
> +        }
Done

2024-10-31 19:59 UTC, caglaryucekaya commented on crates/net/network/src/session/active.rs
> +}
Done

2024-11-01 11:32 UTC, mattsse approved these changes
lgtm

2024-11-01 11:47 UTC, merged