feat: add gas averages over time into grafana
paradigmxyz/reth pull request #12237
Opened 2024-10-31 20:08 UTC by edisontim

2024-11-01 21:33 UTC, Rjected requested changes
thanks! just notes on the legend, also can we also add a 30m one?

2024-11-01 21:33 UTC, Rjected commented on etc/grafana/dashboards/overview.json
> +            "legendFormat": "avg/m",
```suggestion
            "legendFormat": "Avg Gas/s (1m)",
```

2024-11-01 21:33 UTC, Rjected commented on etc/grafana/dashboards/overview.json
> +            "legendFormat": "avg/5m",
```suggestion
            "legendFormat": "Avg Gas/s (5m)",
```

2024-11-01 21:33 UTC, Rjected commented on etc/grafana/dashboards/overview.json
> +            "legendFormat": "avg/10m",
```suggestion
            "legendFormat": "Avg Gas/s (10m)",
```

2024-11-01 21:33 UTC, Rjected commented on etc/grafana/dashboards/overview.json
> +            "legendFormat": "avg/h",
```suggestion
            "legendFormat": "Avg Gas/s (1h)",
```

2024-11-01 21:33 UTC, Rjected commented on etc/grafana/dashboards/overview.json
> +            "legendFormat": "avg/24h",
```suggestion
            "legendFormat": "Avg Gas/s (24h)",
```

2024-11-02 01:02 UTC, Rjected approved these changes
Awesome thanks!

2024-11-06 10:19 UTC, mattsse approved these changes

2024-11-06 10:35 UTC, merged