Track time diff between `new_payload` and FCU
paradigmxyz/reth pull request #12245
Opened 2024-11-01 06:54 UTC by stevencartavia

wip #12212

2024-11-01 06:59 UTC, stevencartavia commented
Hello @mattsse, let me know your thoughts on this approach and whether it should be applied to the other payloads or if any adjustments are needed.

2024-11-01 10:37 UTC, mattsse requested changes
great, some suggestions

2024-11-01 10:37 UTC, mattsse commented on crates/rpc/rpc-engine-api/src/engine_api.rs
> +};
this should use parking_lot::Mutex

2024-11-01 10:37 UTC, mattsse commented on crates/rpc/rpc-engine-api/src/engine_api.rs
> +    start_time: Mutex<Option<Instant>>,
this should go into the inner type, because the `EngineApi` type is cloned per request

2024-11-01 10:37 UTC, mattsse commented on crates/rpc/rpc-engine-api/src/engine_api.rs
> +        self.inner.metrics.payload_to_fcu_latency.new_payload_v1_time_diff.record(elapsed_time);
we can make this a standalone function of the inner type

2024-11-01 10:37 UTC, mattsse commented on crates/rpc/rpc-engine-api/src/engine_api.rs
> +            .expect("start_time should be set before fork_choice_updated_v1 is called")
and this can't use unwrap here, and should only update if there is an instant

2024-11-01 10:37 UTC, mattsse commented on crates/rpc/rpc-engine-api/src/engine_api.rs
> +            .unwrap()
```suggestion
            .take()
```

2024-11-01 18:28 UTC, stevencartavia commented
@mattsse comments addressed, let me know how it looks :)

2024-11-06 10:06 UTC, mattsse approved these changes
lgtm

2024-11-06 10:35 UTC, merged