Use global secp256k1 context for tests
paradigmxyz/reth pull request #12339
Opened 2024-11-05 19:49 UTC by Jonatan-Chaverri

Closes https://github.com/paradigmxyz/reth/issues/12260

2024-11-06 08:44 UTC, mattsse requested changes
I think we want to use the global context for all of these fns because even the signing context still does new randomization

2024-11-06 08:44 UTC, mattsse commented on testing/testing-utils/Cargo.toml
> +secp256k1 = { workspace = true, features = ["rand", "global-context"] }
this actually looks unused because no changes actually use the global context

2024-11-06 08:44 UTC, mattsse commented on testing/testing-utils/src/generators.rs
> +    let secp = Secp256k1::signing_only();
this isn't the global context

2024-11-07 18:03 UTC, Jonatan-Chaverri commented
@mattsse please check again and let me know if this is what you mean by global context

2024-11-08 12:04 UTC, mattsse approved these changes

2024-11-08 13:12 UTC, merged