introduce standalone estimate gas type
paradigmxyz/reth pull request #12344
Opened 2024-11-06 04:55 UTC by stevencartavia

#12250

2024-11-06 08:36 UTC, mattsse requested changes

2024-11-06 08:36 UTC, mattsse commented on crates/rpc/rpc-eth-api/src/helpers/estimate.rs
> +    inner: Arc<T>,
we can remove the arc here

2024-11-06 08:36 UTC, mattsse commented on crates/rpc/rpc-eth-api/src/helpers/estimate.rs
> +    ) -> impl Future<Output = Result<U256, T::Error>> + Send {
we def want this as a new trait `trait GasEstimator`

2024-11-06 08:36 UTC, mattsse commented on crates/rpc/rpc-eth-api/src/helpers/estimate.rs
> +                .await
all this does here is reuse the existing estimate trait.

what we want instead is to extract this into a standalone type

2024-11-12 14:03 UTC, mattsse requested changes

2024-11-12 14:03 UTC, mattsse commented on crates/rpc/rpc-eth-api/src/helpers/call.rs
this must be updated so that the estimate functions are removed here

2024-11-14 12:17 UTC, mattsse approved these changes
I've completed this by updating some bounds, because this isn't super obvious

2024-11-14 12:48 UTC, mattsse commented
cc @tcoratger

2024-11-14 12:49 UTC, merged

2024-11-14 12:49 UTC, tcoratger commented
> cc @tcoratger
> 
> this decouples estimation but could likely need more work

@mattsse @stevencartavia thanks guys :)