feat(rpc): add compression to JSON-RPC
paradigmxyz/reth pull request #12352
Opened 2024-11-06 16:45 UTC by TheDhejavu

## Description
Resolves: #9652

This adds a compression layer that wraps [`tower_http::compression::CompressionLayer`](https://github.com/tower-rs/tower-http/blob/main/tower-http/src/compression/layer.rs) and adapts it to work with jsonrpsee's HTTP types. The layer automatically compresses responses based on the client's `Accept-Encoding` header while preserving the middleware chain's expected body type.

Supports:
  - `gzip`
  - `deflate`
  - `brotli`
  - `zstd`

### Demo
<img width="450" alt="Screenshot 2024-11-11 at 11 35 25 AM" src="https://github.com/user-attachments/assets/4c6c9686-ebe3-4dd8-acb5-0819a29ee28f">

2024-11-07 16:37 UTC, mattsse requested changes
cool, but I think hyper doesn't apply any changes to the body automatically so we'd need to do that

this seems relevant:

https://github.com/paritytech/jsonrpsee/issues/1133

2024-11-08 14:24 UTC, TheDhejavu commented
> cool, but I think hyper doesn't apply any changes to the body automatically so we'd need to do that
> 
> this seems relevant:
> 
> [paritytech/jsonrpsee#1133](https://github.com/paritytech/jsonrpsee/issues/1133)

Thanks!!

figured out that reth has `tower-http` as a dependency and compression middleware is implemented by default which works out-of-the-box with `jsonrpee` with their recent release [here](https://github.com/paritytech/jsonrpsee/releases/tag/v0.24.7). 

in the case of this: https://github.com/paritytech/jsonrpsee/issues/1133#issuecomment-1562534957, the implementation is quite similar to what i did here but i will need to modify the body in order to compress it.

this will be the only change i will probably need to make if i use tower compression layer implementation.
```rust
use tower_http::compression::CompressionLayer;

impl<RpcMiddleware> RpcServerConfig<RpcMiddleware> {
    //.....other middlewares

    /// Returns a [`CompressionLayer`] that adds compression support (gzip, deflate, brotli, zstd)
    /// based on the client's `Accept-Encoding` header
    const fn maybe_compression_layer() -> Option<CompressionLayer> {
          Some(CompressionLayer::new())
    }
}
```

wdyt ?

2024-11-09 16:27 UTC, mattsse commented
cool, sgtm!

2024-11-11 11:02 UTC, TheDhejavu commented
cc @mattsse .

2024-11-12 17:14 UTC, mattsse requested changes
great!

only have pedantic style nits

2024-11-12 17:14 UTC, mattsse commented on crates/rpc/rpc-layer/src/compression_layer.rs
> +/// Created by [`CompressionLayer`].
same

2024-11-12 20:20 UTC, TheDhejavu commented on Cargo.toml
> +tower-http = { version = "0.6", features = ["full"] }
removed, but i left the upgrade.

2024-11-12 21:24 UTC, mattsse approved these changes

2024-11-12 23:12 UTC, merged