chore: move trie functions to alloy
paradigmxyz/reth pull request #12438
Opened 2024-11-10 18:42 UTC by c0np4nn4

2024-11-10 19:21 UTC, mattsse requested changes
please undo the additional `;`, otherwise lgtm

2024-11-12 03:41 UTC, Rjected submitted a review, later dismissed
needs cargo fmt + must propagate the std feature now, otherwise looks good

2024-11-12 09:13 UTC, fgimenez approved these changes

2024-11-12 10:15 UTC, mattsse approved these changes

2024-11-12 10:32 UTC, merged