Reafactor/move structs to args mod
paradigmxyz/reth pull request #1250
Opened 2023-02-09 13:37 UTC by chirag-bgh

fixes #1243

2023-02-09 13:49 UTC, mattsse requested changes

2023-02-09 13:49 UTC, mattsse commented on bin/reth/src/args/rpc_server_args.rs
> -/// Parameters for configuring the network more granularity via CLI
we need to keep lib and only move the types to a new module `args`

2023-02-09 15:05 UTC, mattsse commented on bin/reth/src/args/mod.rs
> +pub mod rpc_server_args;
nit: use `mod` and reexport via `pub use network_args::NetworkArgs;`

2023-02-09 17:00 UTC, mattsse approved these changes
lgtm

pending @onbjerg

2023-02-11 05:21 UTC, gakonst approved these changes
good w me

2023-02-11 05:21 UTC, merged