add networkprimitives for netoworkmanager
paradigmxyz/reth pull request #12530
Opened 2024-11-13 22:45 UTC by lakshya-sky

Closes #12517

2024-11-14 09:26 UTC, klkvr commented
you should also add generic to its implementations, eg here:

https://github.com/paradigmxyz/reth/blob/68a6ada460c31c74f25d3b5418b8bc878edfe082/crates/net/network/src/manager.rs#L119

this would highlight some more places where generic is required

2024-11-15 04:58 UTC, lakshya-sky commented
@klkvr could you help me a bit here? I've updated all the places but it seems I can't keep up with the chain of all generics.

2024-11-15 09:00 UTC, mattsse requested changes

2024-11-15 09:02 UTC, mattsse commented on crates/net/network-api/src/events.rs
this I'd like to change separately

2024-11-15 09:48 UTC, klkvr commented
@lakshya-sky the issue is that here stream expects a stream of `NodeEvent`s with default generic but it is actually generic over `NetworkEventListenerProvider::NetworkPrimitives`

I think for now it should be OK to remove NetworkPrimitives generic from NodeEvent and instead just convert `Established` events into `Other` variant

2024-11-15 18:22 UTC, mattsse approved these changes
lgtm

2024-11-16 04:59 UTC, merged