Improve metrics hooks setup (fixes #12672)
paradigmxyz/reth pull request #12684
Opened 2024-11-19 19:06 UTC by nils-mathieu

This pull request fixes #12672.

It adds the type `HooksBuilder`, responsible for creating new custom instances of the `Hooks` collection.

# Changes

- Add the `HooksBuilder` type.
- Add the `Hooks::builder` method to create a new `HooksBuilder`.
- Change the calls to `Hooks::new` by `Hooks::builder`.
- Remove `Hooks::new`.

# Other

- I had to fix a compilation error here (there was a comparaison between `i32` and `u32`:
https://github.com/paradigmxyz/reth/blob/7c7baca9807e9a9556cb217d3df8cd03c21ba4ed/crates/storage/libmdbx-rs/src/environment.rs#L431-L444

- I changed a `format!` to a `format_args!` in a `Debug` implementation to save on an allocation.

2024-11-19 20:38 UTC, nils-mathieu commented
The `ffi::MDBX_RDONLY` type and friends seem to have different types on my machine (Windows 11) than they are on the testing environment.

Should I duplicate the function? Ideally the contant themselves should change not to change type depending on the compilation target, I guess.

2024-11-19 20:48 UTC, mattsse requested changes
great start

2024-11-19 20:50 UTC, mattsse commented
regarding the different mdbx type, could you ptal at

https://github.com/paradigmxyz/reth/issues/12259#issuecomment-2452962847

2024-11-19 21:31 UTC, nils-mathieu commented on crates/node/metrics/src/hooks.rs
> +        provider: StaticFileProvider<N>,
understood, will do

2024-11-20 09:51 UTC, mattsse reviewed
lgtm, 

could you please apply the changes here

https://github.com/paradigmxyz/reth/pull/12698

can't push to your main branch

2024-11-20 09:51 UTC, mattsse commented on crates/node/metrics/Cargo.toml
> -reth-provider.workspace = true
great

2024-11-20 15:04 UTC, nils-mathieu commented
@mattsse done!

2024-11-21 16:47 UTC, mattsse approved these changes

2024-11-21 17:22 UTC, merged