(WIP) use payloadbuilder for build_block
paradigmxyz/reth pull request #12725
Opened 2024-11-21 01:42 UTC by SkandaBhat

FIxes #12535

2024-11-21 10:29 UTC, mattsse requested changes

2024-11-21 10:29 UTC, mattsse commented on crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
>      {
I'd rather not provide a default impl to prevent issues

2024-11-21 10:29 UTC, mattsse commented on crates/rpc/rpc/src/eth/helpers/pending_block.rs
> +                let sealed_block = payload.block().clone();
can't this use the configured payload builder?

https://github.com/paradigmxyz/reth/blob/33730536f5e5de1403f2deb3c7dbe551879b9724/crates/rpc/rpc-eth-api/src/node.rs#L34-L35

2024-11-25 11:13 UTC, mattsse requested changes
overall, this looks pretty good already

2024-11-25 11:13 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +            return http.merge(other.into()).map(|_| true);
```suggestion
            return http.merge(other.into()).map(|_| true)
```

2024-11-25 11:13 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +            return ws.merge(other.into()).map(|_| true);
```suggestion
            return ws.merge(other.into()).map(|_| true)
```

2024-11-25 11:13 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +            return ipc.merge(other.into()).map(|_| true);
```suggestion
            return ipc.merge(other.into()).map(|_| true)
```

2024-11-25 11:13 UTC, mattsse commented on crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
> +                        return Ok(Some((block, receipts)));
```suggestion
                        return Ok(Some((block, receipts)))
```

2024-11-25 11:13 UTC, mattsse commented on crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
> +                    return Ok(None);
```suggestion
                    return Ok(None)
```

2024-11-25 11:13 UTC, mattsse commented on crates/rpc/rpc/src/eth/core.rs
> +    type PayloadBuilder = EthereumPayloadBuilder<EvmConfig>;
we need to solve this a little bit differently, 
similar to how provider is integrated, via a generic. but for this pr this  should be okay.

2024-11-26 12:14 UTC, SkandaBhat commented
@mattsse have addressed comments and created an issue https://github.com/paradigmxyz/reth/issues/12844 to track EthereumPayloadBuilder. This is ready for review.

2024-12-17 23:31 UTC, mattsse reviewed
sorry this turned out to be more complex than anticipated and we had to solve this differntly

2024-12-17 23:32 UTC, closed without merging