Plug ovm codec into ImportOpCommand
paradigmxyz/reth pull request #12759
Opened 2024-11-21 20:38 UTC by lakshya-sky

Towards #12587

2024-11-21 20:42 UTC, lakshya-sky commented
this is incomplete and cuts too many corners. but the bigger issue is `reth_providers::DatabaseProvider` is tightly coupled with `reth_primitives::BlockBody`, which doesn't allow using `reth_optimism_cli::ovm_file_codec::BlockBody`.

2024-11-21 20:44 UTC, lakshya-sky commented on crates/optimism/cli/src/commands/build_pipeline.rs
>  {
here is the all problem and would require a large refactor.

2024-11-21 20:47 UTC, lakshya-sky commented on crates/optimism/cli/src/commands/build_pipeline.rs
`build_import_pipeline` fails to compile with the error
```
error[E0271]: type mismatch resolving `<DatabaseProvider<<<N as NodeTypesWithDB>::DB as Database>::TXMut, N> as BlockWriter>::Body == BlockBody`
   --> crates/optimism/cli/src/commands/build_pipeline.rs:95:14
    |
95  |             .builder()
    |              ^^^^^^^ expected `BlockBody`, found a different `BlockBody`
    |
    = note: `BlockBody` and `BlockBody` have similar names, but are actually distinct types
note: `BlockBody` is defined in crate `reth_primitives`
   --> /home/dkathiriya/projects/reth/crates/primitives/src/block.rs:591:1
    |
591 | pub struct BlockBody {
    | ^^^^^^^^^^^^^^^^^^^^
note: `BlockBody` is defined in the current crate
   --> crates/optimism/cli/src/ovm_file_codec.rs:102:1
    |
102 | pub struct BlockBody {
    | ^^^^^^^^^^^^^^^^^^^^
    = note: required for `BodyStage<TaskDownloader<BlockBody>>` to implement `reth_stages::Stage<DatabaseProvider<<<N as NodeTypesWithDB>::DB as reth_db::Database>::TXMut, N>>`
    = note: required for `OnlineStages<ProviderFactory<N>, ..., ...>` to implement `StageSet<DatabaseProvider<<<N as NodeTypesWithDB>::DB as reth_db::Database>::TXMut, N>>`
    = note: 1 redundant requirement hidden
    = note: required for `DefaultStages<ProviderFactory<...>, ..., ..., ...>` to implement `StageSet<DatabaseProvider<<<N as NodeTypesWithDB>::DB as reth_db::Database>::TXMut, N>>`
   ```

2024-11-21 20:48 UTC, lakshya-sky commented on crates/optimism/cli/src/commands/build_pipeline.rs
I assume fixing this would require a large refactor of `DatabaseProvider`?

2024-11-23 12:01 UTC, emhane requested changes
Since BlockFileCodec was made generic over Block, I think it makes more sense to pass the Block in the ovm codec file to the original BlockFileCodec, does that make sense?

2024-11-25 14:00 UTC, lakshya-sky commented
> Since BlockFileCodec was made generic over Block, I think it makes more sense to pass the Block in the ovm codec file to the original BlockFileCodec, does that make sense?

You're right and I did that on my first attempt. But ends up on the same error as this one.

2024-11-27 10:10 UTC, emhane commented on crates/optimism/cli/src/commands/build_pipeline.rs
`DatabaseProvider` is generic over `N: NodeTypes`, so should be possible to use with custom `N::Primitives`, i.e. making a new type
```rust
pub struct OvmPrimitives {
    type BlockBody = ovm_file_codec::BlockBody;
    ..
}
```
and implementing the `reth_primitives_traits::BlockBody` trait for `ovm_file_codec::BlockBody` etc. then make a copy of the `OpNode` called `OvmNode`, replacing `type Primitives = OpPrimitives` with `type Primitives = OvmPrimitives`. 

if you could impl these changes now, it's not sure if it will be able to take effect right away, since the complete integration of generic data primitives is pending https://github.com/paradigmxyz/reth/issues/12454. however this pr will definitely be merged once it compiles.

2024-11-27 16:19 UTC, lakshya-sky commented on crates/optimism/cli/src/commands/build_pipeline.rs
I was thinking maybe move `ovm_file_codec::{Block, BlockBody, *} to primitives and update `OpPrimitives` itself with the new primitives. That way we won't have to introduce `OvmNode` and `OvmPrimitives`?

2024-11-27 18:32 UTC, emhane commented on crates/optimism/cli/src/commands/build_pipeline.rs
`OpNode` is EVM since the bedrock hardfork, that's why we are importing the OVM part of the op mainnet chain by this command as opposed to the traditional way: syncing from peers

2024-11-27 22:32 UTC, lakshya-sky commented
@emhane the scope of this pr is huge compared to what I thought. Despite adding `OvmNode` and `OvmPrimitives` it wouldn't compile. Each stage needs to be made generic over primitives then only `OvmCodec` could be used. I think I'll close this for now and comeback in future.

2024-11-27 22:33 UTC, closed without merging