feat: generic data primitives PersistenceHandle
paradigmxyz/reth pull request #12968
Opened 2024-11-28 14:22 UTC by hoank101

Closes #12942

2024-11-29 08:05 UTC, emhane requested changes, later dismissed

2024-11-29 08:05 UTC, emhane commented on crates/engine/tree/src/persistence.rs
> +pub struct PersistenceHandle<N: PersistenceNodeTypes = reth_primitives::EthPrimitives> {
the trait bound should be `NodePrimitives` not `PersistenceNodeTypes`

2024-11-30 11:33 UTC, mattsse approved these changes

2024-11-30 11:33 UTC, mattsse commented on crates/engine/tree/src/persistence.rs
> +    _marker: std::marker::PhantomData<N>,
in a next step, we need to apply the same to PersistenceAction, then we can get rid of the phantomdata

2024-11-30 16:03 UTC, merged