perf: profile TransactionsManager::poll hash fetching
paradigmxyz/reth pull request #12975
Opened 2024-11-28 16:08 UTC by Elvis339

Issue: https://github.com/paradigmxyz/reth/issues/12842

This PR attempts to profile TransactionsManager::poll hash fetching.

2024-11-28 16:11 UTC, Elvis339 commented
Test case added for debugging purposes, I will delete it later.

2024-11-28 16:35 UTC, mattsse requested changes
nice, I like this a lot.

testing this one specific code path is a bit challenging, I'll also try this out.

featurewise, I consider this PR completed once it compiles, because the next part is now just debugging work.

2024-11-28 16:35 UTC, mattsse commented on crates/net/network/src/test_only.rs
> +    async fn test_playground() {
I'd actually like to keep this but ignore before we merge, I have a feeling this will be useful again

2024-11-28 16:35 UTC, mattsse commented on crates/net/network/src/test_only.rs
can we move this to the tests/it/ folder or does this require private API access?

2024-11-28 17:13 UTC, Elvis339 commented on crates/net/network/src/test_only.rs
Sure! Moved, thank you for the help & review. I'll try to have profiling data asap.

2024-11-28 18:05 UTC, mattsse commented on crates/net/network/tests/it/transaction_hash_fetching.rs
> +mod tests {
this isn't needed because we're already in the tests scope

2024-12-04 10:26 UTC, Elvis339 commented
Just bumping this up for visibility.

2024-12-06 09:31 UTC, mattsse commented
nope this is good, was just holding off in case we introduced some conflicts with some recent changes,

looks like we're good

2024-12-06 09:58 UTC, mattsse approved these changes

2024-12-06 10:27 UTC, merged