feat(storage): accept any RangeBounds to walk_range
paradigmxyz/reth pull request #1309
Opened 2023-02-13 07:39 UTC by shekhirin

2023-02-13 08:16 UTC, rkrasiuk requested changes
this is great! let's change the usage of walk_range in a couple of places as well
- https://github.com/paradigmxyz/reth/blob/73ffc425a36714969c7d7b03eb4b63c022efe150/crates/stages/src/stages/sender_recovery.rs#L78
- https://github.com/paradigmxyz/reth/blob/73ffc425a36714969c7d7b03eb4b63c022efe150/crates/stages/src/stages/execution.rs#L95
-

2023-02-13 08:16 UTC, rkrasiuk commented on crates/storage/db/src/abstraction/cursor.rs
>      fn walk_range<'cursor>(
fix the docs for this method

2023-02-13 21:26 UTC, gakonst commented
lgtm - supportive of roman's comments

2023-02-14 00:39 UTC, shekhirin commented on crates/storage/db/src/abstraction/cursor.rs
>      fn walk_range<'cursor>(
fixed

2023-02-14 01:31 UTC, gakonst approved these changes

2023-02-14 01:31 UTC, merged

2023-02-14 01:32 UTC, gakonst commented
ayy welcome @shekhirin good to have you back