refactor: use constructor functions
paradigmxyz/reth pull request #13255
Opened 2024-12-10 01:00 UTC by faheelsattar

Closes #13247

2024-12-10 09:32 UTC, mattsse requested changes
ty,

I'd like to limit these to one specific change at a time

2024-12-10 09:32 UTC, mattsse commented on crates/engine/tree/src/tree/mod.rs
can we do this separately and only focus on the constructor calls?

2024-12-10 09:32 UTC, mattsse commented on crates/consensus/beacon/src/engine/mod.rs
same

2024-12-10 09:57 UTC, faheelsattar commented on crates/engine/tree/src/tree/mod.rs
Do you mean we keep the `BlockWithSenders` fields public for now and rather than accessing via getters via call the fields directly? And also just introduce a constructor for now?

2024-12-10 19:19 UTC, mattsse commented on crates/engine/tree/src/tree/mod.rs
yes, I want to do this incrementally and limit this pr to the constructor call

2024-12-10 20:01 UTC, faheelsattar commented on crates/engine/tree/src/tree/mod.rs
adjusted

2024-12-11 08:03 UTC, mattsse approved these changes
great! ty

next step is making the fields private and adding getters and functions that consume the individual fields so we can avoid clones

2024-12-11 09:51 UTC, merged