docs: inline mermaid diagrams meanwhile aquamarine is fixed
paradigmxyz/reth pull request #13302
Opened 2024-12-11 16:06 UTC by vcastellm

Re-exports doesn't work well with include_mmd! so we're embedding the diagrams in the code meanwhile.

Fixes https://github.com/paradigmxyz/reth/issues/4430

2024-12-11 17:07 UTC, mattsse requested changes
this seems fine, in case we need to update the mermaid file, the additional effort is negligible,

would like to keep the include_mmd macro as comments though

2024-12-11 17:07 UTC, mattsse commented on crates/transaction-pool/src/pool/txpool.rs
> -/// `include_mmd!("docs/mermaid/txpool.mmd`")
could we keep this as // doc below and add an additional note

2024-12-12 11:18 UTC, mattsse approved these changes

2024-12-12 11:19 UTC, mattsse commented
pending clippy

2024-12-12 12:00 UTC, vcastellm commented
Fixed clippy and squashed 😅 thx @mattsse

2024-12-12 12:57 UTC, mattsse approved these changes

2024-12-12 13:31 UTC, merged