feat(op-isthmus): `l1tol2-msg-passer` storage root validation
paradigmxyz/reth pull request #13311
Opened 2024-12-11 18:57 UTC by emhane

Branched out from https://github.com/paradigmxyz/reth/pull/13214

Implements block validation according to isthmus consensus rules

2024-12-13 10:29 UTC, mattsse requested changes

2024-12-13 15:47 UTC, emhane commented on crates/consensus/consensus/src/lib.rs
> +    Other,
I tried to remove the clone from the error type but it required too many changes and grew the scope of the pr significantly

2024-12-13 16:28 UTC, mattsse commented on crates/consensus/consensus/src/lib.rs
> +    Other,
I see, I believe this is due to some other error type Clone derives

we can keep this but perhaps add a string value?

2024-12-17 23:25 UTC, emhane commented on crates/consensus/consensus/src/lib.rs
> +    Other,
this failed for another reason I recall, think it was requirement to be `Send + Sync`, in that case wrapped in an `Arc`

2025-01-02 21:02 UTC, emhane commented
have re-written this to be called in execution. new code depends on https://github.com/paradigmxyz/reth/pull/13538.

2025-01-02 21:02 UTC, closed without merging