feat: SparseStateTrie's BlindedProviderFactory is boxed
paradigmxyz/reth pull request #13463
Opened 2024-12-20 01:19 UTC by nadtech-hub

This should close [13307](https://github.com/paradigmxyz/reth/issues/13307)

2024-12-20 08:05 UTC, shekhirin requested changes
Clarified the original issue name, my bad.

What we want to do is to remove `Box`es in `StateRootTask` that were introduced in https://github.com/paradigmxyz/reth/pull/13294. The generici in `SparseStateTrie` can also be removed, but it's less invasive than in the task, so can be done later.

2024-12-20 17:40 UTC, nadtech-hub commented
what should I replace removed generics with? There should be specific type in place

2024-12-26 17:58 UTC, nadtech-hub commented
@shekhirin I guess I got ur point. I will push changes in a while

2025-01-18 08:38 UTC, nadtech-hub commented
@shekhirin is the issue resolved with my latest changes?

2025-01-28 12:38 UTC, shekhirin commented
This was solved by https://github.com/paradigmxyz/reth/pull/13898

2025-01-28 12:38 UTC, closed without merging