Add drop aware sender new type (fixes #13242)
paradigmxyz/reth pull request #13495
Opened 2024-12-22 16:58 UTC by ABD-AZE

Fixes #13242

2024-12-23 06:13 UTC, mattsse requested changes
cool, this is great.

only have a smol nit

2024-12-23 06:13 UTC, mattsse commented on crates/rpc/rpc-eth-types/src/cache/mod.rs
> +                                    ActionSender { blockhash: block_hash, tx: Some(action_tx) };
I'd like a `fn new` for this

2024-12-23 06:13 UTC, mattsse commented on crates/rpc/rpc-eth-types/src/cache/mod.rs
> +pub struct ActionSender<B: Block, R: Send + Sync> {
we can keep this private

```suggestion
struct ActionSender<B: Block, R: Send + Sync> {
```

2024-12-23 07:56 UTC, mattsse approved these changes

2024-12-23 08:15 UTC, ABD-AZE commented
@mattsse should I label the **fn new** as const as directed by lint?

2024-12-23 08:15 UTC, mattsse commented
yep,
and `cargo +nightly fmt`

2024-12-24 06:46 UTC, ABD-AZE commented
@mattsse can you please enable the workflow for this PR.

2024-12-24 09:51 UTC, mattsse approved these changes

2024-12-24 10:33 UTC, merged