refactor(debug): simplify trie updates comparison logic
paradigmxyz/reth pull request #13516
Opened 2024-12-23 09:39 UTC by bendanzhentan

- Removing redundant match patterns and nested code blocks
- Improving warning messages to show the number of mismatched entries

2024-12-23 15:22 UTC, mattsse reviewed
not very familiar with this, but looks easier ptal @rkrasiuk

2025-01-02 12:29 UTC, bendanzhentan commented
@rkrasiuk ping

2025-01-02 12:37 UTC, rkrasiuk requested changes

2025-01-02 12:37 UTC, rkrasiuk commented on bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
> +        for (in_mem, incr) in in_mem_updates_iter.zip(incremental_updates_iter) {
if length of updates is not the same, some updates will be lost whereas previously we at least produced a warning if any items are left after iteration

2025-01-02 12:37 UTC, rkrasiuk commented on bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
> +        if !in_mem_mismatched.is_empty() {
this is incorrect because you are checking the lengths of mismatched entries whereas previously we checked whether any updates have more items

2025-01-02 12:37 UTC, rkrasiuk commented on bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
> +        }
this path is unreachable, because if `in_mem_mismatched` is empty, `incremental_mismatched` will be empty as well

2025-01-07 11:33 UTC, bendanzhentan commented on bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
> +        for (in_mem, incr) in in_mem_updates_iter.zip(incremental_updates_iter) {
Thanks @rkrasiuk and sorry for the late reply.
You are correct. This change will emit some updates when the length is not the same.
I will close this PR.

2025-01-07 11:34 UTC, closed without merging