chore(sync): Delay shrinking db abstraction to `revm::Database` in execution
paradigmxyz/reth pull request #13538
Opened 2024-12-24 04:00 UTC by emhane

Closes https://github.com/paradigmxyz/reth/issues/13537

`revm::Database` is a subset of the `StateProvider` behaviour (`EvmStateProvider`). The database passed to execution in reth, implements `StateProvider`, so this PR simply delays the step where the db is limited to the `revm::Database` subset of behaviour. This way we can now compute the state root (and storage root (OP)) in execution directly, which means we can verify the corresponding values in the block header against the correct state also in batch execution.

2024-12-24 09:59 UTC, mattsse requested changes
I think this is a pretty good change, offloading all the `revm::Db` stuff to the actual executor and instead provide the `State`, the `fn get_state(State<)` getters a re bit horrible but we had to add those, but I assume we could simplify these a bit later.

very supportive here

2024-12-24 09:59 UTC, mattsse commented on crates/evm/src/execute.rs
> +        F: FnMut(&State<StateProviderDatabase<DB>>);
what I wanted to do for this for a while now is introduce a trait for `State`, which would make this a lot more ergonomic. so for now I'm fine with that

2024-12-24 09:59 UTC, mattsse commented on crates/revm/src/cached.rs
> +impl<DB: AccountReader> AccountReader for CachedReadsDbMut<'_, DB> {
~~do we need these?~~

ah we need these to satisfy the stateprovider trait?

but why do we need this traits now?

2024-12-24 09:59 UTC, mattsse commented on crates/rpc/rpc/src/debug.rs
> +        // Note: we assume the block has a valid height
I believe this is a merge artifact?

2025-01-02 17:08 UTC, emhane commented on crates/revm/src/cached.rs
> +impl<DB: AccountReader> AccountReader for CachedReadsDbMut<'_, DB> {
yepp exactly, `StateProvider` super traits. in rpc `execute` is called on `CachedReadsDbMut`.

2025-01-07 17:02 UTC, mattsse requested changes
supportive, only the manual impls for cachedreads are a bit odd, and I think we can avoid this if we enforce that either the DB itself supports those traits or is AsRef trait, I assume this could work

2025-01-07 17:02 UTC, mattsse commented on crates/revm/src/cached.rs
> +impl<DB: AccountReader> AccountReader for CachedReadsDbMut<'_, DB> {
this seems a bit weird that we have to do this, but I know why,

but if I look at how we're using this,

https://github.com/paradigmxyz/reth/blob/9127d0e0ff0f8de7b52867297808fe5035c76d10/crates/optimism/payload/src/builder.rs#L156-L156

https://github.com/paradigmxyz/reth/blob/9127d0e0ff0f8de7b52867297808fe5035c76d10/crates/optimism/payload/src/builder.rs#L352-L353

could we simplify this by delegating to the wrapped `DB` if that is `AsRef<trait>`?

2025-01-07 21:33 UTC, emhane commented
> could we simplify this by delegating to the wrapped DB if that is AsRef<trait>?
I'm really reluctant to do that, it means nothing is cached then. which could seriously downgrade performance

2025-01-08 17:27 UTC, mattsse commented
@emhane this will likely drift a lot, because we're revamping this

because this has been delay beyond isthmus I think we can close for now

2025-01-08 17:27 UTC, closed without merging