fix: tag debug client
paradigmxyz/reth pull request #13542
Opened 2024-12-24 13:17 UTC by greged93

Fixes the tag for the debug client, as the [`Display` implementation](https://github.com/alloy-rs/alloy/blob/b6e2795b43f78a8c4039aabf0e7d157d5a52febf/crates/eips/src/eip1898.rs#L219) for `BlockNumberOrTag` will add `number` at the beginning of the string for the `Number` variant.

2024-12-24 13:28 UTC, mattsse commented
> Fixes the tag for the debug client, as the [Display implementation](https://github.com/alloy-rs/alloy/blob/b6e2795b43f78a8c4039aabf0e7d157d5a52febf/crates/eips/src/eip1898.rs#L219) for BlockNumberOrTag

meh this is a bit weird

2024-12-24 13:29 UTC, mattsse requested changes
smol nit

2024-12-24 13:29 UTC, mattsse commented on crates/consensus/debug-client/src/providers/etherscan.rs
> +            BlockNumberOrTag::Number(x) => format!("{x:x}"),
```suggestion
            BlockNumberOrTag::Number(num) => format!("{num}"),
```

2024-12-24 13:34 UTC, greged93 commented
actually I think the block number [needs to be in hex](https://docs.etherscan.io/api-endpoints/geth-parity-proxy#eth_getblockbynumber) @mattsse

2024-12-24 14:00 UTC, mattsse commented
I see, then let's format this as hex then

2024-12-24 14:05 UTC, greged93 commented on crates/consensus/debug-client/src/providers/etherscan.rs
> +            BlockNumberOrTag::Number(num) => format!("{num}"),
```suggestion
            BlockNumberOrTag::Number(num) => format!("{num:x}"),
```

2024-12-25 08:21 UTC, mattsse approved these changes

2024-12-25 08:57 UTC, merged