chore: correct typo docs
paradigmxyz/reth pull request #13557
Opened 2024-12-25 17:48 UTC by sky-coderay

**Description**  

- Corrected `RCP ` to `RPC `
- Corrected `mesesages ` to `messages ` 
- Corrected `DAO_HARDKFORK_ACCOUNTS` to `DAO_HARDFORK_ACCOUNTS` 

I fixed the typos in the comments and also one in the function. I tried really hard—happy to help, thank you!

2024-12-27 19:07 UTC, Rjected requested changes
normally we would not accept purely typo fix PRs, but changing the name of this constant seems like an improvement and I can't stop seeing the typo now. We do need all usages of the constant changed, should also make sure it builds locally

2024-12-28 17:02 UTC, mattsse approved these changes

2024-12-28 17:03 UTC, mattsse commented
needs `cargo +nightly fmt`

please don't open prs from main branch :)

2024-12-30 17:25 UTC, Rjected approved these changes
this looks good to me now - no rebase is needed now, but future PRs should be opened from a branch of your personal fork. This is so that we can make touchups if needed :)

2024-12-30 17:42 UTC, merged