feat: add cli `download` to download public node snapshots
paradigmxyz/reth pull request #13598
Opened 2024-12-30 18:05 UTC by lean-apple

Closes https://github.com/paradigmxyz/reth/issues/13469.

2025-01-06 11:00 UTC, gakonst reviewed
Let's also maybe add a list of pre-set snapshot URLs so that the user doesn't need to find the URL themselves? And we can default to one of them, while the `--help` menu shows alternatives/fallbacks?

2025-01-06 11:22 UTC, lean-apple commented
> Let's also maybe add a list of pre-set snapshot URLs so that the user doesn't need to find the URL themselves? And we can default to one of them, while the `--help` menu shows alternatives/fallbacks?

Thanks for your comment, I didn't find a common dynamic pattern with to retrieve the right URL pattern from the given URLS, for example for `https://snapshots.publicnode.com/ethereum-reth-{height}.tar.lz4`, where can I get the height information of the file ? I assume often changes.

or do you mean at least suggest the websites' URLs where the user can pick itself ?

2025-01-06 16:41 UTC, lean-apple commented
> Let's also maybe add a list of pre-set snapshot URLs so that the user doesn't need to find the URL themselves? And we can default to one of them, while the `--help` menu shows alternatives/fallbacks?

What would you advise me to be able to fetch the same block height they are using in their url ?  @matias-gonz @joshieDo 
For example, in this url  `https://snapshots.publicnode.com/ethereum-holesky-reth-3087369.tar.lz4`, we see it's`3087369`, 
but if I use  `let latest_block = provider.get_block_number().await?;`  I got `3090694`.

My aim is to build a default "dynamic" url with the corresponding block height with this pattern : 
`https://snapshots.publicnode.com/ethereum-{potential network}-reth-{block height}.tar.lz4`.

2025-01-07 13:32 UTC, joshieDo submitted a review, later dismissed
Snapshots can be quite big (>2TB with an archival node).

The current PR would mean that we'd need double that space, since we're downloading everything first and then decompressing. Ideally we'd pipe what we download straight into the decompressing stage.

Basically replicating the following behaviour:
`wget -O - https://downloads.merkle.io/reth-2025-01-06.tar.lz4 | tar -I lz4 -xvf -`

2025-01-09 14:34 UTC, lean-apple commented
> Snapshots can be quite big (>2TB with an archival node).
> 
> The current PR would mean that we'd need double that space, since we're downloading everything first and then decompressing. Ideally we'd pipe what we download straight into the decompressing stage.
> 
> Basically replicating the following behaviour: `wget -O - https://downloads.merkle.io/reth-2025-01-06.tar.lz4 | tar -I lz4 -xvf -`

Thanks, I've added this option `--decompress` that indeed makes the downloading inefficient.

2025-02-08 18:21 UTC, emhane commented
@lean-apple any issues here?

2025-02-12 10:31 UTC, lean-apple commented on crates/cli/commands/src/download.rs
> +}
I wanted to avoid adding new crates, and I wasn't aware I could use `reth_nippy_jar::lz4`.

2025-02-13 18:20 UTC, lean-apple commented
> @lean-apple any issues here?

Yes, I'm a bit blocked, I tried integrating `reth_nippy_jar::lz4::decompress_to/decompress` instead of using one this `spawn_lz4_process` I added, but not sure if you mean in fact using [lz4](https://crates.io/crates/lz4) and [tar](https://crates.io/crates/tar) @joshieDo and not some `reth` crates ?

2025-02-13 18:21 UTC, lean-apple commented on crates/cli/commands/src/download.rs
> +}
or do you mean using https://crates.io/crates/tar and https://crates.io/crates/lz4 ?

2025-02-28 11:01 UTC, lean-apple commented
> Sorry, I missed the notification.
> 
> > but not sure if you mean in fact using [lz4](https://crates.io/crates/lz4) and [tar](https://crates.io/crates/tar) @joshieDo and not some of the reth crates ?
> 
> Yeah, i think it's totally fine to just use `lz4` and `tar`

In fact, I found it less practial when refactoring to use them to have an efficient memory management but I will give another try.

2025-03-04 19:29 UTC, jenpaff commented
hey @lean-apple ! how is it going ? whats the status on the PR? Do you need any support?

2025-03-05 06:45 UTC, lean-apple commented
> hey @lean-apple ! how is it going ? whats the status on the PR? Do you need any support?

Hey @jenpaff, I'm waiting for a new review since I refactored the code to use `tar` and `lz4` crates directly.

2025-04-26 07:50 UTC, mattsse requested changes
okay, sorry for letting this become stale.

this is actually a very nice thing to add and as you already demonstrated isnt too complex.

so let's try to get this in.

I think we can fully use async for, because iirc the async reqwest client is more performant overall.

2025-04-26 07:50 UTC, mattsse commented on crates/cli/commands/src/download.rs
> +}
I think we're okay with just rolling an async variant of this.

there is 
https://github.com/astral-sh/tokio-tar/
which provides an Archive that can use  AsyncRead as input

2025-04-26 07:50 UTC, mattsse commented on crates/cli/commands/src/download.rs
> +    fs,
we can use reth_fs_utils here as fs which provides more useful errors

2025-05-02 11:59 UTC, lean-apple commented on deny.toml
> +    "CDLA-Permissive-2.0",
Was done because of this https://github.com/rustls/webpki-roots/commit/90c48f38672f4300eea5f1b712d4ccca8ad82123

2025-05-07 09:16 UTC, mattsse approved these changes
gg, ty and sorry for the delay.

2025-05-07 09:42 UTC, merged