Add Error extension trait used by RPC for Result<Option<Block>>
paradigmxyz/reth pull request #1381
Opened 2023-02-15 17:27 UTC by literallymarvellous

Resolves: #1374 

Draft

2023-02-15 17:29 UTC, literallymarvellous commented
@mattsse does this work?

2023-02-15 17:32 UTC, mattsse requested changes

2023-02-15 17:32 UTC, mattsse commented on crates/rpc/rpc/src/result.rs
> +    type Error;
we don't want this here.

this trait should be implemented manually for specific error types.

2023-02-15 17:32 UTC, mattsse commented on crates/rpc/rpc/src/result.rs
> +    fn output_or_rpc_err(self, err: Err) -> RpcResult<Self::Output> {
this should not take err.

2023-02-16 01:23 UTC, gakonst commented
@mattsse should we just make ToRpcResult do this always? doing `.to_rpc_result()?. output_or_rpc_err()?` doesnt look good. i could see calling it like `res()` or something instead, but would pref something less verbose

2023-02-16 01:39 UTC, mattsse commented
> @mattsse should we just make ToRpcResult do this always? doing .to_rpc_result()?. output_or_rpc_err()?

if we want to go from something like `Result<Option<T>>` to `RpcResult<T>` then we need a helper, that's what `Result<Option<T>>::output_or_rpc_err` would be for. and it's just `output_or_rpc_err` which is intended to be a `map+transpose` but in one step.

we could however replace `.to_rpc_result()` with a From impl

2023-02-16 02:18 UTC, gakonst commented
I guess it's fine, mostly nitpicking. Merging then.

2023-02-16 10:50 UTC, mattsse approved these changes
awesome, 

I#ve renamed the function to make it clearer what this actually does.

2023-02-16 16:51 UTC, merged