chore: phase out ethers rpc block types
paradigmxyz/reth pull request #1463
Opened 2023-02-20 14:09 UTC by mattsse

closes https://github.com/paradigmxyz/reth/issues/1439
supersedes https://github.com/paradigmxyz/reth/pull/1441

replace 
* `ethers::rpc::BlockId` with `reth::BlockId`
* `ethers::rpc::BlockNumber` with `reth::BlockNumberOrTag`

2023-02-20 14:29 UTC, rkrasiuk requested changes

2023-02-20 14:29 UTC, rkrasiuk commented on crates/rpc/rpc-api/src/eth.rs
> +    #[method(name = "eth_BlockNumberOrTag")]
replace all went a bit too far 😄. this shouldn't change

2023-02-20 14:29 UTC, rkrasiuk commented on crates/rpc/rpc-api/src/eth.rs
> +    #[method(name = "eth_getUncleCountByBlockNumberOrTag")]
same here

2023-02-20 14:29 UTC, rkrasiuk commented on crates/rpc/rpc-api/src/eth.rs
> +    #[method(name = "eth_getUncleByBlockNumberOrTagAndIndex")]
and here

2023-02-20 14:29 UTC, rkrasiuk commented on crates/rpc/rpc-api/src/eth.rs
> +    #[method(name = "eth_getTransactionByBlockNumberOrTagAndIndex")]
and here

2023-02-20 14:33 UTC, rkrasiuk approved these changes

2023-02-20 15:02 UTC, merged

2023-02-21 02:59 UTC, gakonst reviewed
amazing