Support soft limit in NewPooledTransactions
paradigmxyz/reth pull request #1577
Opened 2023-02-28 02:27 UTC by Tirthnp

Fixes #1484

2023-02-28 02:28 UTC, Tirthnp commented
Not sure if this is right, please let me know :)

2023-02-28 16:46 UTC, mattsse requested changes

2023-02-28 16:46 UTC, mattsse commented on crates/net/network/src/transactions.rs
> +        let soft_limit = 4096;
pleas make this another constant, see top of file.

2023-02-28 16:46 UTC, mattsse commented on crates/net/network/src/transactions.rs
> +                if msg.0.len() <= soft_limit {
this check should happen where `.push` is called,
see `todo!` in file.

2023-03-03 08:35 UTC, mattsse approved these changes
lgtm,

please enable edits by maintainer for next contribution

2023-03-03 08:36 UTC, merged