Add p2p listener port options for reth node
paradigmxyz/reth pull request #1753
Opened 2023-03-14 13:22 UTC by i-m-aditya

Fixes #1707

2023-03-14 14:40 UTC, mattsse requested changes
ty,
please add docs, which also serve as cli help

2023-03-14 14:40 UTC, mattsse commented on bin/reth/src/args/network_args.rs
> +    pub listener_address: Option<Ipv4Addr>,
sceptical that this option does make sense.
geth also doesn't seem to have this.

2023-03-14 14:40 UTC, mattsse commented on bin/reth/src/args/network_args.rs
> +    pub listener_port: Option<u16>,
looks like geth calls this

```

    --discovery.port value         (default: 30303)
          Use a custom UDP port for P2P discovery

```

let's stick with geth naming conventions for all of these.

2023-03-15 01:16 UTC, gakonst approved these changes

2023-03-15 01:18 UTC, gakonst approved these changes

2023-03-15 01:19 UTC, merged