feat(BlockchainTree): ShareableBlockchainTree and pending state
paradigmxyz/reth pull request #2007
Opened 2023-03-28 11:05 UTC by rakita

Create shareable blockchain tree that holds Tree behind RwLock.

Introduce traits
* `BlockchainTreeEngine` for write operations used by engine
* `BlockchainTreeViewer` for read operations and getting info data
* `BlockchainTreePendingStateProvider` for creating pending state data needed to execute on

Removes dependency from the engine on the provider and executor.

Refactor the Tree so the pending state data can be extracted and used with the state provider factroy.

2023-03-28 12:59 UTC, mattsse requested changes
I think I can follow and this makes sense to me.

So we have the `ShareableBlockchainTree` which clones the `PostSate` which is then used to create a `StateProvider` (the pending state), via the `canonical fork` block.

I believe we should rethink the `ShareableDatabase` type and merge with `BlockchainTreePendingStateProvider` so that we don't need two different types to construct the pending state and can directly call:

`StateProvider::pending(&self)`

this would make it so much easier in rpc

2023-03-28 18:23 UTC, rakita commented on crates/storage/provider/src/traits/state.rs
> -
Yeah, I overcomplicated it initially with associated types, the idea was to have clear types but usage got complex.

2023-03-28 19:28 UTC, mattsse commented on crates/storage/provider/src/traits/state.rs
> +    fn latest<'a>(&'a self) -> Result<Box<dyn StateProvider + 'a>>;
same thing, just less verbose.
using box dyn here is perfectly fine though

2023-03-29 11:07 UTC, rakita commented on crates/storage/provider/src/traits/state.rs
> +pub trait PostStateDataProvider: Send + Sync {
copilot is amazing help for writing docs.

2023-03-29 11:27 UTC, mattsse approved these changes
🔥
lgtm

2023-03-29 12:01 UTC, mattsse approved these changes

2023-03-29 18:59 UTC, merged