Network integrations tests with txpool task
paradigmxyz/reth pull request #2148
Opened 2023-04-07 07:07 UTC by i-m-aditya

Fixes #2014

2023-04-07 07:08 UTC, i-m-aditya commented
@mattsse Will add more tests, just want to make sure its in the right direction.

2023-04-07 07:51 UTC, mattsse requested changes
nice tests.

all the fields and private functions should remain private.
the `tests/integrationtests` should only ever use public interfaces, perhaps some things need to be exposed but it test should not invoke private functions directly.
if we need to test these then we can add the test inside the module see, txpool.rs

2023-04-07 07:51 UTC, mattsse commented on crates/net/network/src/transactions.rs
> +    pub pool: Pool,
all of these should remain private

2023-04-07 07:51 UTC, mattsse commented on crates/net/network/tests/it/transaction.rs
> +    );
there's a trait function that returns the tx by hash.

2023-04-09 10:49 UTC, mattsse approved these changes
nice, tests looking good,

made a smol change in the network config so port can be configured and discovery is always disabled.

2023-04-09 11:31 UTC, merged