feat: add best_block_number call to BlockIdProvider
paradigmxyz/reth pull request #2358
Opened 2023-04-23 12:31 UTC by chirag-bgh

Closes #2351

2023-04-24 02:50 UTC, gakonst commented
How does this optimize reads? Isn't it the same as before but behind a helper function?

2023-04-24 09:36 UTC, rkrasiuk commented
@gakonst `chain_info` performs one additional lookup for block hash
https://github.com/paradigmxyz/reth/blob/2a8c8d095b7b3e69cba2272b004f486832730ba0/crates/storage/provider/src/providers/mod.rs#L120

2023-04-24 09:42 UTC, rkrasiuk requested changes
pls, review the usages of `chain_info`. there are a couple more places where it can be swapped for `best_block_number`

2023-04-24 09:42 UTC, rkrasiuk commented on crates/storage/provider/src/providers/mod.rs
> +    fn best_block_number(&self) -> Result<BlockNumber> {
call this function in `chain_info` above

2023-04-25 08:47 UTC, mattsse approved these changes
ty,

lgtm

2023-04-25 19:23 UTC, gakonst approved these changes

2023-04-25 20:30 UTC, merged