feat: write account and storage hashes in genesis
paradigmxyz/reth pull request #2441
Opened 2023-04-28 01:17 UTC by Rjected

This is a starting point for inserting hashed accounts / storage when inserting the genesis block. In hive we discovered that building an empty payload on top of genesis without running stages would result in an empty root, so we need to populate the correct tables in order to calculate the root.

2023-04-28 21:24 UTC, gakonst approved these changes
fine w me - @rkrasiuk ptal

2023-05-01 14:39 UTC, onbjerg approved these changes

2023-05-01 14:39 UTC, rkrasiuk requested changes

2023-05-01 14:39 UTC, rkrasiuk commented on bin/reth/src/drop_stage.rs
> +                insert_genesis_state::<Env<WriteMap>>(&tx, self.chain.genesis())?;
that's not right, we have to commit this

2023-05-01 14:39 UTC, rkrasiuk commented on crates/staged-sync/src/utils/init.rs
> +    let tx = db.tx_mut()?;
this should fail to acquire the write transaction because it's already owned by `Transaction`

2023-05-01 15:42 UTC, Rjected commented on bin/reth/src/drop_stage.rs
> +                insert_genesis_state::<Env<WriteMap>>(&tx, self.chain.genesis())?;
tbh not sure why I moved it out of the closure, just added it back which should commit

2023-05-01 19:06 UTC, gakonst approved these changes

2023-05-01 19:06 UTC, merged