fix fork_id function which will run into issues in the near future.
paradigmxyz/reth pull request #2503
Opened 2023-05-01 14:30 UTC by TovarishFin

The current implementation does not take into account that timestamp forks should ALWAYS be applied after block number forks. This fixes that.

reference: https://eips.ethereum.org/EIPS/eip-6122

2023-05-01 14:33 UTC, onbjerg requested changes
Please add a test demonstrating that this is not the case currently and that this fixes it.

2023-05-01 14:33 UTC, onbjerg commented on crates/primitives/src/chain/spec.rs
> +                    println!("block: {} forkhash: {:#?}", block, forkhash);
```suggestion

```

2023-05-01 14:33 UTC, onbjerg commented on crates/primitives/src/chain/spec.rs
> +                    println!("block: {} forkhash: {:#?}", timestamp, forkhash);
```suggestion

```

2023-06-05 12:37 UTC, mattsse reviewed
this looks right to me,

pending @Rjected

2023-06-19 10:59 UTC, onbjerg commented
Ping @Rjected, wdyt?

2023-06-29 22:02 UTC, Rjected approved these changes
Now this is good and passes tests, it originally missed the sepolia netsplit block edge case

2023-06-29 22:10 UTC, mattsse approved these changes
cool!
glad we can get this included

2023-06-29 22:15 UTC, onbjerg approved these changes

2023-06-29 22:59 UTC, gakonst commented
Did we try this live? Want to be very sensitive to anything that touches this logic given it's in live p2p mode.

2023-06-30 02:30 UTC, Rjected commented
> Did we try this live? Want to be very sensitive to anything that touches this logic given it's in live p2p mode.

Just tested this with sepolia, without any issues

2023-06-30 07:43 UTC, merged