chore: Additional logs on revert error
paradigmxyz/reth pull request #2623
Opened 2023-05-10 12:18 UTC by rakita

Added more logs to hunt for the revert bug that we have.

It will log all new canonical block number and hashes.
It will log revert range
In case of error on reverting canonical chain it will print all block tree indices and all new block tree indices, which should help to see the state before and after the `make_canonical`.

2023-05-10 12:32 UTC, rkrasiuk requested changes

2023-05-10 12:32 UTC, rkrasiuk commented on crates/blockchain-tree/src/blockchain_tree.rs
> +            "Committing new canonical chain: {:?}",
pls add target here

2023-05-10 18:09 UTC, rakita commented on crates/blockchain-tree/src/blockchain_tree.rs
> +            info!(target: "blockchain_tree", "Block hash not found in block indices");
Same here, I increased log level for debugging, we should lower the log level after we found the bug.

2023-05-12 16:19 UTC, rkrasiuk approved these changes

2023-05-12 16:20 UTC, merged