feat: reth-config crate
paradigmxyz/reth pull request #2825
Opened 2023-05-24 21:21 UTC by bowenyou

Closes https://github.com/paradigmxyz/reth/issues/2809.

2023-05-25 16:58 UTC, onbjerg requested changes

2023-05-25 16:58 UTC, onbjerg commented on crates/staged-sync/src/config.rs
Everything in this file should be removed, it should be removed from `reth-staged-sync` in its entirety

2023-05-25 18:49 UTC, bowenyou commented on crates/staged-sync/src/config.rs
okay, moved all of it over to `reth-config` now

2023-05-26 03:00 UTC, onbjerg approved these changes
lgtm, @mattsse does this resolve your original issue? i guess other config changes are separate prs?

2023-05-26 08:44 UTC, mattsse approved these changes
lgtm

> i guess other config changes are separate prs?

yes, I believe so

2023-05-26 14:29 UTC, merged