ci: add dummy jobs to required workflows
paradigmxyz/reth pull request #2905
Opened 2023-05-30 04:24 UTC by TechieBoy

Closes #2890

2023-05-30 09:03 UTC, onbjerg requested changes

2023-05-30 09:03 UTC, onbjerg commented on .github/workflows/ci.yml
> +    needs: [code-lint, doc-lint]
I think this needs to be `[lint, doc-lint]`?

2023-05-30 11:47 UTC, onbjerg approved these changes
seeing if this will trigger ci :shrug:

2023-05-30 11:48 UTC, onbjerg requested changes
ah, each of the jobs also needs `runs-on: ubuntu-latest`, my bad

2023-05-31 07:08 UTC, TechieBoy commented
Looks like it worked. All the success ones were triggered in correct order

2023-05-31 08:19 UTC, onbjerg approved these changes

2023-05-31 08:52 UTC, merged