chore: percentage sync progress in Grafana dashboard
paradigmxyz/reth pull request #2936
Opened 2023-05-31 20:24 UTC by shekhirin

With the introduction of new percentage-based progress reporting, we can now better visualize stages like Headers or Hashing.

| Before                                                                                                                                           | After                                                                                                                                            |
|-------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="1800" alt="image" src="https://github.com/paradigmxyz/reth/assets/5773434/be583af3-dc5a-4e58-95c2-5f88c42b601b"> | <img width="1800" alt="image" src="https://github.com/paradigmxyz/reth/assets/5773434/dc9d87fb-530a-40a4-9ea2-583f8adb982f"> |

The rest of the dashboard below is the same.

2023-05-31 22:13 UTC, onbjerg requested changes
Can you rename the old sync progress table to checkpoints or something similar? Better captures the discrepancy between the two

2023-06-01 07:22 UTC, shekhirin commented
@onbjerg I think checkpoint may be misleading because for Headers it'll be at 0 for a long time, while % will grow. IMO `Highest block number reached` better reflects the difference, but the titles of these two charts are too long now.

2023-06-03 01:26 UTC, gakonst requested changes
this should be against feat/checkpoints right?

2023-06-03 01:26 UTC, gakonst approved these changes

2023-06-05 03:09 UTC, merged