feat(sync): headers commit threshold
paradigmxyz/reth pull request #296
Opened 2022-11-30 09:33 UTC by rkrasiuk

Modify the headers stage to download the block headers in batches. Add a `commit_threshold` parameter for aggregated commits

blocked by #310

2022-11-30 11:42 UTC, mattsse requested changes
the stream looks alright, 
since we need to day a lot of checks and conditionally return it makes sense to solve this with macros here

2022-12-02 12:53 UTC, gakonst requested changes
nice work. some nits, requests for more docs, and questions aroudn if we had bugs before

2022-12-02 14:26 UTC, mattsse requested changes

2022-12-06 06:28 UTC, gakonst approved these changes
lgtm - merging to get the ball rolling but pls address comments in followup

2022-12-06 06:28 UTC, merged