Display hardforks on startup
paradigmxyz/reth pull request #3011
Opened 2023-06-06 08:10 UTC by seroze

Addresses https://github.com/paradigmxyz/reth/issues/1343

2023-06-06 11:07 UTC, mattsse requested changes

2023-06-06 11:07 UTC, mattsse commented on bin/reth/src/cli.rs
> +    }
ptal at how to format/align 

https://doc.rust-lang.org/std/fmt/#formatting-parameters

2023-06-06 11:07 UTC, mattsse commented on bin/reth/src/cli.rs
> +    let hardfork = MAINNET.hardforks();
this is only true for MAINNET, we want this as function of `Chainspec`

2023-06-06 11:07 UTC, mattsse commented on crates/primitives/src/chain/spec.rs
> +        write!(f, "{self:?}")
This displays things like

```
TTD { fork_block: None, total_difficulty: 0x000000000000000000000000000000000000000000000c70d808a128d7380000_U256 }
```

which is not easy to read.

ptal at `geth`'s default output which we should use as a reference here

2023-06-06 11:07 UTC, mattsse commented on bin/reth/src/cli.rs
> +fn display_hardforks_on_startup() {
I'd rather have an intermediate representation something like:

```rust
struct DisplayFork {
  name: String,
  activated at: ForkCondition
  eip: Option<String>
}

struct HardforkList {
 pre_merge: Vec<DisplayFork>,
 with_merge: Vec<DisplayFork>,
 post_merge: Vec<DisplayFork>,
}
```

2023-06-19 10:56 UTC, onbjerg commented
Hi @seroze, this PR looked stale so I rebased it and addressed @mattsse's review comments. I hope you don't mind; I retained your original commits in the new PR, so you will be counted as a contributor because of the first stab you took.

I am closing this PR in favor of the new one at #3227 

Thanks for contributing ❇️

2023-06-19 10:56 UTC, closed without merging