feat(stages): log indexing
paradigmxyz/reth pull request #3082
Opened 2023-06-09 13:56 UTC by rkrasiuk

## Description

This PR introduces log address and topic indexing - supplementary indices for log querying (intended to be used by RPC module).

_Further description to be added_

2023-06-09 17:24 UTC, gakonst commented
1. Can we run this on an existing node to backfill via `reth stage run --commit`?
2. How big are the tables on mainnet at tip?

2023-06-12 11:34 UTC, rkrasiuk commented
@gakonst https://github.com/paradigmxyz/reth/pull/3089 solves this by starting the pipeline for any newly added stage

2023-06-13 08:41 UTC, shekhirin commented on crates/stages/src/stages/index_log_history.rs
> +        info!(target: "sync::stages::index_log_history", checkpoint = *range.end(), is_final_range, "Stage iteration finished");
I think this kind of logs is obsolete after https://github.com/paradigmxyz/reth/pull/3055

2023-06-13 08:41 UTC, shekhirin commented on crates/stages/src/stages/index_log_history.rs
> +        info!(target: "sync::stages::index_account_history", to_block = input.unwind_to, unwind_progress, is_final_range, "Unwind iteration finished");
same re logs deprecation

2023-06-13 08:45 UTC, shekhirin commented on crates/storage/db/src/tables/mod.rs
> +    /// Storages pointers to block numbers at which the particular address emitted the log.
nit: typo
```suggestion
    /// Stores pointers to block numbers at which the particular address emitted the log.
```

2023-06-13 08:54 UTC, shekhirin commented on crates/storage/provider/src/transaction.rs
> +    fn insert_history_index<P, T>(
love the generalized methods!

2023-06-16 15:24 UTC, shekhirin requested changes

2023-06-17 01:28 UTC, gakonst approved these changes
mainly nits which can go in a follow-up. 

mind sharing the mainnet db impact of this change?

also, if we merge this, people will resync this stage per your recent pipeline PR right?

in that case maybe we can merge it earlier so people get the indices earlier than later, and we can test https://github.com/paradigmxyz/reth/pull/3208/ as a fast followup? would like to have both ASAP ideally

2023-06-17 01:28 UTC, gakonst commented on crates/stages/src/stages/index_log_history.rs
> +        // TODO: stage checkpoint
still relevant for this / followup?

2023-06-17 01:28 UTC, gakonst commented on crates/stages/src/stages/index_log_history.rs
> +        provider.insert_log_topic_history_index(log_topic_indices)?;
good opportunity to define these as new provider traits IMO vs adding on the struct

2023-06-17 01:28 UTC, gakonst commented on crates/stages/src/stages/index_log_history.rs
> +
any checkpoint logic needed?

2023-06-17 01:28 UTC, gakonst commented on crates/stages/src/stages/index_log_history.rs
> +fn stage_checkpoint<DB: Database>(
do we want them completely disabled? i think that got me confused a little

2023-06-17 01:28 UTC, gakonst commented on crates/storage/provider/src/providers/database/provider.rs
> +    ) -> std::result::Result<(LogAddressIndices, LogTopicIndices, u64), TransactionError> {
let's make this part of a `trait LogIndexProvider`, so that we can make this easier for @joshieDo's broader Provider -> Trait refactor/cleanup.

2023-06-17 01:28 UTC, gakonst commented on crates/storage/provider/src/providers/database/provider.rs
> +            let partial_shard = unwind_history_shards::<_, tables::AccountHistory, _>(
v nice

2023-06-18 10:41 UTC, rkrasiuk commented on crates/stages/src/stages/index_log_history.rs
> +fn stage_checkpoint<DB: Database>(
@gakonst they are temporarily disabled until fixed

2023-06-18 10:51 UTC, rkrasiuk commented on crates/stages/src/stages/index_log_history.rs
> +
no additional logic is needed here

2023-06-18 11:23 UTC, shekhirin approved these changes

2023-06-19 11:10 UTC, onbjerg approved these changes
lgtm but also curious on mainnet impact here, any guesstimates or figures?

2023-06-19 11:10 UTC, onbjerg commented on crates/primitives/src/integer_list.rs
> +    // Creates an IntegerList from a list of integers. `usize` is safe to use since
```suggestion
    // Creates an IntegerList from a pre-sorted list of integers. `usize` is safe to use since
```

2023-06-19 13:28 UTC, mattsse reviewed
I can't say I fully understand the indexing and integer lists, but I was able to follow the impl and nothing stood out to me.

2023-06-29 20:13 UTC, onbjerg commented
@gakonst We need to figure out when to release this - there is another breaking DB change in #3464, so I wonder if we should bundle both in e.g. Alpha 3?

2023-07-12 01:15 UTC, gakonst commented on crates/rpc/rpc/src/eth/filter.rs
> +            log_index_filter.install_topic_filter(&self.provider, topics)?;
should some fo this stuff be moved to the provider? so that e.g. reth-indexer type code doesn't need to reimplement parts of it and can re-use it?

2023-08-08 01:51 UTC, closed without merging