fix: shrink queued bodies and headers when drained or split
paradigmxyz/reth pull request #3191
Opened 2023-06-15 18:33 UTC by Rjected

This fixes an OOM in the bodies stage and reduces overall memory allocations in the downloaders, by shrinking vectors whenever we `split` or `drain` them. Previously the headers downloader would effectively clone `queued_validated_headers` in terms of allocations, because `split_off` does not change the original vec's capacity. Because `queued_validated_headers` could be on the order of gigabytes, this caused on OOM.

Fixes #3175

2023-06-15 18:34 UTC, gakonst approved these changes
supportive - any way of testing this?

2023-06-15 18:43 UTC, mattsse requested changes
very nice find.

This also applies to the BianryHeaps which are just Vec wrappers, so we need to shrink them as well.

I think we can get away with having our own shrink_to fit, where we delegate the calls and only call this once when we return the next batch?

2023-06-15 18:43 UTC, mattsse commented on crates/net/downloaders/src/headers/reverse_headers.rs
> +                self.queued_validated_headers.shrink_to_fit();
I don't think this is necessary here, because this merely removes a few headers from the front, and we will go through `next_batch` eventually

2023-06-15 18:43 UTC, mattsse commented on crates/net/downloaders/src/headers/reverse_headers.rs
> +        rem.shrink_to_fit();
hmm, I think this is redundant because `split_off` only allocates required capacity

2023-06-15 18:48 UTC, Rjected commented
> supportive as discussed - any way of testing this?

Just added some checks in the existing tests that make sure `len == capacity` for downloaded values, when the stream batch size is lower than the number of values that should be produced.

also added another test for one-by-one download with a larger request limit, so `queued_validated_headers` is hopefully larger than the batch size in that test, which should trigger the necessary condition.

2023-06-15 19:35 UTC, rkrasiuk approved these changes
majestic!

2023-06-15 20:20 UTC, Rjected commented
@mattsse added calls to `shrink_to_fit` whenever buffered responses are popped in 781d786e8d2f2de9b9e97e0e3748482d1815ec1e

2023-06-15 20:35 UTC, mattsse requested changes
smol nits

just to be safe I'd also like to replace all `.clear()` calls in the `fn clear()` functions of bodies and headers downloader with new initializations because clear does not change capacity

2023-06-15 20:35 UTC, mattsse commented on crates/net/downloaders/src/headers/reverse_headers.rs
> +                    self.buffered_responses.shrink_to_fit();
having this inside a loop is not ideal,

I think we can move it below the loop, since the error case would retrigger a new download

2023-06-15 21:13 UTC, Rjected commented on crates/net/downloaders/src/bodies/bodies.rs
> +        self.buffered_responses.shrink_to_fit();
ah right, these should definitely be moved outside loops

2023-06-15 21:17 UTC, mattsse approved these changes
gg

2023-06-15 23:06 UTC, merged

2023-06-19 18:25 UTC, sigridjineth commented
thks for resolving this.