refactor: add total distance in log message
paradigmxyz/reth pull request #3292
Opened 2023-06-21 05:58 UTC by yuichiroaoki

resolve #3203

2023-06-21 12:51 UTC, mattsse requested changes
smol nit,

pending @shekhirin

2023-06-21 12:51 UTC, mattsse commented on crates/net/downloaders/src/bodies/bodies.rs
> +            info!(target: "downloaders::bodies", "Downloading bodies {range:?} (total distance: {total_distance})");
`distance` should be sufficient
```suggestion
            info!(target: "downloaders::bodies", "Downloading bodies {range:?} (distance: {total_distance})");
```

2023-06-21 12:51 UTC, mattsse commented on crates/net/downloaders/src/bodies/bodies.rs
> +        info!(target: "downloaders::bodies", "Downloading bodies {range:?} (total distance: {total_distance})");
```suggestion
        info!(target: "downloaders::bodies", "Downloading bodies {range:?} (distance: {total_distance})");
```

2023-06-21 13:17 UTC, shekhirin commented
@yuichiroaoki @mattsse how do you feel about including this as a logging field, and not part of the message?

2023-06-21 13:45 UTC, mattsse commented
like

```
info!(target: "downloaders::bodies", %distance, "Downloading bodies {range:?}");
```

?

yeah that's actually better

2023-06-22 02:11 UTC, mattsse approved these changes
ty

2023-06-22 03:28 UTC, merged