Create stream-mempool.rs
paradigmxyz/reth pull request #3489
Opened 2023-06-30 01:31 UTC by BrazilRaw

A minimal examples that  stream transaction events using the transactions_listener method of the Pool struct.

2023-06-30 01:38 UTC, onbjerg requested changes
@BrazilRaw It should be an example in the `examples` directory, see https://doc.rust-lang.org/cargo/guide/project-layout.html for project layouts. It should be runnable via `cargo run --example <name>`.

While this snippet is nice, it is not runnable (and it is in the tests directory)

2023-06-30 06:57 UTC, mattsse requested changes
this is great.

as @onbjerg mentioned, we want a standalone example for this, so we need:

1. open DB
2. configure pool


But I'd be also fine with moving this snippet as is to a docs example for transaction-pool crate

2023-07-02 11:54 UTC, gakonst commented
agreed let's move to examples dir as suggested in #3533

2023-07-05 12:25 UTC, mattsse commented
@BrazilRaw ty for this,

I converted your example into docs in #3596

2023-07-05 12:25 UTC, closed without merging