Adding outgoing metric to grafana dashboard
paradigmxyz/reth pull request #3802
Opened 2023-07-16 04:57 UTC by i-m-aditya

Fixes #3745 
<img width="1376" alt="Screenshot 2023-07-16 at 10 27 16 AM" src="https://github.com/paradigmxyz/reth/assets/24940106/900726ab-1aae-4331-8e51-89c78007bfec">

2023-07-16 10:43 UTC, mattsse approved these changes
lgtm, pending @Rjected

2023-07-16 19:58 UTC, Rjected requested changes
Just one nit, otherwise looks good

2023-07-16 19:58 UTC, Rjected commented on etc/grafana/dashboards/overview.json
> +          "expr": "reth_network_total_dial_successes",
```suggestion
          "expr": "reth_network_total_dial_successes{instance=~\"$instance\"}",
```

2023-07-16 19:59 UTC, Rjected commented on etc/grafana/dashboards/overview.json
> +    {
This should also probably be placed with the rest of the peer related metrics (for example after peer disconnect reasons)

2023-07-24 18:35 UTC, Rjected commented
ping @i-m-aditya :)

2023-07-25 06:37 UTC, i-m-aditya commented
@Rjected Apologies. I was occupied with office work last week. Will resolve comments today.

2023-07-25 11:35 UTC, mattsse approved these changes
ty!

pending @Rjected

2023-07-25 16:36 UTC, onbjerg approved these changes

2023-07-25 16:54 UTC, Rjected approved these changes
LGTM, thx!

2023-07-25 17:03 UTC, merged