feat(docs): add primer on all transaction types
paradigmxyz/reth pull request #3897
Opened 2023-07-24 21:17 UTC by tcoratger

Should solve #3803.

I added the description of the different types of transactions in two places:
- In the code for new contributors who would be lost.
- In the official documentation (book) for users with a little more text.

If it is not necessary, I can remove the description in the book, but I thought it could provide additional information.

2023-07-24 22:51 UTC, mattsse requested changes
awesome!

I will use this as the base and extend this with docs about reth's internal transaction types (txpool, primitives) and rpc types

2023-07-24 22:51 UTC, mattsse commented on book/run/transactions.md
> +## EIP-1559 Transactions
nit: we can reference this eip url here

2023-07-25 06:32 UTC, tcoratger commented on book/run/transactions.md
> +## EIP-1559 Transactions
@mattsse Done!

2023-07-25 10:21 UTC, mattsse approved these changes

2023-07-25 10:31 UTC, merged