clear merkle checkpoint on invalid root
paradigmxyz/reth pull request #3973
Opened 2023-07-27 17:32 UTC by joshieDo

While working on another branch, I noticed that the merkle stage once it fails its validation (related to my branch), it can't really recover since its checkpoint never gets cleared.

This is what happened **before** the logs from the image below.
1. Run first sync
2. Reach tip
3. Re-run the pipeline 
4. Fails MerkleStage and unwinds `AccountHashing` and `StorageHashing`.
5. MerkleUnwind fatal failure with process exit
6. Run again
7. `AccountHashing`
8. `StorageHashing` (you can see its end in the first line of the picture.
9. 
![image](https://github.com/paradigmxyz/reth/assets/93316087/5cadf2c2-0fe0-498e-958e-781c99380a4d)

Proposing that we clear `MerkleStage` checkpoints once we hit a validation error.

2023-07-27 18:02 UTC, rkrasiuk requested changes
nice catch! however, we should do this inside the merkle stage

2023-07-27 18:07 UTC, joshieDo commented
we cannot commit anything from inside a stage though, and I do like that constraint

furthermore, there's already a branch to handle the validation error, so as long as it doesn't grow with many edge cases I feel like it should be fine?

2023-07-27 18:37 UTC, rkrasiuk commented
ah, ye, makes sense

2023-07-27 18:37 UTC, rkrasiuk approved these changes

2023-07-31 12:51 UTC, onbjerg approved these changes
Would like to mark this as a `FIXME` since it's technically debt we should try to solve in a better way (this is "special treatment" for merkle)

2023-07-31 12:51 UTC, onbjerg commented on crates/stages/src/pipeline/mod.rs
> +                        // checkpoint, and restarting from an invalid place.
```suggestion
                        // FIXME: When handling errors, we do not commit the database transaction. This
                        // leads to the Merkle stage not clearing its
                        // checkpoint, and restarting from an invalid place.
```

2023-07-31 13:40 UTC, merged