feat(taskmanager) spawn tokio tasks with names
paradigmxyz/reth pull request #3995
Opened 2023-07-31 04:08 UTC by 0xprames

should close #3985 if we decide to take on the `tokio-unstable` dep

2023-07-31 04:15 UTC, 0xprames commented
```
GitHub
Actions
/ code lint
failed to resolve: could not find `Builder` in `task`
```

linter fails because im not sure it's loading the necessary `RUSTFLAGS` to support the `tokio::task::Builder` in the `tracing` feature crate

I added a `.cargo/config.toml` to this PR with the necessary rustc flags following: https://docs.rs/tokio/latest/tokio/index.html#unstable-features

but not sure how to get the PR linter to pick this up

2023-07-31 11:35 UTC, mattsse requested changes
afaik this has now perf implications 

wdyt @onbjerg

2023-07-31 12:38 UTC, onbjerg requested changes

2023-07-31 12:38 UTC, onbjerg commented on crates/tasks/src/lib.rs
> +    fn spawn_on_rt<F>(&self, fut: F, task_kind: TaskKind, name: &'static str) -> JoinHandle<()>
Please make this an `Option` instead to make the behavior of no name more explicit

2023-07-31 12:39 UTC, onbjerg commented
@mattsse it makes sense to name the threads so I think this is ok - however, I'd like for you to expand a bit on the perf implications, what are they?

2023-07-31 12:40 UTC, onbjerg commented
@0xprames it seems that `tokio::task::Builder` requires both `tokio_unstable` and `tracing` which is probably why lint fails? ref https://docs.rs/tokio/latest/tokio/task/struct.Builder.html

2023-07-31 12:59 UTC, 0xprames commented
ah ok if we turn on tracing via the feature crate/`tokio-unstable` flag then every task we spawn (even as is without the name, i.e for non-critical tasks) we will generate a trace for which will probably impact performance.

There's no way to only create traces for critical named tasks looks like

https://github.com/tokio-rs/tokio/blob/efe3ab679a05f3da3fcc511a44120239830254f2/tokio/src/runtime/blocking/pool.rs#L364

https://github.com/tokio-rs/tokio/blob/efe3ab679a05f3da3fcc511a44120239830254f2/tokio/src/runtime/handle.rs#L328

the futures are wrapped or instructed with a `Trace`

2023-07-31 13:29 UTC, 0xprames commented
following up re linter: this is the same `cargo clippy` command run locally
https://pastebin.com/S2AK53hk

few warnings, but completes without the compiler error seen in the linter. I think if we add this feature and unstable dep we need to modify the linter config - was what I was alluding to with my original comment above

2023-08-01 10:29 UTC, rkrasiuk commented
closing in favor of #4003

2023-08-01 10:29 UTC, closed without merging