feat: add p2p crate
paradigmxyz/reth pull request #4
Opened 2022-09-28 22:14 UTC by Rjected

adding `reth-p2p` based on the template for now, this should eventually provide nice interfaces for other components to interact with the network.

2022-09-28 22:30 UTC, mattsse reviewed
should we move this into a subfolder called `net`?
so `./net/p2p` or `./net/devp2p`?

I can imagine we'll need additional stuff related to p2p, or net in general

2022-09-29 11:30 UTC, onbjerg reviewed
nit: let's make a habit of writing docs "normal cased"(? is that even a term), so e.g. "networking utilities for reth" -> "Networking utilities for reth"

2022-09-29 12:52 UTC, mattsse requested changes

2022-09-30 16:27 UTC, gakonst approved these changes

2022-09-30 16:27 UTC, merged