feat(pruner): storage history
paradigmxyz/reth pull request #4006
Opened 2023-07-31 16:47 UTC by shekhirin

2023-08-01 17:26 UTC, joshieDo requested changes

2023-08-01 17:26 UTC, joshieDo commented on crates/prune/src/pruner.rs
> +                            if prev_key.sharded_key.key == key.sharded_key.key {
shouldn't we check `prev_key.address == key.address` as well?

2023-08-02 14:10 UTC, mattsse approved these changes
lgtm

2023-08-02 14:10 UTC, mattsse commented on crates/prune/src/pruner.rs
> +                // will not contain the target block number, as it's in this shard.
this is a very useful comment

2023-08-02 14:10 UTC, mattsse commented on crates/prune/src/pruner.rs
> +                    .collect::<Vec<_>>();
these are only numbers and not the actual blocks, so we can safely load them

2023-08-02 14:10 UTC, mattsse commented on crates/prune/src/pruner.rs
> +                            if prev_key.address == key.address &&
even if we have a bunch of levels, this is still readable imo

2023-08-02 15:05 UTC, joshieDo approved these changes

2023-08-02 15:16 UTC, merged