feat(storage): account for pruned account/storage history
paradigmxyz/reth pull request #4092
Opened 2023-08-07 11:07 UTC by shekhirin

2023-08-07 11:34 UTC, joshieDo commented
i don't quite like that i'm getting a provider for a block that i didn't request. I'd rather it fail, and handle the error somewhere else

2023-08-07 12:21 UTC, mattsse requested changes
agree with @joshieDo 

if the requested block's state is pruned this should just fail.

this looks way too complex

2023-08-07 13:42 UTC, shekhirin commented
@joshieDo @mattsse agree, made it return an error instead. But I'd still prefer to check account and storage history restrictions separately, as e.g. `eth_getStorageAt` doesn't require account history, and a user can have separate account/storage history pruning configurations.

2023-08-07 13:51 UTC, joshieDo commented on crates/storage/provider/src/providers/state/historical.rs
> +            lowest_storage_history_block_number: None,
just preference, but i like `oldest` more

2023-08-09 16:20 UTC, mattsse requested changes
we definitely need this.

left some suggestions, 
a helper wrapper type could be nice with functions to ensure target block number is present

2023-08-09 17:06 UTC, shekhirin commented on crates/storage/provider/src/providers/state/historical.rs
> +        block_number: BlockNumber,
agree, fixed

2023-08-09 17:06 UTC, shekhirin commented on crates/storage/provider/src/providers/state/historical.rs
> +    lowest_storage_history_block_number: Option<BlockNumber>,
added docs, helper struct and also tests

2023-08-09 18:08 UTC, mattsse approved these changes
lgtm

2023-08-09 18:11 UTC, joshieDo approved these changes

2023-08-09 18:24 UTC, merged