pass parent beacon block root to payload builder
paradigmxyz/reth pull request #4425
Opened 2023-08-31 10:17 UTC by alessandromazza98

Closes #4401 

This PR should close that issue. I'm actually not 100% sure that it is complete. Please let me know.

2023-08-31 23:19 UTC, Rjected requested changes
Important note on making sure we keep the root as `None` pre-cancun, otherwise this looks good

2023-08-31 23:19 UTC, Rjected commented on crates/payload/builder/src/payload.rs
> +    pub parent_beacon_block_root: H256,
This needs to be an `Option<H256>` so header conversions can preserve `None` pre-cancun

2023-09-03 16:38 UTC, mattsse approved these changes
lgtm, pending @Rjected

2023-09-04 14:05 UTC, Rjected approved these changes
LGTM, thanks!

2023-09-04 15:02 UTC, merged