refactor: split async/sync work in stages
paradigmxyz/reth pull request #4636
Opened 2023-09-18 13:35 UTC by onbjerg

This is essentially just #4215 but renamed to better reflect what the PR will now be about.

Previously, most of the work in #4215 was to try and remove the `Send + Sync` bounds for `DbTx` where possible to make it work with redb, however the transactions have since been made `Send + Sync` upstream so that is no longer needed.

Instead, this will continue work on splitting async and sync work in the stages into two parts, inspired by `tower`'s `Service` trait: async work will be done in `poll_ready`, which will tell the caller when the stage is ready to be executed, and sync work (incl. writing to the database) will be performed in `execute` as normal.

This will make it a lot clearer when things block and when they do not; most stages block in `execute` and do not really leverage async at all, some notable exceptions being the header and bodies stage.

## Assumptions

- It is assumed that unwinds will never need any async work done, so `poll_ready` is only required to be called before `execute`

(Rebasing newer work and pushing in a bit)

2023-11-15 12:24 UTC, shekhirin commented on crates/stages/src/stage.rs
> +    /// Unwinds may happen without consulting `poll_ready` first.
appreciate the docs

2023-11-15 12:24 UTC, shekhirin commented on crates/stages/src/stages/hashing_account.rs
> +                    let (tx, rx) = mpsc::channel();
missing channel size

2023-11-15 12:24 UTC, shekhirin commented on crates/stages/src/stages/sender_recovery.rs
> +            let (recovered_senders_tx, recovered_senders_rx) = mpsc::channel();
missing channel size

2023-11-15 12:24 UTC, shekhirin commented on crates/storage/provider/src/traits/header_sync_gap.rs
> +        last_uninterrupted_block: BlockNumber,
nit
```suggestion
        highest_uninterrupted_block: BlockNumber,
```

2023-11-15 12:28 UTC, mattsse requested changes
this looks great!

I like this a lot.
some style nits

2023-11-15 12:28 UTC, mattsse commented on bin/reth/src/stage/dump/hashing_storage.rs
> +        done = stage.execute(&provider, input)?.done;
same

2023-11-15 12:44 UTC, rkrasiuk commented on crates/stages/src/stages/hashing_account.rs
> +                    let (tx, rx) = mpsc::channel();
standard mpsc channel is unbounded

2023-11-15 14:06 UTC, shekhirin commented on crates/stages/src/stages/hashing_account.rs
> +                    let (tx, rx) = mpsc::channel();
my bad, fr

2023-11-17 19:52 UTC, mattsse approved these changes
lgtm, some suggestions that could be done as followups


I'd also suggest renaming ExecInput to ExecContext?

2023-11-17 19:52 UTC, mattsse commented on bin/reth/src/stage/run.rs
> +            poll_fn(|cx| exec_stage.poll_execute_ready(cx, input)).await?;
we add an extension trait with a helper function that does this:

https://docs.rs/tower/latest/tower/trait.ServiceExt.html#method.ready

but perhaps not worth it, maybe in a followup

2023-11-17 19:52 UTC, mattsse commented on crates/stages/src/stages/bodies.rs
> +    buffer: Vec<BlockResponse>,
these could probably be an Option, right?
with the assumption that calling execute before ready can panic

but this is fine

2023-11-17 19:52 UTC, mattsse commented on crates/stages/src/stages/headers.rs
> +    provider: Provider,
I like this a lot, no more fiddling with the db types directly,
we could also box this I think

2023-11-17 21:20 UTC, merged