Update lib.rs
paradigmxyz/reth pull request #4879
Opened 2023-10-02 15:46 UTC by DoTheBestToGetTheBest

2023-10-02 15:55 UTC, DoTheBestToGetTheBest commented
Could i ask help on what i need to do in the next step please?

2023-10-02 17:25 UTC, mattsse requested changes

2023-10-02 17:25 UTC, mattsse commented on crates/net/discv4/src/lib.rs
> +                        && !self.pending_find_nodes.contains_key(&node.key.preimage().0)
please use nightly formatting `cargo +nightly fmt`

2023-10-02 17:25 UTC, mattsse commented on crates/net/discv4/src/lib.rs
> +                        todo!()
this needs to emit the event 

and here we need to handle the terminate:

https://github.com/paradigmxyz/reth/blob/858ea41da1f8852e93e0604dbb2f7a89a5398b28/crates/net/discv4/src/lib.rs#L1618-L1618

2023-10-02 18:17 UTC, DoTheBestToGetTheBest commented
I'm really sorry if i'm asking newbie questions for most of you

2023-10-02 20:16 UTC, mattsse commented
it's okay, we're almost there, the only thing missing:

https://github.com/paradigmxyz/reth/pull/4879#discussion_r1342963406

2023-10-02 20:18 UTC, DoTheBestToGetTheBest commented
> it's okay, we're almost there, the only thing missing:
> 
> [#4879 (comment)](https://github.com/paradigmxyz/reth/pull/4879#discussion_r1342963406)

I'm really sorry but i didn't what it means by emit the event ? Sorry again Mat, i know you have better to do then telling me

2023-10-02 20:49 UTC, DoTheBestToGetTheBest commented
@mattsse hey again, sorry again for all this questions. How it look like for you ? added an event, and return None if Poll::ready is terminated

2023-10-03 10:45 UTC, mattsse approved these changes
this is great, tysm!

2023-10-03 10:46 UTC, DoTheBestToGetTheBest commented
> this is great, tysm!

oh i don't understand this, is this okey ? or i need to change others thing or i'm wrong in the implementation ?

2023-10-03 10:49 UTC, mattsse commented
yes this is great, I made a few smol touchups and pushed to #4888

because you're opened the PR from your main branch I'm unable to push changes here directly,
if you want you can merge #4888 into this PR real quick

2023-10-03 11:02 UTC, DoTheBestToGetTheBest commented
> yes this is great, I made a few smol touchups and pushed to #4888
> 
> because you're opened the PR from your main branch I'm unable to push changes here directly, if you want you can merge #4888 into this PR real quick

Everything good then Matt thank you so much, i'm ready to take another good first issue if you can open one please :)

2023-10-03 11:05 UTC, mattsse commented on crates/net/discv4/src/lib.rs
> +    /// A
```suggestion
    /// Service is being terminated
```

2023-10-03 11:08 UTC, DoTheBestToGetTheBest commented
I take another good first issue if you open one today :)

2023-10-03 11:27 UTC, merged