update trace_filter, trace block only to highest matching index
paradigmxyz/reth pull request #4974
Opened 2023-10-10 19:45 UTC by smatthewenglish

This PR aims to address the following TODO:
```
// TODO: this could be optimized to only trace the block until the highest matching index in
// that block
```

This is my first contribution to `reth`, I've read through the CONTRIBUTING.md doc and executed all the specified checks. If there's anything I've overlooked or missed please let me know and I'll be happy to address it.

2023-10-11 10:54 UTC, mattsse requested changes
that's a great start.

I have some nits,
the biggest improvement would still be to only trace the block until the highest index, for that we'd need a new function that is similar to:
https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/trace.rs#L363-L369
pub only traces the block until a given transaction, 
we can unify some code by moving this loop to a standalone function so it can be reused:

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/trace.rs#L408-L408

2023-10-11 10:54 UTC, mattsse commented on crates/rpc/rpc/src/trace.rs
> +                    }
this check is redundant because all tx_idx are only increasing

2023-10-11 10:54 UTC, mattsse commented on crates/rpc/rpc/src/trace.rs
> +                        }
this is a smol improvement, however this still traces the entire block, 
https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/trace.rs#L353-L362

2023-10-11 10:54 UTC, mattsse commented on crates/rpc/rpc/src/trace.rs
>              let traces = self.trace_block_with(
there's something else we need to do here:
skipping blocks with empty indices entirely

2023-10-12 01:27 UTC, smatthewenglish commented
i wanted to localize this code in one place, instead of defining it twice, once for each function/
```
F: for<'a> Fn(
        TransactionInfo,
        TracingInspector,
        ExecutionResult,
        &'a revm_primitives::State,
        &'a CacheDB<StateProviderDatabase<StateProviderBox<'a>>>,
    ) -> EthResult<R>
    + Send
    + 'static,
```

so i defined it like this at the top of the file

```
trait TransactionCallback<R> 
where
    Self: for<'a> Fn(
        TransactionInfo,
        TracingInspector,
        ExecutionResult,
        &'a State,
        &'a CacheDB<StateProviderDatabase<StateProviderBox<'a>>>,
    ) -> EthResult<R>
    + Send
    + 'static,
{
}

impl<F, R> TransactionCallback<R> for F
where
    F: for<'a> Fn(
        TransactionInfo,
        TracingInspector,
        ExecutionResult,
        &'a State,
        &'a CacheDB<StateProviderDatabase<StateProviderBox<'a>>>,
    ) -> EthResult<R>
    + Send
    + 'static,
{
}
```

but i think that's still pretty redundant. I'm not that familiar with rust, it's why I wanna become a contributor to this project, to learn rust. is there a more idiomatic way to do that^?

2023-10-12 10:35 UTC, mattsse requested changes
nice, almost there

2023-10-12 10:35 UTC, mattsse commented on crates/rpc/rpc/src/trace.rs
> +                    }
I'd like to move this to `transactions.into_iter().take()` instead

2023-10-12 10:35 UTC, mattsse commented on crates/rpc/rpc/src/trace.rs
> +                Some(highest_idx),
this argument should be moved and should be the second argument, so that the closure is always the last argument

2023-10-12 14:06 UTC, mattsse commented on crates/rpc/rpc/src/trace.rs
> -                    }
we still need this

2023-10-12 15:56 UTC, mattsse requested changes

2023-10-12 15:56 UTC, mattsse commented on crates/rpc/rpc/src/trace.rs
> +}
I don't really like this because this is just a hack to make signatures nicer and not really needed

2023-10-12 18:33 UTC, mattsse approved these changes
nice, lgtm

2023-10-12 18:56 UTC, merged