feat: track encoded length with pooled txs
paradigmxyz/reth pull request #4976
Opened 2023-10-10 22:00 UTC by Rjected

This tracks the encoded length whenever txs are added to the pool

TODO:
 - [ ] Actually use the `encoded_length` field
 - [ ] Make sure #4969 works

2023-10-11 01:39 UTC, Rjected commented
The test expects a length of `262660`, which is actually the length of the RPC format of the transaction, ie it does not include a string header. These changes correctly calculate the length _with_ a header.
rpc format:
```
len(type || tx body)
```

network format:
```
len(rlp string header || type || tx body)
```

This is unintuitive to me because I thought it referred to the length of the tx in the network. I've asked for clarification on the `Request Blob Pooled Transactions` test, it's possible this is not the intended expected value.

2023-10-11 17:15 UTC, Rjected commented
`Request Blob Pooled Transactions` passes with the recent changes

2023-10-11 23:34 UTC, mattsse requested changes
ngl, rlp is kinda cursed -.-

smol remaining todo:

we can now remove this:

https://github.com/paradigmxyz/reth/blob/67c14def5dab4b6df2e075b1bf511a4328024d03/crates/transaction-pool/src/pool/mod.rs#L415-L415

and replace the field with a function that simply calls the function of the wrapped transaction:

https://github.com/paradigmxyz/reth/blob/67c14def5dab4b6df2e075b1bf511a4328024d03/crates/transaction-pool/src/validate/mod.rs#L212-L213

and add a note to the PoolTx trait encoded_length function, that this should be cached

Update: did this real quick

2023-10-13 10:35 UTC, mattsse approved these changes

2023-10-13 10:57 UTC, merged