example simulation transportless
paradigmxyz/reth pull request #5025
Opened 2023-10-14 19:28 UTC by supernovahs

Ref #4980 

I have a small question.
How should I access trace call ? 
cc @mattsse 
thanks

2023-10-15 09:54 UTC, mattsse requested changes
this is great!

left some pointers,

we also need a way to trace a `Transaction` via:

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/trace.rs#L70-L70

we want:
a conversion function in the rpc-types-compat crate that converts a transaction into a callrequest.

2023-10-15 09:54 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +    pub eth: Option<EthHandlers<Provider, Pool, Network, Events>>,
we don't want to expose internals here
```suggestion
   eth: Option<EthHandlers<Provider, Pool, Network, Events>>,
```

2023-10-15 09:54 UTC, mattsse commented on examples/trace-transaction-cli/src/main.rs
> +    pub receipient: Address,
let's do multiple
```suggestion
    #[arg(long, value_delimiter = ',')]
    pub recipients: Vec<Address>,
```

2023-10-15 09:54 UTC, mattsse commented on examples/trace-transaction-cli/src/main.rs
> +                            // TODO: CAll trace_call
we need an instance of `TraceApi`:

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-builder/src/lib.rs#L862-L862

we can add a new function `fn trace_api` that returns this from the registry, similar to:

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-builder/src/lib.rs#L1078-L1081

2023-10-15 09:55 UTC, mattsse commented on examples/trace-transaction-cli/src/main.rs
> +            tokio::spawn(async move {
let's use the `components.tasks` to spawn the service

2023-10-15 09:55 UTC, mattsse commented on examples/trace-transaction-cli/src/main.rs
> +        let provider = rpc_components.registry.provider().clone();
let's use the provider from the `components`

2023-10-16 10:17 UTC, supernovahs commented
We would have to change the. u64,u128 used in https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/transaction/mod.rs
As CallRequest uses alloy primitives .
Should we do this in a separate PR?
thx

2023-10-16 11:42 UTC, mattsse requested changes

2023-10-16 11:42 UTC, mattsse commented on examples/trace-transaction-cli/Cargo.toml
> +reth-primitives.workspace = true
all of these should be available from the reth crate as reexports

2023-10-16 11:44 UTC, mattsse commented
> We would have to change the. u64,u128 used in

I don't understand, we should be able to create a CallRequest from a Transaction by simply converting the types

we need to do this in this example, because otherwise we can call the trace function?

2023-10-17 12:10 UTC, supernovahs commented
cc @mattsse

2023-10-17 13:20 UTC, mattsse approved these changes
this is great, I made some small changes:

* don't try to fetch the transaction from db (because it isn't included yet)
* use existing trait to convert a pool transaction into TransactionSignedRecovered then convert this into CallRequest
*

2023-10-17 13:40 UTC, supernovahs commented
Too much to learn for me .thx

2023-10-17 13:46 UTC, merged

2023-10-17 14:06 UTC, mattsse commented
I know :)
you'll get there, lmk if you want to continue with something bigger

btw I opened https://github.com/paradigmxyz/reth/issues/5051 which should be nice to have