feat(db): codec encoding/decoding
paradigmxyz/reth pull request #51
Opened 2022-10-12 09:34 UTC by joshieDo

Summary:
--

When data is to be stored or read from the database, the type should implement `table::Encoding` and `table::Decoding` so it knows how to transform from a structured type to a list of bytes.

However, at the same time we have to care for how we encode this data. Either in a way that helps with sorting (`Table::Key`) or compactness (`Table::Value`). That's why we add external codecs such as scale for example.

Having them to be configurable through annotations allows us to contain their implementations/leakage to isolated portions of the project, and allows us to switch between them relatively easily (eg. benchmarking).

old
--

Added scale encoding, which allowed to remove most of the `impl` of some basic types.

Added `Headers` example.

~~Although, having to put `#[codec(compact)]` in every integer is kinda of annoying. I was kinda hoping it would do it by default. Another limitation of the lib is that inner types are not getting compacted at all (Vec<T>, Option<T>, etc...)~~

---

Added another one called `postcard`, which seemed to be good on the benchmarks. However, when I tested it with `Account`... it didn't perform as I expected it. I'd expect the maxsize to be 72 (u64 + 32bytes + 32bytes)... but it's encoding it to 144 bytes.. which is strange. Maybe I'm missing something.

2022-10-14 07:39 UTC, mattsse requested changes

2022-10-14 11:28 UTC, mattsse reviewed
As I understood it, this serves as a way to easily switch between codecs which we'll make use of for benchmarks?

once we settled on a codec this will be become obsolete, right?

can we add this to the readme?

2022-10-17 07:13 UTC, gakonst requested changes

2022-10-17 07:15 UTC, mattsse approved these changes
lgtm

2022-10-17 08:04 UTC, merged