Function builder for TransacitonRequest
paradigmxyz/reth pull request #5104
Opened 2023-10-19 22:31 UTC by DoTheBestToGetTheBest

2023-10-21 05:51 UTC, mattsse requested changes
nice,

only cosmetic nits

2023-10-21 05:51 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/transaction/request.rs
> +    }
these we don't need here, because these functions are only intended for testing

2023-10-21 05:51 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/transaction/request.rs
> +// impl Default for TransactionRequest {
please remove these comments

2023-10-21 05:51 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/transaction/request.rs
> +            }
this is currently not possible and needs some additional changes,

please remove for now and open an issue for blob support in transactionaction request, which we can add separately.

2023-10-21 08:53 UTC, DoTheBestToGetTheBest commented
> nice,
> 
> only cosmetic nits

Thank you so so so much !

2023-10-22 08:55 UTC, mattsse approved these changes

2023-10-22 09:17 UTC, merged