feat: roundtrip fuzz harness for `PooledTransactions`
paradigmxyz/reth pull request #5125
Opened 2023-10-21 19:56 UTC by 0xalpharush

Add a roundtrip fuzz harness for `PooledTransactions` by converting an existing unit test into a fuzz test. This harness identified a new bug (cc @Rjected). Run the harness with `cargo test-fuzz -p reth-eth-wire --run-until-crash` and reproduce the crash with `cargo test-fuzz -p reth-eth-wire --replay crashes`.

Partially addresses https://github.com/paradigmxyz/reth/issues/4962

2023-10-22 08:45 UTC, mattsse commented
what's the bug?

2023-10-23 19:39 UTC, Rjected commented
> what's the bug?

https://github.com/recmo/uint/pull/335 is one surfaced by this fuzz test

Another is related to payload length checks, PR soon

2023-10-23 20:02 UTC, Rjected requested changes
Just one comment about preserving existing behavior from `decode_pooled_transactions_data` in at least one test

2023-10-29 19:24 UTC, 0xalpharush commented on crates/net/eth-wire/tests/pooled_transactions.rs
> +}
I added an assertion that the existing tests decodes successfully in https://github.com/paradigmxyz/reth/pull/5125/commits/9eb594c8d0734b3cba383619b941c8a9fd6a6579

2023-10-30 15:54 UTC, mattsse approved these changes
lgtm, pending @Rjected

2023-10-30 17:10 UTC, Rjected approved these changes
LGTM!

2023-10-30 17:22 UTC, merged