Adding blob support for TransactionRequest
paradigmxyz/reth pull request #5129
Opened 2023-10-22 10:22 UTC by DoTheBestToGetTheBest

This PR need https://github.com/paradigmxyz/reth/pull/5121 this PR to be able to build since i changed u128 to U128

this PR should be able to close https://github.com/paradigmxyz/reth/issues/5118

2023-10-23 11:39 UTC, mattsse requested changes

2023-10-23 11:39 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/transaction/request.rs
> +    pub sidecar: Option<BlobTransactionSidecar>,
needs docs

2023-10-23 11:39 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/transaction/request.rs
> +    pub sidecar: Option<BlobTransactionSidecar>,
this should be marked with serde(flattened)

2023-10-23 11:39 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/transaction/request.rs
> +            (None, Some(_), access_list) => {
this is not correct, this should enforce that all eip4844 fields are none

2023-10-23 11:39 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/transaction/request.rs
> +            (None, None, access_list) => {
this needs to enforce that all 4844 fields are present

2023-10-27 10:24 UTC, mattsse approved these changes
thanks, I'll merge these into #5193 because there are some conflicts

2023-10-27 11:33 UTC, DoTheBestToGetTheBest commented
> thanks, I'll merge these into #5193 because there are some conflicts

oh but i didn't finish this

2023-10-27 11:36 UTC, mattsse commented
right, sorry, this was closed premature.

there'll be some conflicts after #5193 (function moved to compat)

2023-10-27 11:40 UTC, DoTheBestToGetTheBest commented
> right, sorry, this was closed premature.
> 
> there'll be some conflicts after #5193 (function moved to compat)

oh okey, don't worry then, i understand , 

thank you for this issue !

i'm still working on the new issue where i'am assigned, just it take some time because i'm facing some problems with this issue, I hope the deadline is not very close

2023-10-27 11:46 UTC, mattsse commented
sgtm!

no deadline, but feel free to open a draft anytime so I can provider some pointers more easily

2023-10-27 11:49 UTC, DoTheBestToGetTheBest commented
> sgtm!
> 
> no deadline, but feel free to open a draft anytime so I can provider some pointers more easily

well tbh i don't want to open draft for this because i know what to do for it but i'm just blocked in something which i want to resolve it alone, don't wanna bother you with this

Thank you so much for all help and pointers you're giving for all this community !

2023-10-27 18:08 UTC, closed without merging