feat: remove const generics from cursors and add segment masks
paradigmxyz/reth pull request #5181
Opened 2023-10-25 16:34 UTC by joshieDo

PR into #5170

* Removes const generics from `NippyJarCursor` and `SnapshotCursor`.
* Adds a bunch of helper traits and structs for using  `SnapshotCursor` with masks to query and decode values.
* Split `storage/db/snapshot into different files`

Feels way better/more readable to me. Follow-ups are implementing the rest of `SnapshotJarProvider` providers

2023-10-25 16:43 UTC, mattsse commented on crates/storage/db/src/snapshot/mask.rs
> +pub trait ColumnMaskTwo {
can we get a few more docs about what this actually does, and what all of this represents.

having a hard time deciphering what a mask, column, row is in this context.

2023-10-25 16:43 UTC, mattsse commented on crates/storage/db/src/snapshot/mask.rs
> +pub struct Mask<T, J = (), K = ()>(std::marker::PhantomData<(T, J, K)>);
what are these types used for if they are set to unit type in the type aliases?

2023-10-26 13:13 UTC, mattsse requested changes
the comments make this now perfectly clear and the mask type and the getters are easy to read

2023-10-26 13:13 UTC, mattsse commented on crates/storage/db/src/snapshot/mask.rs
> +    /// Second cdesired olumn value
```suggestion
    /// Second desired column value
```

2023-10-26 13:13 UTC, mattsse commented on crates/storage/db/src/snapshot/mask.rs
> +pub struct Mask<T, J = (), K = ()>(std::marker::PhantomData<(T, J, K)>);
Can we rename this to smth that makes it obvious that these are the column types,

like `FIRST`, `SECOND` etc to make that obvious?

2023-10-27 10:53 UTC, shekhirin approved these changes
only nits, appreciate the comments. I wonder if there's better way to do that without too much boilerplate, but seems hard without at least https://github.com/rust-lang/rust/issues/29661.

2023-10-27 10:53 UTC, shekhirin commented on crates/storage/db/src/snapshot/masks.rs
> +add_snapshot_mask!(HeaderMask, <HeaderTD as Table>::Value, 0b010);
just to have them in order
```suggestion
add_snapshot_mask!(HeaderMask, <HeaderTD as Table>::Value, 0b010);
add_snapshot_mask!(HeaderMask, BlockHash, 0b100);
```

2023-10-27 10:53 UTC, shekhirin commented on crates/storage/db/src/snapshot/cursor.rs
> +    Hash(&'a [u8]),
just to be consistent with the terminology here, because a sequence of bytes shouldn't always be a hash
```suggestion
    Key(&'a [u8]),
```

2023-10-30 11:27 UTC, mattsse approved these changes
lgtm

2023-10-30 12:35 UTC, merged