wip: add TransactionsHandle function
paradigmxyz/reth pull request #5198
Opened 2023-10-26 21:56 UTC by smatthewenglish

Initial attempt/sketch at a solution to [Issue #5143](https://github.com/paradigmxyz/reth/issues/5143)

2023-10-26 22:43 UTC, mattsse requested changes
great initial draft.

we can convert this int general purpose `GetPeerSender` command and the request handling can happen entirely outside of the TransactionManager in the Handle

2023-10-26 22:43 UTC, mattsse commented on crates/net/network/src/transactions.rs
> +    TransactionsHandle {
```suggestion
    GetPeerSender {
```

2023-10-26 22:43 UTC, mattsse commented on crates/net/network/src/transactions.rs
> +        result: oneshot::Sender<Result<RequestResult<PooledTransactions>, RecvError>>,
it's easier to return a clone of the Sender if the peer exists
```suggestion
        result: oneshot::Sender<Option<PeerRequestSender>>,
```

2023-10-26 22:43 UTC, mattsse commented on crates/net/network/src/transactions.rs
> +        requested_hashes: Vec<TxHash>,
```suggestion
```

2023-10-26 22:43 UTC, mattsse commented on crates/net/network/src/transactions.rs
> +                }
this should return `peer.request_tx.clone()`

and all the request logic should happen in the context of the `TransactionHandle` where we can use await

2023-10-27 01:27 UTC, smatthewenglish commented on crates/net/network/src/transactions.rs
> +        peer_id: PeerId,
that makes me think maybe we should remove `peer_id` 'cause it already exists on `PeerRequestSender`

2023-11-06 13:25 UTC, mattsse approved these changes

2023-11-06 13:48 UTC, merged