Add missing beacon API eventstream-types
paradigmxyz/reth pull request #5200
Opened 2023-10-27 07:44 UTC by i-m-aditya

Fixes #5152

2023-10-27 07:45 UTC, i-m-aditya commented
@mattsse Is the approach correct? I am receiving JSON string and then deserializing it to events struct.

2023-10-27 08:38 UTC, mattsse requested changes
nice start.

we also want some tests

here's a sample for head

```json
{
    "slot": "202656",
    "block": "0x023b140bea768d741c42214a742bf6d50279828fd78774ebb077e8a7bd9cd7b9",
    "state": "0xa4ab3b5f3c00dff2842e545a683ecfe0190daea795fad62372f5f2c44fef40dd",
    "current_duty_dependent_root": "0x4b65252090bb84a831703f641f9abd36b27c5dc7a9b6d716d58122edbf6fc3de",
    "previous_duty_dependent_root": "0xa90c02c51761c1d20a7fff8f9ba403117ebd038be017304dbc2ab5d96b144064",
    "epoch_transition": true,
    "execution_optimistic": true
}
```

finalized checkpoint:

```json
{
    "block": "0xeac147a2c136eb4969f3c2c3b3447d438478befcb182082606af7162b504dd3f",
    "state": "0xbeeda7a8e3b3c9f4b6ba63cc6dad9f95024412f78fe33e323c019b14b9cdb819",
    "epoch": "6343",
    "execution_optimistic": true
}
```

2023-10-27 08:38 UTC, mattsse commented on examples/beacon-api-sse/src/main.rs
we want to limit this example to payload attributes only, so please revert changes here

2023-10-27 08:38 UTC, mattsse commented on examples/beacon-api-sse/src/main.rs
> +}
this can be moved to rpc-types crate

2023-10-27 08:38 UTC, mattsse commented on examples/beacon-api-sse/src/main.rs
> +    fn to_string_representation(&self) -> String {
```suggestion
    fn query_value(&self) -> &'static str {
```

2023-10-30 15:52 UTC, mattsse requested changes
this is great ty,

please remove all the `rename_all camelCase` attributes which then makes all the other renames redundant

2023-10-30 18:00 UTC, i-m-aditya commented
> this is great ty,
> 
> please remove all the `rename_all camelCase` attributes which then makes all the other renames redundant

I was going to do it in draft PR, but missed it :/

2023-10-30 19:37 UTC, mattsse requested changes
this is great,

some requests, also we need to change all the string types.

epoch+slot as u64 and use serde_as DisplayFromStr
https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-types/src/eth/engine/beacon_api/events.rs#L207-L207
hash types need to be `B256`, like epoch,hash,commitment etc...

2023-10-30 19:37 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/engine/beacon_api/attestation.rs
> +#[serde(rename_all = "camelCase")]
serde attributes not needed

2023-10-30 19:37 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/engine/beacon_api/attestation.rs
> +#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
add `Eq` derive

2023-10-30 19:37 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/engine/beacon_api/events.rs
> +#[derive(Debug, Clone)]
Copy, PartialEq,Eq

2023-10-30 19:37 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/engine/beacon_api/events.rs
> +    PayloadAtrributes,
```suggestion
    PayloadAttributes,
```

2023-10-30 19:37 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/engine/beacon_api/events.rs
> +pub enum BeaconNodeEventTopic {
we need a function that returns the topic name for the variant

2023-10-31 14:32 UTC, mattsse requested changes
nice, last tiny nit

2023-10-31 14:32 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/engine/beacon_api/events.rs
> +    pub fn query_value(&self) -> String {
```suggestion
    pub fn query_value(&self) -> &'static str {
```

2023-10-31 17:10 UTC, mattsse approved these changes

2023-10-31 18:35 UTC, merged