block_with_senders in ethstatecache
paradigmxyz/reth pull request #5302
Opened 2023-11-05 12:17 UTC by supernovahs

TODO:
Change conversion function to use the api 

@mattsse Can u take a look at the changes and suggest a better approach?
My code is doing a lot of clones.

2023-11-07 14:59 UTC, mattsse requested changes
this looks great already!

some requests:
* modify `block_with_senders` so that it supports `BlockHashOrNumber` (should be separate PR)
* always store BlockWithSenders

2023-11-07 14:59 UTC, mattsse commented on crates/rpc/rpc-types/src/eth/block.rs
> +                                return Err(serde::de::Error::duplicate_field("blockNumber"))
please don't reformat this, this makes it a lot harder to review

2023-11-07 14:59 UTC, mattsse commented on crates/rpc/rpc/src/eth/cache/mod.rs
> +                                    .unwrap_or_else(|e| {});
these unwraps seem unneccessary?

2023-11-07 14:59 UTC, mattsse commented on crates/rpc/rpc/src/eth/cache/mod.rs
> +                                        .find_block_by_hash(block_hash, BlockSource::Database);
this step is redundant we only do this to get the block number.

we should add a new helper function to the provider that takes the hash instead:

`block_with_senders_by_hash`:

https://github.com/paradigmxyz/reth/blob/main/crates/storage/provider/src/traits/block.rs#L115-L124

2023-11-07 14:59 UTC, mattsse commented on crates/rpc/rpc/src/eth/cache/mod.rs
> +}
I think we can simplify this by a lot if we always store `BlockWithSenders` instead, so every missing block should be fetched with senders

2023-11-12 08:10 UTC, supernovahs commented
https://github.com/paradigmxyz/reth/blob/63f67d97fd7e0007c806efb58dfae04d4aa8d895/crates/rpc/rpc-types-compat/src/block.rs#L68-L77 
This is the bottleneck right?

2023-11-14 11:52 UTC, mattsse commented
@supernovahs do you have the bandwidth to get this over the line?

2023-11-14 12:36 UTC, supernovahs commented
At the stage of changing the conversion function. Trying to figure out how to use the senders in from_block_full

2023-11-14 13:48 UTC, supernovahs commented
Let me know if this implementation makes sense. Thanks
@mattsse

2023-11-15 12:44 UTC, mattsse requested changes
nice, this is almost there.

2023-11-15 12:44 UTC, mattsse commented on crates/primitives/src/transaction/mod.rs
> +    pub signed_transaction: TransactionSigned,
these should remain private

2023-11-15 12:44 UTC, mattsse commented on crates/rpc/rpc-types-compat/src/block.rs
> +    let transactions_with_senders = body.into_iter().zip(block.senders);
there are now helper functions for this on the block type

2023-11-15 12:44 UTC, mattsse commented on crates/rpc/rpc-types-compat/src/block.rs
> +        .collect::<Result<Vec<_>, _>>()?;
we don't need the result anymore, right?

2023-11-15 12:44 UTC, mattsse commented on crates/rpc/rpc-types-compat/src/block.rs
> +                TransactionSignedEcRecovered { signer: sender, signed_transaction: tx };
there's now, tx.with_signer()

2023-11-15 12:44 UTC, mattsse commented on crates/rpc/rpc/src/eth/cache/mod.rs
> +}
we need to get rid of this enum and only handle BlockWithSenders

2023-11-15 12:44 UTC, mattsse commented on crates/rpc/rpc/src/eth/cache/mod.rs
> +                                    Ok(Some(BlockData::Block(block.unseal()))),
this needs to insert the BlockWithsenders,

we need to update:

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/cache/mod.rs#L534-L534

2023-11-17 10:17 UTC, mattsse requested changes
cache changes lgtm

still a few nits + failing tests

2023-11-17 10:17 UTC, mattsse commented on crates/rpc/rpc/src/eth/api/block.rs
> +        let block_with_senders = self.cache().get_block_with_senders(block_hash).await?;
this is redundant, because we already fetch the block above?

2023-11-17 12:04 UTC, mattsse commented
needs rebase and two open comments, then this is good

2023-11-18 08:43 UTC, mattsse commented
bump @supernovahs 
I really want to get this in

2023-11-18 08:45 UTC, supernovahs commented
Ah darn , I am afk for atleast 6 hours.
I tried to figure to out the bug as to why tests were failing. But no progress on it yet

2023-11-20 13:52 UTC, mattsse approved these changes
great!

I added the missing parts

2023-11-20 13:58 UTC, supernovahs commented
thanks 🫡

2023-11-20 15:06 UTC, merged