eat(rpc-testing-utils) : implement trace_call streaming.
paradigmxyz/reth pull request #5347
Opened 2023-11-07 22:36 UTC by DoTheBestToGetTheBest

2023-11-08 19:22 UTC, DoTheBestToGetTheBest commented
> @DoTheBestToGetTheBest please, for each PR write a clear and concise description that includes motivation for the changes and a brief overview of them. Also, some of your previous PRs need attention (#5267, #5321, #5329 etc). make sure to attend to them before opening new ones

oh my god, I'm so sorry I have to be such a bother. I didn't know about the descriptions, I thought a title was enough. Sorry again my friend, I'll be careful next time. Don't worry about my other PRs, at the moment I have exams that I am taking, I try to take some time to reth during my exams, as soon as I finish my exams, I will go back to my PRs. If my PRs are disturbing, I can close them, please let me know. Again i'm so sorry

2023-11-08 20:08 UTC, mattsse requested changes
nit

2023-11-08 20:08 UTC, mattsse commented on crates/rpc/rpc-testing-util/src/trace.rs
> +        block_overrides: Option<Box<BlockOverrides>>,
this should be replaced with the new

https://github.com/paradigmxyz/reth/blob/e056bfb213e7ddb2f4345d9717735475229024dd/crates/rpc/rpc-types/src/eth/trace/tracerequest.rs#L12-L12

type which makes this a lot easier

2023-11-10 11:40 UTC, mattsse approved these changes
nice

2023-11-10 11:57 UTC, merged