feat(op-reth): Canyon receipts root RLP fix
paradigmxyz/reth pull request #5504
Opened 2023-11-20 19:13 UTC by clabby

## Overview

Implements a draft fix for the canonical receipts root hashing bug from `op-geth` + `op-erigon`, included in the `Canyon` hardfork.

As it stands, this is pretty ugly. Handling this within `reth-primitives` seems the most prudent to ensure people can use the library correctly, though it also involves leaks in the abstraction where the receipt root hasher now has to know about the chainspec as well as the current timestamp to check which forks are active. Open to any suggestions.

2023-11-23 20:06 UTC, rkrasiuk approved these changes
lgtm

2023-11-24 15:18 UTC, mattsse requested changes
I'd like to have standalone functions for all the OP proofs

and all functions should accept `&ChainSpec`

2023-11-24 15:18 UTC, mattsse commented on crates/primitives/src/proofs.rs
> +) -> B256 {
I'd like this as a separate function for OP instead

this will make it easier once we eventually remove the feature

2023-11-24 15:18 UTC, mattsse commented on crates/primitives/src/proofs.rs
> +) -> B256 {
same

2023-11-24 15:18 UTC, mattsse commented on crates/primitives/src/receipt.rs
> +    ) -> Option<B256> {
same

2023-11-24 15:18 UTC, mattsse commented on crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
> +        #[cfg(feature = "optimism")] timestamp: u64,
same

2023-11-27 09:23 UTC, mattsse approved these changes

2023-11-27 16:16 UTC, merged