discv5 support
paradigmxyz/reth pull request #5576
Opened 2023-11-26 09:38 UTC by supernovahs

#1383 

TODO 
Add relevant traits in https://github.com/sigp/discv5 through a PR

2023-11-26 10:05 UTC, mattsse commented
> Add relevant traits in https://github.com/sigp/discv5 through a PR

this should not be required, everything we need on top of discv5 should go into the reth-discv5 crate

2023-12-03 05:06 UTC, supernovahs commented on crates/net/network/src/discovery.rs
> +            });
@mattsse discv5 does not implement clone trait . How should I go with this ?

```
future cannot be sent between threads safely
within `[async block@crates/net/network/src/discovery.rs:145:55: 152:14]`, the trait `std::marker::Send` is not implemented for `std::sync::MutexGuard<'_, Discv5>`

```

2023-12-04 13:38 UTC, mattsse requested changes
okay after looking at an example:

https://github.com/sigp/discv5/blob/aa12e384c52cc706a570b24260fef09f41c0181b/examples/find_nodes.rs#L159

I think all of this should be easier than expected, we perhaps don't even need the additional crate since the start function spawns the services.

what we should do here is

1. Configure discv5
2. `call start`
3. get an event stream
4. Store `Arc<Discv5>` internally as field and the eventstream as field

2023-12-04 13:38 UTC, mattsse commented on crates/net/network/src/discovery.rs
> +            })?;
I don't understand why this is necessary.

2023-12-05 07:31 UTC, supernovahs commented
`lint / MSRV / ethereum (pull_request) ` wants me to import enr crate , but clippy does not want me to add (its redundant).  😅

2023-12-05 08:41 UTC, supernovahs commented
@rkrasiuk let me know what additional changes need to be done.
Thanks

2023-12-05 10:35 UTC, mattsse requested changes
great!

what's missing now is polling the discv5 event stream in the poll function

2023-12-05 14:54 UTC, rkrasiuk commented on crates/net/discv5/src/lib.rs
> +}
```suggestion

/// The default table filter that results in all nodes being accepted into the local routing table.
const fn allow_all_enrs(_enr: &Enr) -> bool {
    true
}
```

2023-12-06 05:13 UTC, supernovahs commented on crates/net/network/src/discovery.rs
> +            .field("discv5", &format_args!("<Discv5>"))
cool

2023-12-06 11:49 UTC, supernovahs commented on crates/net/network/Cargo.toml
> +k256 = "0.13.2"
yes 
https://github.com/supernovahs/reth/blob/965f58ded5ef11cb8e6cf0041fc04559ece3bad1/crates/net/network/src/discovery.rs#L8

2023-12-08 09:19 UTC, mattsse requested changes
pretty close

2023-12-08 09:19 UTC, mattsse commented on crates/net/network/src/discovery.rs
> +                )
all of this should be moved to Discv5Wrapper

2023-12-08 09:19 UTC, mattsse commented on crates/net/network/src/discovery.rs
> +            Event::NodeInserted { node_id, replaced } => {}
here we need to handle the discovered entries

see https://github.com/paradigmxyz/reth/blob/32bf97d7bc7a862e5440f3182428de427585bb0f/crates/net/network/src/discovery.rs#L169-L169

2023-12-08 09:19 UTC, mattsse commented on crates/net/discv5/src/lib.rs
> +    Discv5EventStream(String),
these should use `#[from]` where possible or retain the wrapped error type

2023-12-08 09:19 UTC, mattsse commented on crates/net/discv5/src/lib.rs
> +pub struct Discv5Wrapper {
```suggestion
pub struct Discv5Handle {
```

2023-12-08 09:19 UTC, mattsse commented on crates/net/discv5/src/lib.rs
> +use tokio::sync::{mpsc, Mutex, MutexGuard};
we want a parking_lo::mutex here

2023-12-13 12:38 UTC, supernovahs commented on crates/net/network/src/discovery.rs
> +                    // local_enr.set_ip(socket_address.ip(),); #5576 figure out how to get signing
trying to figure out how to get the signing key to update the ip

2023-12-13 12:40 UTC, supernovahs commented
Some errors need to be handled apart from open comments.
Also, I am reviewing the implementation again to check for any bugs

2024-01-01 15:37 UTC, supernovahs commented
@mattsse any inputs on how to fix the test error. It occurred after using parking lot mutex . 
I tried debugging it. 
thanks

2024-01-05 16:28 UTC, mattsse requested changes

2024-01-05 16:28 UTC, mattsse commented on crates/net/discv5/src/lib.rs
> +    inner: Arc<Mutex<Discv5>>,
why do we need a mutex here?

2024-01-05 16:28 UTC, mattsse commented on crates/net/discv5/src/lib.rs
> +    pub async fn start_service(&self) -> Result<(), Discv5Error> {
can this not call start directly on the wrapped discv5?

2024-01-05 16:28 UTC, mattsse commented on crates/net/network/src/discovery.rs
> +            // let discv5_event_stream = Some(ReceiverStream::new(discv5_event));
please remove

2024-01-05 16:28 UTC, mattsse commented on crates/net/network/src/discovery.rs
> +                        discv5_guard.talk_req(enr.unwrap(), protocol.to_vec(), request.to_vec());
I don't think we need this

2024-01-09 21:53 UTC, gakonst commented
@supernovahs anything else you'd like to add? else @mattsse bump

2024-02-29 00:58 UTC, supernovahs commented
closing since #6151  is now the main PR for this

2024-02-29 00:58 UTC, closed without merging