add: default gpo constants
paradigmxyz/reth pull request #5662
Opened 2023-12-02 00:33 UTC by yash-atreya

Addresses #5661

2023-12-02 01:10 UTC, Rjected requested changes
Just some doc comment suggestions, otherwise this lgtm

2023-12-02 01:10 UTC, Rjected commented on crates/primitives/src/constants/mod.rs
> +pub const DEFAULT_GAS_PRICE_MAX: u64 = 500_000_000_000;
```suggestion
/// Maximum transaction priority fee (or gas price before London Fork) to be recommended by the gas price oracle
pub const DEFAULT_GAS_PRICE_MAX: u64 = 500_000_000_000;
```

2023-12-02 01:10 UTC, Rjected commented on crates/primitives/src/constants/mod.rs
> +///
```suggestion
```

2023-12-02 01:10 UTC, Rjected commented on crates/primitives/src/constants/mod.rs
> +/// Gas Price below which gpo will ignore transactions
```suggestion
/// Gas Price below which the gas price oracle will ignore transactions
```

2023-12-02 02:43 UTC, Rjected approved these changes
looks good to me, thanks!

2023-12-02 09:04 UTC, rkrasiuk reviewed
should these be in primitives crate? iirc it has no notion of gpo, so [rpc constants](https://github.com/paradigmxyz/reth/blob/0d522e84729038e3ff50a57e1fc79f019e82a5b2/crates/rpc/rpc-builder/src/constants.rs) is a better place to put it

2023-12-02 12:36 UTC, mattsse requested changes
I think so too,
can thenbe reexported from rpc-builder

2023-12-02 18:56 UTC, yash-atreya commented
> should these be in primitives crate? iirc it has no notion of gpo, so [rpc constants](https://github.com/paradigmxyz/reth/blob/0d522e84729038e3ff50a57e1fc79f019e82a5b2/crates/rpc/rpc-builder/src/constants.rs) is a better place to put it

It's done

2023-12-04 11:18 UTC, onbjerg approved these changes
lgtm

2023-12-04 13:23 UTC, mattsse requested changes
this needs a bit more work:

use constants here:

https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/args/gas_price_oracle_args.rs#L7-L21

get rid of Options

unify constants:

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/gas_oracle.rs#L20-L26

remove new function and use default initializor (`GasPriceOracleConfig {..Default:default}`) instead where needed

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/gas_oracle.rs#L70-L70

2023-12-05 22:49 UTC, yash-atreya commented
> this needs a bit more work:
> 
> use constants here:
> 
> https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/args/gas_price_oracle_args.rs#L7-L21
> 
> get rid of Options
> 
> unify constants:
> 
> https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/gas_oracle.rs#L20-L26
> 
> remove new function and use default initializor (`GasPriceOracleConfig {..Default:default}`) instead where needed
> 
> https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/gas_oracle.rs#L70-L70

@mattsse Almost done here.

To unify constants, I need to import the constants from `rpc-builder` and remove them from https://github.com/paradigmxyz/reth/blob/227e1b7ad513977f4f48b18041df02686fca5f94/crates/rpc/rpc/src/eth/gas_oracle.rs#L20-L26

This will require me to add `reth-rpc-builder` in the Cargo.toml of `rpc` but this causes a cyclical dependency. 
Need some guidance here. How can I import the constants from rpc-builder without causing this problem?

2023-12-06 14:56 UTC, mattsse requested changes
almost there

2023-12-06 14:56 UTC, mattsse commented on bin/reth/src/args/rpc_server_args.rs
> +        GasPriceOracleConfig::default()
here we need to use the values from self:

```
GasPriceOracleConfig {
  max_prise: self.max_price,
  ....
..Default::default
}

2023-12-06 14:56 UTC, mattsse commented on bin/reth/src/args/gas_price_oracle_args.rs
>      #[arg(long = "gpo.blocks", default_value = "20")]
use the actual constant for all arguments: `default_value_t = <const>`

2023-12-08 08:04 UTC, mattsse approved these changes
ty!

lgtm

2023-12-08 08:31 UTC, merged