More descriptive reorg log
paradigmxyz/reth pull request #5671
Opened 2023-12-04 09:13 UTC by fgimenez

Closes #5427 

Added "Reorg" explicitly to the log message and included words in the function name to make it easier to find/grep.

2023-12-04 13:06 UTC, mattsse approved these changes
I like this.

wdyt @rkrasiuk ?

2023-12-15 12:17 UTC, Rjected requested changes, later dismissed
needs a smol change for `cargo fmt`

2023-12-15 12:17 UTC, Rjected commented on crates/blockchain-tree/src/blockchain_tree.rs
> +        info!(target: "blockchain_tree", "Reorg: revert canonical from database by unwinding chain blocks {:?}", revert_range);
```suggestion
        info!(target: "blockchain_tree", "REORG: revert canonical from database by unwinding chain blocks {:?}", revert_range);
```

2023-12-15 12:17 UTC, Rjected commented on crates/blockchain-tree/src/blockchain_tree.rs
> +///
```suggestion
/// 
```

2023-12-15 12:17 UTC, Rjected commented on crates/blockchain-tree/src/blockchain_tree.rs
> +///
this is needed for `cargo fmt`

2023-12-15 13:31 UTC, merged