feat(bin) enhance logging config to make RUST_LOG for journalId and File writers
paradigmxyz/reth pull request #5687
Opened 2023-12-04 20:31 UTC by DoTheBestToGetTheBest

should solve https://github.com/paradigmxyz/reth/issues/5685

2023-12-04 22:31 UTC, DaniPopes commented
@DoTheBestToGetTheBest FYI to close issues automatically https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

2023-12-08 12:23 UTC, shekhirin requested changes
Hmm, can we initialize the `EnvFilter` with `from_env_lossy`, and then use `add_directive` to add `DEFAULT_ENV_FILTER_DIRECTIVE` and filter from arguments?

`add_directive` works by overwriting existing spans and events: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#method.add_directive

2023-12-08 14:16 UTC, DoTheBestToGetTheBest commented
> nt / clippy / ethereum (pull_reque

ty for your review and your help, changed file :)

2023-12-08 15:58 UTC, shekhirin approved these changes
LGTM, only nits!

2023-12-08 15:58 UTC, shekhirin commented on bin/reth/src/cli/mod.rs
> +            Ok(filter)
should work in one statement with builder pattern

```suggestion
            Ok(EnvFilter::builder().from_env_lossy()
                .add_directive(DEFAULT_ENV_FILTER_DIRECTIVE.parse()?)
                .add_directive(additional_directive.parse()?))
```

2023-12-08 15:58 UTC, shekhirin commented on bin/reth/src/cli/mod.rs
> +        // Function to create a new EnvFilter with base and specific directives
```suggestion
        // Function to create a new EnvFilter with environment, default and additional directive
```

2023-12-08 16:19 UTC, DoTheBestToGetTheBest commented
> LGTM, only nits!

ty so much  !

2023-12-11 14:57 UTC, shekhirin approved these changes
LGTM, thank you! Really clean change.

2023-12-11 15:07 UTC, merged

2023-12-11 17:22 UTC, DoTheBestToGetTheBest commented
> LGTM, thank you! Really clean change.

ty sir, appreciate lot