feat: add DatabaseMetrics trait for generic DB in reth node
paradigmxyz/reth pull request #5690
Opened 2023-12-05 01:08 UTC by Rjected

This adds a trait `DatabaseMetrics` that includes a `report_metrics` method, that extends the `Database` trait. This is meant for use in `bin/reth/node`, so we can reduce usage of `DatabaseEnv`, and move towards using a generic database in the node setup. Moving towards using a generic database everywhere in the node setup methods will allow us to use `TempDatabase` as the main `DB: Database` type in tests.

The `serve` method can now be generic over `DB`.

2023-12-06 15:01 UTC, mattsse requested changes

2023-12-06 15:01 UTC, mattsse commented on bin/reth/src/prometheus_exporter.rs
> +pub(crate) async fn serve<DB: DatabaseMetrics + 'static>(
I'd prefer a where close here instead
```suggestion
pub(crate) async fn serve<Metrics>(
```

2023-12-06 15:01 UTC, mattsse commented on bin/reth/src/prometheus_exporter.rs
> +    db: Arc<DB>,
```suggestion
    metrics: Metrics,
```

2023-12-11 16:56 UTC, Rjected commented on crates/storage/db/src/abstraction/database_metrics.rs
> +pub trait DatabaseMetrics: Database {
it doesn't, just removed, still calling it `DatabaseMetrics` for now since the db types are the only implementers

2023-12-11 16:59 UTC, Rjected commented on bin/reth/src/prometheus_exporter.rs
> +pub(crate) async fn serve<DB: DatabaseMetrics + 'static>(
using a where clause now

2023-12-11 20:57 UTC, mattsse approved these changes
lgtm

2023-12-11 22:39 UTC, merged