Base sepolia support
paradigmxyz/reth pull request #5697
Opened 2023-12-05 12:15 UTC by Chomtana

I have added base sepolia support to reth which should fixes #5653

However, I have not added test cases yet as I don't know how to get base_sepolia_forkids. It would be great if team can advise me on this.

If this looks good will proceed with op sepolia support.

2023-12-05 15:15 UTC, clabby commented
Thanks for the PR! Will review after work today.

2023-12-05 16:02 UTC, Chomtana commented
I'm testing running this but unluckily it doesn't advance blocks

Here is our op-node logs

```
Dec 05 15:59:02 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:02+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmR9YJEMR38uYu26S75Nr3Xdchq8Bg12Y3bYrreVnsjm4d
Dec 05 15:59:02 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:02+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmNoxHro3ty7C3LHLKqzQaNUaRLpj57d4MTyvEXpSCRWGJ
Dec 05 15:59:03 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:03+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAm1qN1noEzzcAaCDgDKGcnHvmX38WaLV4swyA7kCFpY4i3
Dec 05 15:59:05 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:05+0000 lvl=warn msg="failed to notify engine driver of L1 head change" err="context deadline exceeded"
Dec 05 15:59:07 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:07+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmKyyh2XrqVacKzYVwrvS186P5zb3CMnB4Hxz3HgsHFRJ1
Dec 05 15:59:07 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:07+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmJWCquweGvbxGRfdVwwxZxPPwr7qxNYnxhXQrMb2997xs
Dec 05 15:59:08 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:08+0000 lvl=warn msg="failed to notify engine driver of new L2 payload" err="context deadline exceeded" id=0xd24b907c69d965fb4b55647ee1e22d9549841e2aa740f37ed0ab95f09bff77f6:3011619
Dec 05 15:59:08 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:08+0000 lvl=info msg="Received signed execution payload from p2p" id=0x2f2ae79a1f987d392362e9508b38c48da76ac3cad6edf853b3d509737e352291:3011620 peer=16Uiu2HAmVnECeHftoUtVDeeseMQk3gaQDAuh2uC9CnTmv4noZBQD
Dec 05 15:59:09 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:09+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmD8EBKPFPddv5Ew7uFt1zQMACf5jWkjuCSpqAqfkZPCH6
Dec 05 15:59:12 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:12+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAkwgi8yGC7xoUsVCgxzMZ5KXQw89F2EYPAzcWtA3iuXv1s
Dec 05 15:59:13 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:13+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmMVmDasoqwfWirpmwsJH3WwRsy9TP5jw4y5BP9GJEa6Ur
Dec 05 15:59:13 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:13+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmJyHJ74d7Z3SSU1zFpGXbbYC27dNFKSFakH3roCD7rZos
Dec 05 15:59:13 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:13+0000 lvl=info msg="connected to peer"                      peer=16Uiu2HAmJyHJ74d7Z3SSU1zFpGXbbYC27dNFKSFakH3roCD7rZos addr=/ip4/3.236.207.129/tcp/9222
Dec 05 15:59:13 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:13+0000 lvl=info msg="Starting P2P sync client event loop"    peer=16Uiu2HAmJyHJ74d7Z3SSU1zFpGXbbYC27dNFKSFakH3roCD7rZos
Dec 05 15:59:13 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:13+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAm9DqQWWWEeeSewpDhEW9SrjRCadL7J4rkvuYTfZJha9e6
Dec 05 15:59:14 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:14+0000 lvl=info msg="disconnected from peer"                 peer=16Uiu2HAmUFQYVFYdqSiAKD3vXmu175NbByXdGVGcj8F8Net39YGa addr=/ip4/3.87.131.161/tcp/9222
Dec 05 15:59:17 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:17+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAkxKPR9N5n777quKoKmqmHCoCYdeHHGJPGNYvMNckPjwdE
Dec 05 15:59:17 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:17+0000 lvl=warn msg="failed to notify engine driver of L1 head change" err="context deadline exceeded"
Dec 05 15:59:19 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:19+0000 lvl=info msg="loaded new runtime config values!"      p2p_seq_address=0xb830b99c95Ea32300039624Cb567d324D4b1D83C
Dec 05 15:59:19 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:19+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmCMAdrMBdsK7uJhLfMFFUtMJq2YdUNk3aq2TizGxcFens
Dec 05 15:59:19 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:19+0000 lvl=info msg="disconnected from peer"                 peer=16Uiu2HAmKyyh2XrqVacKzYVwrvS186P5zb3CMnB4Hxz3HgsHFRJ1 addr=/ip4/46.4.65.162/tcp/31727
Dec 05 15:59:20 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:20+0000 lvl=info msg="disconnected from peer"                 peer=16Uiu2HAmFDyRWHRo4en69fK1gH1fS9TKezHnu1huveM2FtJTRcWK addr=/ip4/130.61.42.163/tcp/9222
Dec 05 15:59:20 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:20+0000 lvl=info msg="disconnected from peer"                 peer=16Uiu2HAmMEc2rMH6ckSCKGQ2vW955e5ncgrvVuCsLujCa5zqJa93 addr=/ip4/51.159.223.6/tcp/9222
Dec 05 15:59:22 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:22+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAm4nXkvxFyz9GFqp9J3vEckfWMmNLFJNzum4fWYGY6CgAN
Dec 05 15:59:23 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:23+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmG5YCzh8n583zWJ7yQeAgaTs1xcNmWhafTU6oFyhRZ27P
Dec 05 15:59:27 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:27+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmH1JKxSsSFLLJLk3U7zFv2uAvrnURRZFKDCCjQbxyxwLs
Dec 05 15:59:29 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:29+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAkxBQy6cAFetMH5xSgyE38985J2qWoAKATrRyNHAJjDC9u
Dec 05 15:59:29 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:29+0000 lvl=info msg="connected to peer"                      peer=16Uiu2HAkxBQy6cAFetMH5xSgyE38985J2qWoAKATrRyNHAJjDC9u addr=/ip4/34.227.58.0/tcp/9222
Dec 05 15:59:29 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:29+0000 lvl=info msg="Starting P2P sync client event loop"    peer=16Uiu2HAkxBQy6cAFetMH5xSgyE38985J2qWoAKATrRyNHAJjDC9u
Dec 05 15:59:29 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:29+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmRHDfmFCfibswiZWfy9CDuzWrUZyu7eUxJTBNmfrX8HF1
Dec 05 15:59:29 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:29+0000 lvl=warn msg="failed to notify engine driver of L1 head change" err="context deadline exceeded"
Dec 05 15:59:30 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:30+0000 lvl=info msg="connected to peer"                      peer=16Uiu2HAmRHDfmFCfibswiZWfy9CDuzWrUZyu7eUxJTBNmfrX8HF1 addr=/ip4/150.136.167.92/tcp/9222
Dec 05 15:59:30 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:30+0000 lvl=info msg="Starting P2P sync client event loop"    peer=16Uiu2HAmRHDfmFCfibswiZWfy9CDuzWrUZyu7eUxJTBNmfrX8HF1
Dec 05 15:59:30 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:30+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAkxhcpfY3X7ERtmM9cTLPG4XBeN4uTf6Y8EZWDa7dpof7n
Dec 05 15:59:30 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:30+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmR9YJEMR38uYu26S75Nr3Xdchq8Bg12Y3bYrreVnsjm4d
Dec 05 15:59:32 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:32+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmED2vqgsAxn2mNYBib8r1p3QrdjGgo2s42D6ymheXNoWc
Dec 05 15:59:33 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:33+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmUdSqQjC4cm9xxY4YK3StHRLWXe8zoMDTqtwCVh4rWJJM
Dec 05 15:59:34 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:34+0000 lvl=info msg="connected to peer"                      peer=16Uiu2HAmUdSqQjC4cm9xxY4YK3StHRLWXe8zoMDTqtwCVh4rWJJM addr=/ip4/34.227.161.78/tcp/9222
Dec 05 15:59:34 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:34+0000 lvl=info msg="Starting P2P sync client event loop"    peer=16Uiu2HAmUdSqQjC4cm9xxY4YK3StHRLWXe8zoMDTqtwCVh4rWJJM
Dec 05 15:59:34 op-reth-fullnode op-node[11560]: t=2023-12-05T15:59:34+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAm2FbGMXt7RBWMWrGyh8Bgqowhfkgk1d7rsnUnX [...]

2023-12-05 22:26 UTC, clabby requested changes

2023-12-06 07:00 UTC, Chomtana commented
Still got the error which is nonsense as it error about BlockGasUsed

op-geth

```
Dec 06 06:57:16 op-reth-fullnode op-reth[14128]: 2023-12-06T06:57:16.054960Z  WARN consensus::engine: Error while processing payload error=InsertBlockError { error: Execution(Validation(BlockGasUsed { gas: GotExpected { got: 63965, expected: 1000000 }, gas_spent_by_tx: [(0, 63965)] })), hash: 0x44b52cadd963750a046be3fa0e4f520fa2d4d22b5222e1a8034295c9d2fc6b6c, number: 1, parent_hash: 0x0dcc9e089e30b90ddfc55be9a37dd15bc551aeee999d2e2b51414c54eaf934e4, num_txs: 1, .. }
Dec 06 06:57:16 op-reth-fullnode op-reth[14128]: 2023-12-06T06:57:16.055016Z  WARN consensus::engine: Invalid block error on new payload invalid_hash=0x44b52cadd963750a046be3fa0e4f520fa2d4d22b5222e1a8034295c9d2fc6b6c invalid_number=1 error=Execution(Validation(BlockGasUsed { gas: GotExpected { got: 63965, expected: 1000000 }, gas_spent_by_tx: [(0, 63965)] }))
Dec 06 06:57:16 op-reth-fullnode op-reth[14128]: 2023-12-06T06:57:16.055029Z  WARN consensus::engine: Bad block with hash hash=0x44b52cadd963750a046be3fa0e4f520fa2d4d22b5222e1a8034295c9d2fc6b6c header=Header { parent_hash: 0x0dcc9e089e30b90ddfc55be9a37dd15bc551aeee999d2e2b51414c54eaf934e4, ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, beneficiary: 0x4200000000000000000000000000000000000011, state_root: 0x7bbfae434ca8ca95b0d2507e990a3252be5df7dbde15bdf7bc733323a48a78ee, transactions_root: 0x54e9f6846ba3df78380177daaeecbe0f8634b302247793c03fc4f3c8e11bc14e, receipts_root: 0xff07e961a994197df0f9406d373ef5d124e6febecf85a74ca0bcd436b2c5ad0e, withdrawals_root: None, logs_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, difficulty: 0x0_U256, number: 1, gas_limit: 25000000, gas_used: 1000000, timestamp: 1695768290, mix_hash: 0x0d3a4941f9c13233edd63f40847ed54e0050d38b2dff2347e31a76608bdcd83d, nonce: 0, base_fee_per_gas: Some(980000000), blob_gas_used: None, excess_blob_gas: None, parent_beacon_block_root: None, extra_data: Bytes(0x) }
```

op-node

```
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=info msg="Advancing bq origin"                    origin=0x2c8726436d28248113da87814b0721a65f2bf365d38820df31c2a9d232deaf83:4371286 originBehind=false
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=info msg="Advancing bq origin"                    origin=0xec7b2358e2dea1f05eb5efb46f053dc8f97e96c7f7d3cc460df09857565803d6:4371287 originBehind=false
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=info msg="Advancing bq origin"                    origin=0xa9b19d4df35a55feec5bffa84e01d6f22098cec085031af6446d45a79c5a870c:4371288 originBehind=false
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=info msg="created new channel"                    origin=0xa9b19d4df35a55feec5bffa84e01d6f22098cec085031af6446d45a79c5a870c:4371288 channel=6e687ab2153b70ca155383a6dc1931b6 length=105,609 frame_number=0 is_last=true
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=info msg="Reading channel"                        channel=6e687ab2153b70ca155383a6dc1931b6 frames=1
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=info msg="Found next batch"                       batch_timestamp=1,695,768,290 parent_hash=0x0dcc9e089e30b90ddfc55be9a37dd15bc551aeee999d2e2b51414c54eaf934e4 batch_epoch=0xcac9a83291d4dec146d6f7f69ab2304f23f5be87b1789119a0c5b1e4482444ed:4370868 txs=0
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=info msg="generated attributes in payload queue"  txs=1 timestamp=1,695,768,290
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=eror msg="cancelling old block sealing job"       payload=0x66dfe77e2b4c32e9
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=warn msg="could not process payload derived from L1 data, dropping batch" err="failed to complete building on top of L2 chain 0x0dcc9e089e30b90ddfc55be9a37dd15bc551aeee999d2e2b51414c54eaf934e4:0, id: 0x66dfe77e2b4c32e9, error (3): execution payload 0x44b52cadd963750a046be3fa0e4f520fa2d4d22b5222e1a8034295c9d2fc6b6c:1 was INVALID! Latest valid hash is 0x0dcc9e089e30b90ddfc55be9a37dd15bc551aeee999d2e2b51414c54eaf934e4, ignoring bad block: 0xc004053080"
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=eror msg="deposit only block was invalid"         parent=0x0dcc9e089e30b90ddfc55be9a37dd15bc551aeee999d2e2b51414c54eaf934e4:0 err="failed to complete building on top of L2 chain 0x0dcc9e089e30b90ddfc55be9a37dd15bc551aeee999d2e2b51414c54eaf934e4:0, id: 0x66dfe77e2b4c32e9, error (3): execution payload 0x44b52cadd963750a046be3fa0e4f520fa2d4d22b5222e1a8034295c9d2fc6b6c:1 was INVALID! Latest valid hash is 0x0dcc9e089e30b90ddfc55be9a37dd15bc551aeee999d2e2b51414c54eaf934e4, ignoring bad block: 0xc004053080"
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=eror msg="Derivation process critical error"      err="engine stage failed: crit: failed to process block with only deposit transactions: failed to complete building on top of L2 chain 0x0dcc9e089e30b90ddfc55be9a37dd15bc551aeee999d2e2b51414c54eaf934e4:0, id: 0x66dfe77e2b4c32e9, error (3): execution payload 0x44b52cadd963750a046be3fa0e4f520fa2d4d22b5222e1a8034295c9d2fc6b6c:1 was INVALID! Latest valid hash is 0x0dcc9e089e30b90ddfc55be9a37dd15bc551aeee999d2e2b51414c54eaf934e4, ignoring bad block: 0xc004053080"
Dec 06 06:51:21 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:21+0000 lvl=info msg="State loop returned"
Dec 06 06:51:23 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:23+0000 lvl=info msg="Received signed execution payload from p2p" id=0x6e70a8d9bbcdef1226f2415cdeeef878a0115157e9d75d4143a5a14ef0062a38:3038597 peer=16Uiu2HAkvcoELKxhAAKNscnycAUK7uYitAZMoMxEk2pazVag5UYH
Dec 06 06:51:23 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:23+0000 lvl=info msg="disconnected from peer"                 peer=16Uiu2HAmCFeWzFXhQY3QLPuUBmu6pgmRRJDsMG1NacDFaMhPyCfX addr=/ip4/54.235.20.108/tcp/9222
Dec 06 06:51:24 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:24+0000 lvl=info msg="Received signed execution payload from p2p" id=0xbb0b8dcd17c4217743620128d33985e9e014efb5f0c747cb28fa9175646b8c29:3038598 peer=16Uiu2HAmNoxHro3ty7C3LHLKqzQaNUaRLpj57d4MTyvEXpSCRWGJ
Dec 06 06:51:26 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:26+0000 lvl=info msg="Received signed execution payload from p2p" id=0x69823bde1dc978448a309169ceca70823fefdf69f615decc4e4f92b951818206:3038599 peer=16Uiu2HAmFMqvsatuZ2AsMncXqybkKSbShu1ZwnQ7ZieAcsFE3HHZ
Dec 06 06:51:27 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:27+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmTbpjqKPjg33ux212Y3dpGDS4o5VPyTk9Rmkgj64RskRX
Dec 06 06:51:27 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:27+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmUdSqQjC4cm9xxY4YK3StHRLWXe8zoMDTqtwCVh4rWJJM
Dec 06 06:51:27 op-reth-fullnode op-node[13999]: t=2023-12-06T06:51:27+0000 lvl=info msg="attempting connection"                  peer=16Uiu2HAmVnECeHftoUtVDeeseMQk3gaQDAuh2uC9CnTmv4noZBQD
```

2023-12-06 08:57 UTC, Chomtana commented on crates/primitives/src/chain/spec.rs
> +        fork_timestamps: ForkTimestamps::default().canyon(1699981200),
https://github.com/paradigmxyz/reth/pull/5697/commits/58a38aa8be95d88fb4df7bdd814a53e4b0e9815c

2023-12-06 08:57 UTC, Chomtana commented on crates/primitives/src/chain/spec.rs
> +            (Hardfork::Shanghai, ForkCondition::Block(0)),
https://github.com/paradigmxyz/reth/pull/5697/commits/58a38aa8be95d88fb4df7bdd814a53e4b0e9815c

2023-12-07 17:14 UTC, clabby commented
Gotcha! I can take a look this weekend. In the meantime, is your L1 Sepolia node an archive node?

2023-12-07 19:59 UTC, Chomtana commented
It's a quicknode one (50$/month plan) which should be an archive node

2023-12-13 19:04 UTC, quickchase commented
Any update here? 🙂

2023-12-18 10:52 UTC, rkrasiuk commented
@clabby @Chomtana what are the next steps here?

2023-12-22 14:26 UTC, Chomtana commented
https://base-sepolia.blockscout.com/block/1

Block hash: 0x44b31f42f3327b2497c94acd1d62dd3965b23da06268316e6085dbaf9900c22c

But in reth it says 0x44b52cadd963750a046be3fa0e4f520fa2d4d22b5222e1a8034295c9d2fc6b6c

which is invalid

2023-12-27 17:14 UTC, mattsse commented
the gas mismatch is very odd, not sure where the (gas_used: 1000000) gas_used is coming from?

but this is wrong?

if I query the first base sepolia block: `cast rpc eth_getBlockByNumber "0x1" true --rpc-url https://sepolia.base.org `

I get gas used by the block:
"gasUsed": "0xf9dd", (63965)

and for the systemTx:
"gas": "0xf4240",  1000000

2023-12-27 18:12 UTC, mattsse commented
Update:

I think I've found the bug; regolith is timestamp based hardfork and must be initialized as such, see also BASE_MAINNET:

https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/chain/spec.rs#L421-L421

this would explain the wrong gas_used because there are no refunds if regolith is not activated.

mind giving this another try @Chomtana ?

2023-12-27 18:20 UTC, Chomtana commented
Testing now. Thank you very much

2023-12-27 18:50 UTC, Chomtana commented
@mattsse it's looking good

## reth
<img width="1568" alt="image" src="https://github.com/paradigmxyz/reth/assets/4103490/53505a81-6499-4521-92db-39f9384d2b92">

## op-node
<img width="1431" alt="image" src="https://github.com/paradigmxyz/reth/assets/4103490/f5d0dcb2-b865-4d8b-a002-d32caf83602c">

2023-12-27 18:59 UTC, mattsse approved these changes
great!

in that case, happy to include this, all chainspec values look fine to me

2023-12-27 19:13 UTC, clabby approved these changes
Apologies for losing track of this; Thought I squared away my todo list prior to logging off for the holidays 😅 

Good catch @mattsse; LGTM.

2023-12-27 19:35 UTC, merged