Archify EthStateCache
paradigmxyz/reth pull request #5744
Opened 2023-12-13 08:12 UTC by i-m-aditya

Ref #5720

2023-12-13 08:14 UTC, i-m-aditya commented on crates/rpc/rpc/src/eth/cache/mod.rs
> +                                let receipts = Arc::new(receipts.clone());
@mattsse Is this the right way or should I archify it `this.receipts_cache.get(&block_hash)` function call itself.

2023-12-13 08:15 UTC, i-m-aditya commented on crates/rpc/rpc/src/eth/api/block.rs
> +                .zip(receipts.to_vec())
I was sceptic using this, any other way to not use extra memory and a workaround only using arc.

2023-12-13 10:20 UTC, rkrasiuk requested changes, later dismissed
couple of comments:
1. We should not change provider interfaces for this purpose
2. The values should be wrapped in `Arc` inside lru cache itself and the `Arc` should only be created upon insertion
3. Having values wrapped in an `Arc` would require creating a custom limiter since `ByLength` is not implemented for `Arc<Vec<T>>`
4. All of the other `to_vec` and `clone` calls should become unnecessary after completion of all steps above

2023-12-13 13:14 UTC, i-m-aditya commented
> couple of comments:
> 
> 1. We should not change provider interfaces for this purpose
> 2. The values should be wrapped in `Arc` inside lru cache itself and the `Arc` should only be created upon insertion
> 3. Having values wrapped in an `Arc` would require creating a custom limiter since `ByLength` is not implemented for `Arc<Vec<T>>`
> 4. All of the other `to_vec` and `clone` calls should become unnecessary after completion of all steps above

@rkrasiuk Thanks for the comments. However, I have one question
`let mut block_and_receipts = None;

        if block_id.is_pending() {
            block_and_receipts = self.provider().pending_block_and_receipts()?;
        } else if let Some(block_hash) = self.provider().block_hash_for_id(block_id)? {
            block_and_receipts = self.cache().get_block_and_receipts(block_hash).await?;
        }`
       For block_and_receipts to align with the same type, it can be Arc or the value itself. For this to happen, I need to change the provider interface. Am I missing something here?

2023-12-14 17:19 UTC, mattsse commented
ah I see,
need to think about more, but we should proceed with simply putting the pending receipts in a new Arc before returning

2023-12-15 11:14 UTC, i-m-aditya commented
> ah I see, need to think about more, but we should proceed with simply putting the pending receipts in a new Arc before returning

Yeah, would wrap the receipt in Arc and not change the provider interface.

2023-12-15 12:49 UTC, mattsse approved these changes
lgtm

2023-12-15 13:32 UTC, merged