Json structured logs
paradigmxyz/reth pull request #5784
Opened 2023-12-15 14:27 UTC by loocapro

Related to: #5726.

I tried to resume all the functionalities that were a bit spread between `bin/reth/src/cli/mod.rs` and `crates/tracing/src/lib.rs` into a single component defined in `crates/tracing/src/tracer.rs`.

Basic usage for a json stdout tracer would be:

```rust
Tracer::new().with_stdout(LayerInfo::new(
    LogFormat::Json,
    "debug".to_string(),
    LevelFilter::INFO.into(),
    None,
));
```
If no layer is configured it defaults to:

```rust
impl Default for LayerInfo {
    /// Provides default values for `LayerInfo`.
    ///
    /// By default, it uses terminal format, INFO level filter,
    /// no additional filters, and no color configuration.
    fn default() -> Self {
        Self {
            format: LogFormat::Terminal,
            directive: LevelFilter::INFO.into(),
            filters: "debug".to_string(),
            color: None,
        }
    }
}
```

I am a bit confused on why we use `log.filter` and `log.verbosity` as cli args.

So i have included them both in the `LayerInfo`, but i feel like since a directive is a rule derived from a filter, I can probably get rid of one of them.

LFF (looking for feedback!) please.

CC: @shekhirin @mattsse

2023-12-15 15:03 UTC, mattsse reviewed
this looks pretty good.

defer to @shekhirin and @onbjerg for a closer look

2023-12-21 11:09 UTC, mattsse commented
friendly bump here @shekhirin @onbjerg

2023-12-22 13:48 UTC, shekhirin reviewed
This looks great, just nits. Next step is integrating this into the existing logging configuration, right?

2023-12-22 13:48 UTC, shekhirin commented on crates/tracing/src/layers.rs
> +
```suggestion
```

2023-12-22 13:48 UTC, shekhirin commented on crates/tracing/src/layers.rs
> +        filter: String,
just for the consistency with other methods
```suggestion
        filter: &str,
```

2023-12-22 13:48 UTC, shekhirin commented on crates/tracing/src/layers.rs
> +                log_dir.join(AsRef::<Path>::as_ref(&self.file_name)),
I think it should work with just a reference
```suggestion
                log_dir.join(&self.file_name),
```

2023-12-22 13:49 UTC, shekhirin commented
> I am a bit confused on why we use log.filter and log.verbosity as cli args.

verbosity is an easy way to display all logs for a certain level without messing with `RUST_LOG`

2023-12-22 14:38 UTC, loocapro commented
> This looks great, just nits. Next step is integrating this into the existing logging configuration, right?

Great! Yep, I am going to proceed then!

2023-12-24 17:45 UTC, loocapro commented
Hi @shekhirin , I have managed to hook up all components.

I have also added a Tracer trait in order to standardise the init function and remove the `init_test_tracing` function and just have a TestTracer struct implementing the Tracer trait. If it's ok, i can proceed to replace every `init_test_tracing` with the `TestTracer` trait.

2024-01-01 16:06 UTC, loocapro commented
Hi @shekhirin gently bump here. I have managed to sync the code with latest main.

I have removed the TestTracer and just left the init_test_tracing function since it required a bit of changes around a lot of tests, but tell me if you want i can just do it.

I am a bit worried with dealing with more merge conflicts, so help me out here 😊

2024-01-02 12:26 UTC, mattsse commented
ah sorry about the conflicts, we should have included this much sooner.

ptal @shekhirin

2024-01-03 15:10 UTC, shekhirin requested changes
some questions on the API and overall simplification

2024-01-03 15:10 UTC, shekhirin commented on crates/tracing/src/layers.rs
> +const RETH_LOG_FILE_NAME: &str = "reth.log";
move to the top of the file

2024-01-03 15:10 UTC, shekhirin commented on crates/tracing/src/layers.rs
> +    /// Creates the log directory if it doesn't exist.
```suggestion
    }

    /// Creates the log directory if it doesn't exist.
```

2024-01-03 15:10 UTC, shekhirin commented on crates/tracing/src/layers.rs
> +        log_dir: &Path,
do we need to accept the directory argument here, even though it's always passed as the one constructed by `create_log_dir`? Maybe we can combine `create_log_dir` and `create_log_writer` into a single function to simplify the usage?

2024-01-03 15:10 UTC, shekhirin commented on crates/tracing/src/layers.rs
> +pub(crate) type BoxedLayer<S> = Box<dyn Layer<S> + Send + Sync>;
move to the top of the file

2024-01-03 15:10 UTC, shekhirin commented on crates/tracing/src/lib.rs
> +
```suggestion
```

2024-01-03 15:10 UTC, shekhirin commented on crates/tracing/src/lib.rs
> +impl Default for LayerInfo {
```suggestion
}

impl Default for LayerInfo {
```

2024-01-03 15:10 UTC, shekhirin commented on crates/tracing/src/lib.rs
> +    /// Initialize the logging configuration.
needs a comment about the return type and how to handle it

2024-01-03 15:10 UTC, shekhirin commented on crates/tracing/src/lib.rs
> +pub trait Tracer {
this is nice. I like that we can have a separate tracer for tests. Let's do it in another PR, so we can merge this one first.

2024-01-03 17:52 UTC, loocapro commented on bin/reth/src/args/log_args.rs
> +            self.log_file_filter.clone(),
Hi @shekhirin thanks for catching this!

Currently the EnvFilter for stdout is configured by verbosity (cli arg) + rust_log (env var). 

While the EnvFilter for file and journald is configured from the filter cli args (stdout does not have a filter cli arg).

This was already like this before, should we normalise this?

Something like: each layer has its own filter from cli args (which default values?), and stdout configures it with also the verbosity cli arg?

2024-01-04 13:42 UTC, loocapro commented
Hi @shekhirin ,

all review comments are resolved.

Keep in mind there is a slightly different behaviour than what it was before:

I have added `log_stdout_filter` which defaults to empty string. Before the stdout EnvFilter was configured from the `RUST_LOG` env var and the `verbosity` cli arg.

Also the verbosity cli arg is only being used by the stdout layer.

Let me know if we can finally merge this.

Thanks a lot!!

2024-01-08 16:28 UTC, mattsse commented
good to merge @shekhirin ?

2024-01-08 16:28 UTC, shekhirin commented
@mattsse testing rn

2024-01-09 11:19 UTC, shekhirin approved these changes
LGTM, works as expected! Thank you for addressing all the review comments 😄

2024-01-09 11:20 UTC, shekhirin commented
We will also need to change the CLI documentation in the book, and integrate the tracer into tests with the new `RethTracer` trait.

2024-01-09 11:23 UTC, loocapro commented
> LGTM, works as expected! Thank you for addressing all the review comments 😄

Thank you for your reviews!

> We will also need to change the CLI documentation in the book, and integrate the tracer into tests with the new `RethTracer` trait.

I can take care of it.

2024-01-09 11:30 UTC, merged