Feat/preload cached reads
paradigmxyz/reth pull request #5804
Opened 2023-12-17 19:30 UTC by allnil

draft PR for cache reads preload

2023-12-18 08:16 UTC, mattsse requested changes
great start so far!

we likely need more changes in the `BasicPayloadGenerator` which now needs a CachedReads and needs to use that to the instantiate a job if the parent_hash matches

2023-12-18 08:16 UTC, mattsse commented on bin/reth/src/cli/ext.rs
> +    fn spawn_payload_builder_service<Conf, Reth, St>(
this can be accessed via the `Reth` components instead `components.events()`

2023-12-18 08:16 UTC, mattsse commented on crates/payload/builder/src/service.rs
>  {
here' we need to poll the chain_events and then call the generator with the event.

The `on_new_state` we need to extract the new `tip` and extract the state+account into an initial CachedReads

2023-12-20 21:59 UTC, mattsse requested changes

2023-12-20 21:59 UTC, mattsse commented on crates/payload/builder/src/service.rs
> +            let mut canon_events = this.chain_events.subscribe_to_canonical_state();
oh actually, we can simplify all of this a lot.

sorry for the confusion.

we can just given the payloadbuilder service an instance of

https://github.com/paradigmxyz/reth/blob/b1d0dc41c2381951c0153a20dc1381b2434bca2a/crates/storage/provider/src/traits/chain.rs#L39-L39

obtained in the `spawn_payload_service` function, then we don't need any of the additional generics and can just poll the stream here

2023-12-29 09:40 UTC, mattsse requested changes
functionality wise this is exactly what we want!

this just needs a few more changes

2023-12-29 09:40 UTC, mattsse commented on crates/payload/builder/src/service.rs
> +                .map(|new_state| this.generator.on_new_state(new_state.unwrap()));
this should fully drain the stream using another while loop

2023-12-29 09:40 UTC, mattsse commented on crates/payload/builder/src/traits.rs
> +    fn on_new_state(&self, new_state: CanonStateNotification);
this we can me make `&mut self` then we don't need the lock

2023-12-29 09:40 UTC, mattsse commented on crates/payload/basic/src/lib.rs
> +    cached_reads: Arc<RwLock<CachedReads>>,
we need a new helper struct for this that:
* tracks the block hash of the tip this was computed for
* includes the CachedReads

then we need to check new_payload_job if the parent hash of the attributes matches, and only then can we use the CachedReads

2023-12-29 09:40 UTC, mattsse commented
sorry about the conflicts -.-

2024-01-09 15:12 UTC, rakita commented on crates/payload/basic/src/lib.rs
> +    }
In general this is okay, but would add helper function to `BundleStateWithReceipts` to make it more obvious, maybe something like `fn bundle_account_iter()`.

To point out, the bundle state contains only written accounts, not the reads, but it is still better than nothing.

2024-01-09 15:37 UTC, rkrasiuk commented on crates/payload/basic/src/lib.rs
> +    }
@mattsse you can create a new method `accounts_with_storage_iter` to make it easier. @rakita made good point that these are only writes, but that's better than nothing

2024-01-09 15:42 UTC, rkrasiuk reviewed
lgtm

2024-01-09 15:42 UTC, rkrasiuk approved these changes

2024-01-09 17:22 UTC, mattsse approved these changes

2024-01-09 17:32 UTC, merged