feat(network): get peer info
paradigmxyz/reth pull request #603
Opened 2022-12-24 12:18 UTC by ayushm2003

Closes #564 

Adds a new `PeerInfo` type and a new command `GetPeerInfo` to `NetworkHandleMessage`

2022-12-24 13:01 UTC, jonasbostoen commented
Perhaps there should also be a command to get info about a certain peer by ID?

2022-12-24 14:04 UTC, mattsse commented
> Perhaps there should also be a command to get info about a certain peer by ID?

good idea! let's add that

2022-12-24 14:08 UTC, mattsse requested changes
nice progress, left some early pointers

2022-12-24 14:08 UTC, mattsse commented on crates/net/network/src/network.rs
> +	GetPeerInfo,
the way this should work is similar to `FetchClient` command. It should take a `oneshot::Sender` through which the `NetworManager` will send the response. The `Handle` can await an the receiver half of the channel and return the response asynchronously.

2022-12-24 14:08 UTC, mattsse commented on crates/net/network/src/session/handle.rs
> +pub(crate) struct PeerInfo {
I think this should be public, right?

2022-12-24 14:08 UTC, mattsse commented on crates/net/network/src/session/mod.rs
> +		for (peer_id, session) in self.active_sessions.iter() {
nit: use `iter().map().collect()` instead of for loop and push to vec.

2022-12-24 20:07 UTC, ayushm2003 commented
> Perhaps there should also be a command to get info about a certain peer by ID?

Is it okay if I add them in the same pr?

2022-12-24 20:12 UTC, onbjerg requested changes

2022-12-24 20:12 UTC, onbjerg commented on crates/net/network/src/manager.rs
> +				println!("{:#?}", peer_info);
nit

```suggestion
```

2022-12-24 20:39 UTC, mattsse commented
> > Perhaps there should also be a command to get info about a certain peer by ID?
> 
> Is it okay if I add them in the same pr?

sure!

2022-12-27 11:37 UTC, ayushm2003 commented
Hey, I had a couple of questions -

1. Can we add the field `ClientId` to the [`Established`](https://github.com/paradigmxyz/reth/blob/c9958a4d13be69977032e306021de71584d08757/crates/net/network/src/session/handle.rs#LL70) event? The [doc](https://github.com/ethereum/devp2p/blob/6b0abc3d956a626c28dce1307ee9f546db17b6bd/rlpx.md#hello-0x00) mentioned in the comment does specify it as one of the parameters. This would allow us to add the field to [`ActiveSessionHandle`](https://github.com/paradigmxyz/reth/blob/c9958a4d13be69977032e306021de71584d08757/crates/net/network/src/session/mod.rs#L376)
2. I am not sure if there is a way to test the command manually, if so how?

2022-12-27 13:34 UTC, mattsse requested changes
we don't need async code in the manager.

for reference, see `NetworkHandleMessage::FetchClient`

2022-12-27 13:34 UTC, mattsse commented on crates/net/network/src/manager.rs
> +    async fn on_handle_message(&mut self, msg: NetworkHandleMessage) {
we don't need async here

2022-12-27 13:35 UTC, mattsse commented
> an we add the field ClientId to the Established event.

yes let's do that

2022-12-27 13:36 UTC, mattsse commented
> I am not sure if there is a way to test the command manually, if so how?

See this test for reference which connects peers manually. for the test we want the same (2 peers are enough) and then retrieve the info once they're connected.

https://github.com/paradigmxyz/reth/blob/main/crates/net/network/tests/it/connect.rs#L92

2022-12-28 18:46 UTC, gakonst commented
Hi @ayushm2003 let us know on your plans for this PR or if we should take it over^^

2022-12-28 19:30 UTC, ayushm2003 commented
Hey, Sorry for the delay. I have a commit ready to fix the compilation errors and will add the test later today. I don't really understand the [async requirement](https://github.com/paradigmxyz/reth/pull/603#discussion_r1056826691), so would appreciate some help in the form of a little more explanation or a commit. 

Would this be ok?

2022-12-28 20:58 UTC, mattsse commented
sending does not require async for `tokio::oneshot::Sender`, we don't want any `async/await` inside the control loop of the Network, we do however want async/await on the `NetworkHandle` which awaits the response on the `tokio::oneshot::Receiver`

2022-12-29 13:05 UTC, mattsse approved these changes
nice job!

tysm

2022-12-29 13:20 UTC, merged