feat(stages): log percentage progress of `Execution` stage
paradigmxyz/reth pull request #6073
Opened 2024-01-15 18:03 UTC by shekhirin

We lack observability in `Execution` stage when a large block range is being executed without reaching any thresholds, and the node is just silent about it.

2024-01-15 18:46 UTC, mattsse reviewed
I'd like a few more docs, because not immediately obvious what this does

This also does not address https://github.com/paradigmxyz/reth/issues/6014 right?

2024-01-15 21:31 UTC, Rjected commented on Cargo.toml
> +opt-level = 0
adding `opt-level = 0` here would mean that this is not much different than the dev profile, why remove the optimizations? I thought the point of `debug-fast` was to enable optimizations

2024-01-15 21:36 UTC, shekhirin commented on Cargo.toml
> +opt-level = 0
I was building with `debug-fast` and wanted to use an actual debugger, but any `opt-level > 0` may affect the source code in a way that makes some variables unavailable for debugger. But yes, you're right that it basically makes it almost the same as `debug`, so reverted and will not introduce in a separate PR.

2024-01-17 15:05 UTC, mattsse requested changes
imo this is an appropriate fix for long-running batches that improves observability for ranges with very high gas usage (DOS range mainnet, inscriptions testnets)

left some questions re use of instants

2024-01-17 15:07 UTC, shekhirin commented on crates/stages/src/stages/execution.rs
> +            fetch_block_duration += execute_start - block_start;
`time.elapsed() == Instant::now() - time`. This saves us one call to `Instant::now()`.

2024-01-17 15:09 UTC, shekhirin commented on crates/stages/src/stages/execution.rs
> +            fetch_block_duration += execute_start - block_start;
okay, I guess here we don't care about such small savings, will fix that

2024-01-17 15:10 UTC, mattsse commented on crates/stages/src/stages/execution.rs
> +            fetch_block_duration += execute_start - block_start;
gotcha! then this makes sense, thanks!

2024-01-17 15:11 UTC, mattsse approved these changes
lgtm

2024-01-17 16:54 UTC, merged