Moving more types from reth crate to node core crate
paradigmxyz/reth pull request #6102
Opened 2024-01-17 11:18 UTC by i-m-aditya

Ref #6063

2024-01-17 11:31 UTC, i-m-aditya commented
@mattsse Have moves args, and other modules on which it is dependent to the node-core crate. Any other refactoring required?

2024-01-17 11:45 UTC, i-m-aditya commented
Will fix the failed checks by EOD. But is this the desired approach.

2024-01-17 14:30 UTC, mattsse requested changes
this is a good draft!

we don't want that examples need to also add the node-core crate

instead we want to re-export node-core from the bin/reth crate

2024-01-18 12:53 UTC, mattsse requested changes
sweet,

last request to also reexport the types from previous locations, so that this change becomes non breaking. Because this is used by a few users already and we don't want to introduce breaking changes incrementally

2024-01-19 05:27 UTC, i-m-aditya commented on examples/additional-rpc-namespace-in-cli/src/main.rs
> +    node_core::cli::{
That would mean having the same modules(args, cli) in both crates: node-core and bin/reth. Should I go ahead and do this change?

2024-01-19 19:05 UTC, mattsse commented on examples/additional-rpc-namespace-in-cli/src/main.rs
> +    node_core::cli::{
yes please 🙏

adding a few mods with reexports is fine, we want to reduce breaking changes for now

2024-01-22 14:36 UTC, mattsse approved these changes
lgtm, pending @Rjected 

I assume we need a few smaller followups but since this touches a lot we should merge asap to reduce friction

2024-01-22 14:36 UTC, mattsse commented on examples/trace-transaction-cli/src/main.rs
> +
```suggestion
```

2024-01-22 14:36 UTC, mattsse commented on examples/beacon-api-sse/src/main.rs
> +
```suggestion
```

2024-01-22 14:36 UTC, mattsse commented on examples/additional-rpc-namespace-in-cli/src/main.rs
> +
```suggestion
```

2024-01-22 14:41 UTC, Rjected approved these changes
have some small nits, otherwise LGTM. for followup: removing any code that's now duplicated in `reth_node_core`

2024-01-22 14:41 UTC, Rjected commented on bin/reth/src/cli/ext.rs
> +/// the [NodeCommand](https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/commands/node/mod.rs).
should probably keep them relative to a crate so our doc tests can pick up on any missing links

2024-01-22 14:41 UTC, Rjected commented on bin/reth/src/commands/init_cmd.rs
> +use crate::init::init_genesis;
nit: this can probably be moved back to the `crate::{` import section

2024-01-22 15:15 UTC, merged