Refactor http server kind
paradigmxyz/reth pull request #6133
Opened 2024-01-19 16:18 UTC by supernovahs

closes #6017 

Still figuring out how to simplify it . 
Opening for ref  and inputs if any .

2024-01-19 17:25 UTC, mattsse requested changes

2024-01-19 17:25 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +    Server(Box<dyn Service<Request<Body>, Response = Response<Body>, Error = hyper::Error, Future = Pin<Box<dyn Future<Output = Result<Response<Body>, hyper::Error>>>>> + Send + Sync>),
The type signature will be very big but we can flatten all of this into a bunch of `Either<Layer, Identiy>` which is what OptionLayer is:

https://docs.rs/tower/latest/tower/builder/struct.ServiceBuilder.html#method.option_layer

2024-01-22 16:15 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +    Server(Server<tower::layer::util::Stack<tower::util::Either<reth_rpc::AuthLayer<reth_rpc::JwtAuthValidator>, tower::layer::util::Identity>, tower::layer::util::Stack<tower::util::Either<std::resu
yeah this is a bit horrible, but better than before,

can convert this to a struct now

2024-01-23 11:00 UTC, supernovahs commented on crates/rpc/rpc-builder/src/lib.rs
> +    //   #6133  How to call start() ?
figuring out this

2024-01-23 12:00 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +type EitherServer = Either<
no type aliases, we want struct wrapper for this

2024-02-27 11:42 UTC, supernovahs commented
Any way to resolve this error? 
```
error[E0599]: the method `start` exists for struct `Server<Stack<Either<AuthLayer<JwtAuthValidator>, Identity>, ...>, ...>`, but its trait bounds were not satisfied
    --> crates/rpc/rpc-builder/src/lib.rs:1960:35
     |
1960 |                 Either::A(a) => a.start(module).await, 
     |                                   ^^^^^ method cannot be called due to unsatisfied trait bounds
     |
    ::: /Users/supernovahs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-0.4.13/src/util/either.rs:22:1
     |
22   | pub enum Either<A, B> {
     | --------------------- doesn't satisfy `_: Layer<Either<AuthService<TowerService<RpcServerMetrics>, JwtAuthValidator>, TowerService<RpcServerMetrics>>>`
     |
    ::: /Users/supernovahs/.rustup/toolchains/nightly-2023-12-21-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:502:1
     |
502  | pub enum Result<T, E> {
     | --------------------- doesn't satisfy `_: Layer<Either<AuthService<TowerService<RpcServerMetrics>, JwtAuthValidator>, TowerService<RpcServerMetrics>>>`
     |
    ::: /Users/supernovahs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-layer-0.3.2/src/stack.rs:6:1
     |
6    | pub struct Stack<Inner, Outer> {
     | ------------------------------
     | |
     | doesn't satisfy `_: Layer<Either<AuthService<TowerService<RpcServerMetrics>, JwtAuthValidator>, TowerService<RpcServerMetrics>>>`
     | doesn't satisfy `_: Layer<TowerService<RpcServerMetrics>>`
     |
     = note: the full type name has been written to '/Users/supernovahs/Desktop/reth/target/debug/deps/reth_rpc_builder-a7d87878da363f83.long-type-2193867962893713952.txt'
     = note: the following trait bounds were not satisfied:
             `Stack<tower::util::Either<AuthLayer<JwtAuthValidator>, Identity>, Stack<tower::util::Either<std::result::Result<CorsLayer, CorsDomainError>, Identity>, Identity>>: Layer<jsonrpsee::jsonrpsee_server::server::TowerService<RpcServerMetrics>>`
             `Stack<tower::util::Either<std::result::Result<CorsLayer, CorsDomainError>, Identity>, Identity>: Layer<tower::util::Either<reth_rpc::layers::auth_layer::AuthService<jsonrpsee::jsonrpsee_server::server::TowerService<RpcServerMetrics>, JwtAuthValidator>, jsonrpsee::jsonrpsee_server::server::TowerService<RpcServerMetrics>>>`
             `tower::util::Either<std::result::Result<CorsLayer, CorsDomainError>, Identity>: Layer<tower::util::Either<reth_rpc::layers::auth_layer::AuthService<jsonrpsee::jsonrpsee_server::server::TowerService<RpcServerMetrics>, JwtAuthValidator>, jsonrpsee::jsonrpsee_server::server::TowerService<RpcServerMetrics>>>`
             `std::result::Result<CorsLayer, CorsDomainError>: Layer<tower::util::Either<reth_rpc::layers::auth_layer::AuthService<jsonrpsee::jsonrpsee_server::server::TowerService<RpcServerMetrics>, JwtAuthValidator>, jsonrpsee::jsonrpsee_server::server::TowerService<RpcServerMetrics>>>`

```

2024-03-27 01:47 UTC, closed without merging