feat: use alloy genesis now
paradigmxyz/reth pull request #6135
Opened 2024-01-19 17:43 UTC by supernovahs

2024-01-19 18:02 UTC, mattsse commented
I don't think we need this anymore

2024-01-19 18:04 UTC, mattsse requested changes

2024-01-19 18:04 UTC, mattsse commented on crates/primitives/src/genesis.rs
> -pub struct GenesisAllocator<'a> {
we removed this type from alloy-genesis so we want to keep this here

2024-01-19 18:17 UTC, supernovahs commented
1st issue pending, 2nd resolved

2024-01-19 18:56 UTC, gakonst commented
to make it explicit, we want to remove the dependency on ethers genesis

2024-01-19 19:01 UTC, mattsse reviewed
thanks @supernovahs this is great!

I'll get rid of the compile errors, I think I know how to fix

2024-01-20 10:08 UTC, mattsse approved these changes

2024-01-20 10:18 UTC, merged