feat: Implement fixed vec arbitrary manually for NewPooledTransactions68
paradigmxyz/reth pull request #6184
Opened 2024-01-23 16:44 UTC by supernovahs

closes #6173

2024-01-23 19:26 UTC, mattsse requested changes
cool, only two nits

2024-01-23 19:26 UTC, mattsse commented on crates/net/eth-wire/src/types/broadcast.rs
> +            .boxed()
I'd like to changes this a bit, now that we have this manually

types should be restricted to the TxType values, possible tx types, and ideally randomized vecs

2024-01-24 04:13 UTC, emhane commented
lgtm, not familiar with `arbitrary` though so waiting on @mattsse to see if anything can be simplified

2024-01-24 10:57 UTC, mattsse requested changes

2024-01-24 10:57 UTC, mattsse commented on crates/net/eth-wire/src/types/broadcast.rs
> +}
I don't think we need this `TxType as u8` should do it

2024-01-24 10:57 UTC, mattsse commented on crates/net/eth-wire/src/types/broadcast.rs
> +                let min_length = *[types.len(), sizes.len(), hashes.len()].iter().min().unwrap();
I wonder if this can improved by using a random length value for all the vec strategies instead?

2024-01-24 12:14 UTC, mattsse approved these changes
lgtm

2024-01-24 12:33 UTC, merged