feat: NetworkManager hibernate command, NetworkHandle hibernate funct…
paradigmxyz/reth pull request #6186
Opened 2024-01-23 17:13 UTC by loocapro

Related to #1208

Hi @mattsse,

I hope i am in the right direction.

Missing to:

- [ ] Pass network handle to Pipelines
- [ ] Toggling hibernation during Offline/Online Stages (i still need to decide the right strategy)

Leaving stages order and Offline stages details for reference below.

Stages execution order:

1. HeaderStage
2. TotalDifficultyStage
3. BodyStage
4. SenderRecoveryStage
5. ExecutionStage
6. MerkleStage (unwind)
7. AccountHashingStage
8. StorageHashingStage
9. MerkleStage (execute)
10. TransactionLookupStage
11. IndexStorageHistoryStage
12. IndexAccountHistoryStage
13. FinishStage

**Offline Stages**

**ExecutionStages**
 SenderRecoveryStage, ExecutionStage
 
**HashingStages**
MerkleStage, AccountHashingStage, StorageHashingStage, MerkleStage

**HistoryIndexingStages**
TransactionLookupStage, IndexStorageHistoryStage, IndexAccountHistoryStage

2024-01-23 18:15 UTC, mattsse requested changes
this looks good, though here's no way to rewake it yet, so we need that as well, 

I think we want an enum for activate,hibernate

2024-01-24 15:03 UTC, loocapro commented
> during initial sync, once bodies have been downloaded we no longer require the network (peers) since all operations are IO+Disk bound.

> and I don't want to integrate this in the stages at all because it's just one more thing to keep track of and not really useful, because tx gossip during sync is already disabled.

@mattsse what should be the recommended way to hibernate the network once the BodyStage is done but without integrating it inside the stages?

2024-01-24 15:11 UTC, mattsse commented
I don't really want to touch that in the stages, but I can see how this feature could be useful for folks that use the network crate as a standalone component

2024-01-26 15:25 UTC, loocapro commented
> I don't really want to touch that in the stages, but I can see how this feature could be useful for folks that use the network crate as a standalone component

Oh ok! I was looking at pipeline events actually. Do you think it would make sense to plug the Hibernate logic there? Or do you already have some logic that needs to be executed right after/before a specific stage?

2024-01-29 12:01 UTC, mattsse requested changes
okay after having a closer look at this, I'd like to change a few small things:

move:

https://github.com/paradigmxyz/reth/blob/matt%2Fnode-builder/crates/net/network/src/swarm.rs#L60-L61

to `PeersManager` and use this to track the state so we don't need the extra bool there

2024-01-29 13:56 UTC, loocapro commented
> okay after having a closer look at this, I'd like to change a few small things:
> 
> move:
> 
> https://github.com/paradigmxyz/reth/blob/matt%2Fnode-builder/crates/net/network/src/swarm.rs#L60-L61
> 
> to `PeersManager` and use this to track the state so we don't need the extra bool there

@mattsse, thanks for this, i have followed your comments!

How about handling NetworkConnectionState during pipeline events to toggle the filling of outbound connection slots? Too critical?

2024-01-29 14:03 UTC, mattsse requested changes
almost there

2024-01-29 14:03 UTC, mattsse commented on crates/net/network/src/swarm.rs
>  }
now that these are public, we should add some docs here

2024-01-29 14:03 UTC, mattsse commented on crates/net/network/src/network.rs
> +    ToggleNetworkConnection(NetworkConnectionState),
```suggestion
    SetNetworkState(NetworkConnectionState),
```

2024-01-29 14:03 UTC, mattsse commented on crates/net/network/src/network.rs
> +    }
here we want to flatten the enum into individual commands, be we can keep this as well, the other calls simply call this then

2024-01-29 14:03 UTC, mattsse commented on crates/net/network/src/manager.rs
> +                    _ => {}
we should still set the state,

2024-01-29 14:03 UTC, mattsse commented on crates/net/network/src/manager.rs
> +                    _ => {}
this should happen in the peers manager, and simply do 

self.state = state;

2024-01-29 17:06 UTC, mattsse approved these changes
thanks, lgtm

I only moved the hibernate check out of the loop and added some additional docs

2024-01-29 17:26 UTC, merged