Hashed post state cursor works on top of a trait instead of &Tx.
paradigmxyz/reth pull request #6226
Opened 2024-01-25 17:30 UTC by dvush

Please consider this.

There are 2 hashed cursor implementations in the `reth_trie`
1. `default.rs` that is implemented on top of database `&Tx`
2. `hashed_cursor.rs` that uses database `&Tx` and trie changes on top (`HashedPostState`)

Both of them implement all `Hashed*Cursor*` traits.

What this PR changes is `hashed_cursor.rs` implementation so that is does not depend on `&Tx` directly but instead on `Hashed*Cursor*` traits.

The behavior for `hashed_cursor` is the same as before when &Tx is used as a `HashedCursorFactory`.

I am using this to implement caching of the database and this allows using caching implementation of the `Hashed*Cursor*` traits as underlying database source for `hashed_cursor`.

Notes:
* I removed manual Clone implementation that was copying refs because `&T` implements `Clone` for any type and its just a reference copy.
* I had to add `current` method to the `HashedAccountCursor` because it was used by `HashedPostStateAccountCursor` 
    * because of that in addition to account key, account struct is stored as a last account in the `HashedPostStateAccountCursor` and it adds overhead that was not there before. I am not sure that this is needed but to fit this into one abstraction either `unimplemented!` should be used for `current` or we should store last returned account value.

2024-01-25 17:47 UTC, rkrasiuk commented
i hear ya, the suggestion makes sense. let me poke around it for a bit, see if new abstraction constraints make sense

2024-01-25 18:02 UTC, dvush commented
Thanks!

2024-01-26 10:06 UTC, rkrasiuk requested changes
we can avoid adding `current` method and storing for account info for last account by changing this call to `self.cursor.seek(*last_account)`, similar to how it's done in `HashedPostStateStorageCursor`
https://github.com/paradigmxyz/reth/blob/04ce77d59199997420f161e80cbcb60e932cd895/crates/trie/src/hashed_cursor/post_state.rs#L155-L156

2024-01-26 10:17 UTC, rkrasiuk approved these changes

2024-01-26 10:33 UTC, merged