Example/custom payload builder
paradigmxyz/reth pull request #6269
Opened 2024-01-29 08:45 UTC by loocapro

Related to: #6219

Feedback:

The overall experience doesn't look bad. I am a bit struggling to understand if i want to implement a custom PayloadBuilder (that implements the PayloadBuilder trait) and pass it to the PayloadBuilderService, if I can do it.

Cc: @mattsse

2024-01-30 13:01 UTC, mattsse requested changes
I think this is helpful/useful

smol stylistic nit, I guess we can improve the ergonomics of the PayloadBuilder type a bit

2024-01-31 08:27 UTC, gakonst commented
Could see a trait that is like RethComponents to make the type situation easier with the generics

2024-02-01 12:26 UTC, mattsse approved these changes

2024-02-01 12:26 UTC, mattsse approved these changes

2024-02-01 12:36 UTC, merged