feat(snapshots): write Headers to snapshots during `HeaderStage`
paradigmxyz/reth pull request #6273
Opened 2024-01-29 12:10 UTC by joshieDo

Writes `Header`, `HeaderTD` and `HeaderHash` to static files during the `HeaderStage`.

Some necessary changes that might require a more careful look at
* genesis initialization takes a `ProviderFactory` equipped with a snapshot provider
* `sync_gap()` and the header downloader changes.

Tested holesky + sepolia  :heavy_check_mark:

2024-01-29 14:51 UTC, mattsse approved these changes
I think this is fairly readable, and I was able to follow along, tho I didn't review all checks in detail

pending @shekhirin

2024-01-29 14:51 UTC, mattsse commented on bin/reth/src/commands/import.rs
> +        init_genesis(provider_factory.clone())?;
this is better!!

2024-01-29 17:26 UTC, shekhirin approved these changes
LGTM, only not sure about the changes in `sync_gap` logic, as it's quite different now

2024-01-31 08:24 UTC, gakonst commented on crates/storage/provider/src/providers/database/provider.rs
> +        let target = match mode {
@mattsse @rkrasiuk ptal

2024-01-31 11:55 UTC, joshieDo commented on crates/node-core/src/init.rs
> +
not quite, there `stage drop` command calls this function with that expectation that it will just overwrite it

2024-01-31 12:04 UTC, joshieDo commented on crates/node-core/src/init.rs
> +    match factory.sealed_header(0) {
hm, im not sure i understand your question. here we check if what's in static files exists OR if it's the right one

2024-01-31 13:58 UTC, shekhirin commented on crates/node-core/src/init.rs
> +    match factory.sealed_header(0) {
we use only hash from the retrieved header, can we use `factory.block_hash(0)` instead, and match on `Ok(Some(hash)) => { ... }`? saves us retrieving the actual header

2024-01-31 20:42 UTC, joshieDo commented on crates/storage/provider/src/providers/snapshot/manager.rs
> +    pub fn get_with_snapshot_or_database<T, FS, FD>(
this a duplicate from another function which was part of `DatabaseProvider`, will dedup on a follow-up

2024-01-31 20:42 UTC, joshieDo commented on crates/storage/provider/src/providers/snapshot/manager.rs
> +    pub fn get_range_with_snapshot_or_database<T, P, FS, FD>(
this a duplicate from another function which was part of `DatabaseProvider`, will dedup on a follow-up

2024-01-31 21:19 UTC, joshieDo commented on crates/storage/provider/src/providers/database/mod.rs
> -
with static files, there's no long the possibility of having a gap where the tip is already in the database

2024-02-01 02:10 UTC, joshieDo commented
rfr, state tests are failing because they're getting canceled

2024-02-01 11:29 UTC, shekhirin commented on crates/stages/src/stages/headers.rs
> +            // // Append to HeaderTD
```suggestion
            // Append to Headers segment
```

2024-02-01 13:26 UTC, onbjerg requested changes

2024-02-02 15:15 UTC, joshieDo commented on crates/stages/src/stages/execution.rs
> +            provider.snapshot_provider().expect("should exist").clone(),
being removed in another PR: https://github.com/paradigmxyz/reth/pull/6344 it will no longer be an Option<_>

2024-02-02 15:15 UTC, joshieDo commented on crates/blockchain-tree/src/externals.rs
> +                self.provider_factory.snapshot_provider().expect("should exist");
being removed in another PR: https://github.com/paradigmxyz/reth/pull/6344 it will no longer be an Option<_>

2024-02-02 17:21 UTC, onbjerg approved these changes
lgtm given expects are going away in a sep pr

2024-02-05 15:57 UTC, merged