init
paradigmxyz/reth pull request #6305
Opened 2024-01-31 10:31 UTC by leontiad

2024-01-31 22:13 UTC, allnil commented on crates/rpc/rpc/src/eth/filter.rs
> +            return Ok(all_logs);
Hey! 
small nit: I think that the idiomatic way in Rust and across the repo is not to add ";" in return statements 
maybe you have some auto-fmt tooling that put ";" after returns
I got such problems a few times in my rust setup
Try to use "cargo +nightly fmt" , it helps!
ps
cargo clippy --bin "reth" --workspace --features "ethereum" --lib --tests --benches --examples
and this one to check lints

2024-02-16 01:16 UTC, gakonst commented
@leontiad what's missing for us to take a look?

2024-02-16 01:21 UTC, mattsse commented
ah my bad, this one slipped through

going over this asap

2024-02-16 19:20 UTC, leontiad commented
> @leontiad thanks for taking the time here! what's missing for us to take a look?

I am having an issue with  http::test_call_filter_functions_http test

2024-02-19 13:57 UTC, leontiad commented
Overall thank you for the support ! As a generic comment as a first contributor I was confused on what local tests/fmt/clippy I need to run before pushing and open the PR. Unless I miss it and is already there a one command line unifying all clippy/formatter/tests would really help.

2024-02-19 18:12 UTC, Rjected commented
> Overall thank you for the support ! As a generic comment as a first contributor I was confused on what local tests/fmt/clippy I need to run before pushing and open the PR. Unless I miss it and is already there a one command line unifying all clippy/formatter/tests would really help.

you can actually run `make lint` to run the clippy / formatter. For tests I usually just test things close to what I'm editing, but if you want something universal (although it may take longer), you can use `make test-unit` or `cargo nextest run --workspace`

2024-02-21 10:28 UTC, leontiad commented
> > Overall thank you for the support ! As a generic comment as a first contributor I was confused on what local tests/fmt/clippy I need to run before pushing and open the PR. Unless I miss it and is already there a one command line unifying all clippy/formatter/tests would really help.
> 
> you can actually run `make lint` to run the clippy / formatter. For tests I usually just test things close to what I'm editing, but if you want something universal (although it may take longer), you can use `make test-unit` or `cargo nextest run --workspace`

thanks, I need some help with a failing test. Can someone have a look @mattsse

2024-02-21 12:31 UTC, mattsse requested changes
very sorry for the delayed review here -.-

this is going in the right direction and is pretty close.

I only have one suggestion to get rid of the block_hash and latest lookup, by reusing the previously fetched `ChainInfo` object

2024-02-21 12:31 UTC, mattsse commented on crates/rpc/rpc/src/eth/filter.rs
>          trace!(target: "rpc::eth::filter", from=from_block, to=to_block, ?filter, "finding logs in range");
we can simplify this a bit more:

this function is always called after fetching the `ChainInfo`:

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/filter.rs#L372-L372

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/filter.rs#L134-L134

so we can use this as an argument to this function

then check if `to_block == from_block == info.best_number`

2024-02-23 11:42 UTC, mattsse requested changes

2024-02-23 11:42 UTC, mattsse commented on crates/rpc/rpc/src/eth/filter.rs
> +        let best_number = info.best_number;
hmm, I believe we can pass `ChainInfo` as an additional argument to the function because we should already have this when we call this function.

2024-02-23 11:42 UTC, mattsse commented on crates/rpc/rpc/src/eth/filter.rs
> +                .ok_or(ProviderError::BlockNotFound(header.number.into()))?;
this is now no longer necessary because the chaininfo also has the block_hash

2024-02-25 12:24 UTC, mattsse approved these changes
nice!

tysm!

2024-02-25 12:44 UTC, merged

2024-02-26 21:38 UTC, gakonst commented
🚀 🚀 🚀