Fix bug, rebuffer hashes that were received over broadcast
paradigmxyz/reth pull request #6316
Opened 2024-01-31 23:00 UTC by emhane

closes https://github.com/paradigmxyz/reth/issues/6315 which panicked in debug mode thanks to `debug_assert`.

2024-02-01 12:52 UTC, mattsse requested changes

2024-02-01 14:50 UTC, emhane commented on crates/net/network/src/transactions/fetcher.rs
>              let Some((retries, peers)) = self.unknown_hashes.get(&hash) else { return };
actually I meant to only call that in `buffer_hashes_for_retry`. had reset the commit but looks like it got added anyhow.

2024-02-01 18:02 UTC, mattsse commented on crates/net/network/src/transactions/fetcher.rs
>          self.buffer_hashes(hashes, None)
we're still checking the unknown hashes map twice, 

why are we doing this instead of skipping the None case in L265 ?

2024-02-05 11:42 UTC, mattsse approved these changes
lgtm

2024-02-05 11:55 UTC, merged