p2p example
paradigmxyz/reth pull request #6349
Opened 2024-02-02 15:12 UTC by loocapro

Related to #6127

Added an example that establishes p2p sessions with polygon peers.

Credits: https://blog.merkle.io/blog/fastest-transaction-network-eth-polygon-bsc

2024-02-02 18:15 UTC, mattsse requested changes
nice, a few nits

I'd also like to setup the txs manager, see other example so we can get polygon txs

2024-02-02 18:15 UTC, mattsse commented on examples/polygon-p2p/src/chain_cfg.rs
> +pub(crate) fn chain_spec() -> Arc<ChainSpec> {
```suggestion
pub(crate) fn polygon_chain_spec() -> Arc<ChainSpec> {
```

2024-02-02 18:15 UTC, mattsse commented on examples/polygon-p2p/src/main.rs
> +
```suggestion
```

2024-02-02 18:15 UTC, mattsse commented on examples/polygon-p2p/src/main.rs
> +        .build(NoopProvider::default());
I think we want a helper function for this in a followup `build_with_noop_provider`

https://github.com/paradigmxyz/reth/blob/30aa3e6792701a8719a49995d79a0525bfc33881/crates/net/network/src/config.rs#L421-L421

the provider in p2p isn't that useful to begin with

2024-02-04 15:15 UTC, closed without merging

2024-02-15 12:55 UTC, emhane commented
reason for closing this @loocapro ?

2024-02-15 14:28 UTC, loocapro commented
> reason for closing this @loocapro ?

its already merged here: https://github.com/paradigmxyz/reth/pull/6393