chore(rpc-types-compat): use SealedBlock.raw_transactions to reduce deplicate
paradigmxyz/reth pull request #6406
Opened 2024-02-05 14:56 UTC by jsvisa

Seems the `SealedBlock.body` is used in the v1,v2,v3 payload builder, use a helper function to reduce the same logic.

2024-02-05 16:24 UTC, Rjected requested changes, later dismissed
just a few style nits, otherwise I like removing the code dup

2024-02-05 16:24 UTC, Rjected commented on crates/primitives/src/block.rs
> +    /// Returns a vector of raw formated transactions.
```suggestion
    /// Returns a vector of transactions RLP encoded with [TransactionSigned::encode_enveloped].
```

2024-02-05 16:24 UTC, Rjected commented on crates/primitives/src/block.rs
> +                encoded.into()
can use `envelope_encoded` here

2024-02-05 20:54 UTC, Rjected commented
this also needs a rebase to fix the test failures

2024-02-06 12:46 UTC, mattsse approved these changes
lgtm

2024-02-06 15:40 UTC, merged