Drop lock on listener as early as possible
paradigmxyz/reth pull request #6414
Opened 2024-02-05 17:23 UTC by emhane

Releases a write lock in tx pool as early as possible.

2024-02-05 17:27 UTC, Rjected approved these changes
nice, lgtm

2024-02-05 18:01 UTC, mattsse requested changes

2024-02-05 18:01 UTC, mattsse commented on crates/transaction-pool/src/pool/mod.rs
> +        drop(listener);
pedantic style nit:
this should be in its own scope `{}` se we don't need to call drop

2024-02-06 08:11 UTC, onbjerg approved these changes

2024-02-06 12:37 UTC, mattsse approved these changes

2024-02-06 12:51 UTC, merged