Payload Events
paradigmxyz/reth pull request #6549
Opened 2024-02-11 16:35 UTC by loocapro

Related to: https://github.com/paradigmxyz/reth/issues/6507

Added `PayloadEvents` and sending events on payload attributes and payload resolve.

@mattsse what should be the right way to send the ResolvePayloadFuture from the broadcast::Sender?

2024-02-12 13:44 UTC, mattsse requested changes
I see that we're returning a `PayloadFuture`:

https://github.com/paradigmxyz/reth/blob/17eca361e8951362f5c544a2dfe20c9b046bef5f/crates/payload/builder/src/service.rs#L24-L24

what we could do is write our own future type here that also gets a clone of the sender and sends it once resolved or keep using box by extending the async scope:

https://github.com/paradigmxyz/reth/blob/17eca361e8951362f5c544a2dfe20c9b046bef5f/crates/payload/builder/src/service.rs#L287-L291

with an update

```rust
let broadcast = self.broadcast.clone();
```



I also want a helper struct for the Subscription so it's easier to get a stream of PayloadAttributes or Payloads

2024-02-12 16:27 UTC, mattsse requested changes

2024-02-12 16:27 UTC, mattsse commented on crates/payload/builder/src/service.rs
> +    pub fn subscribe(&self) -> oneshot::Receiver<broadcast::Receiver<PayloadEvents<Engine>>> {
I want a wrapper struct for `broadcast::Receiver` here so we can easily add more functions, for example to get a stream of PayloadAttr

2024-02-12 16:27 UTC, mattsse commented on crates/payload/builder/src/traits.rs
> +    type BuiltPayload: BuiltPayload + Clone + std::fmt::Debug;
I think this is reasonable bound, shouldn't impact anything.

and I don't think the clone is that expensive

2024-02-12 16:27 UTC, mattsse commented on crates/payload/builder/src/service.rs
>  }
this needs some docs

2024-02-13 11:31 UTC, mattsse requested changes
last nits

2024-02-13 11:31 UTC, mattsse commented on crates/payload/builder/src/service.rs
> +pub struct PayloadEventReceiver<Engine: EngineTypes> {
```suggestion
pub struct PayloadEvents<Engine: EngineTypes> {
```

2024-02-13 11:31 UTC, mattsse commented on crates/payload/builder/src/service.rs
> +pub struct PayloadEventReceiver<Engine: EngineTypes> {
I want to move this to a new file events.rs

2024-02-13 11:31 UTC, mattsse commented on crates/payload/builder/src/service.rs
> +pub struct PayloadEventReceiver<Engine: EngineTypes> {
this should expose an async function to recv

2024-02-13 13:38 UTC, onbjerg approved these changes

2024-02-13 14:43 UTC, mattsse approved these changes
lgtm

2024-02-13 14:53 UTC, merged