enhance tx gossip test coverage
paradigmxyz/reth pull request #6578
Opened 2024-02-13 11:09 UTC by i-m-aditya

Fixes #6501
- [x] Check that bad transactions are rejected
- [x] Test peer penalization when blob txs(EIP-4844 Blob tx) are gossiped
- [x] Add helper functions for TransactionGenerator.

2024-02-13 12:45 UTC, emhane requested changes
lgtm, appreciate that you moved as much of the reusable test rigging code as possible out into methods

2024-02-13 14:22 UTC, i-m-aditya commented on crates/net/network/tests/it/txgossip.rs
> +    }
Cool

2024-02-13 15:17 UTC, emhane requested changes
didn't quite get why there was a 15 second time out at first, it's unnecessarily long to pause 15 seconds in ci, but yes, we need to give the test rig some time to send the tx, you were right. a second should do.

2024-02-13 15:17 UTC, emhane commented on crates/net/network/tests/it/txgossip.rs
> +
```suggestion
tokio::time::sleep(Duration::from_secs(1)).await;
```

I see why there was a time out now. inserting a short sleep should make sure that any item is received that was sent. think 1 second is enough, no need for 15 seconds.

2024-02-13 15:17 UTC, emhane commented on crates/net/network/tests/it/txgossip.rs
> +
```suggestion

tokio::time::sleep(Duration::from_secs(1)).await;
```

same here

2024-02-14 17:04 UTC, emhane requested changes

2024-02-14 17:04 UTC, emhane commented on crates/net/network/tests/it/txgossip.rs
> +    let received = peer1_tx_listener.recv().await.unwrap();
```suggestion

    let received = peer1_tx_listener.recv().await.unwrap();
```

here the sleep isn't necessary since the `await` syntax is used

2024-02-16 04:32 UTC, emhane approved these changes

2024-02-16 04:41 UTC, merged