fix: check versioned hash version for EIP-4844 transactions
paradigmxyz/reth pull request #6601
Opened 2024-02-14 01:42 UTC by jtraglia

I didn't see where the versioned hash's version was checked for EIP-4844 transactions. This PR adds this check. I don't believe this is a big deal though because the CL should also check this.

Here's the spec for this:
* https://eips.ethereum.org/EIPS/eip-4844#execution-layer-validation

This part in particular:
```python
# all versioned blob hashes must start with VERSIONED_HASH_VERSION_KZG
for h in tx.blob_versioned_hashes:
    assert h[0] == VERSIONED_HASH_VERSION_KZG
```

2024-02-14 01:47 UTC, Rjected commented
it should be checked here, although implicitly by recalculating the versioned hash
https://github.com/paradigmxyz/reth/blob/1cc52ff73cbe268e863434ee3eb8c646787831bf/crates/primitives/src/transaction/eip4844.rs#L147-L150

the error type is useful though, see the TODO in the above snippet

2024-02-14 02:00 UTC, jtraglia commented
Oh I see, thanks! Would it be worth keeping both checks? How should I proceed?

You're welcome to modify this PR how you see fit btw.

2024-02-14 02:33 UTC, Rjected requested changes
I think the way forward would be to create a new `BlobTransactionValidationError` variant that describes a mismatched versioned hash, and change this to return that variant
https://github.com/paradigmxyz/reth/blob/1cc52ff73cbe268e863434ee3eb8c646787831bf/crates/primitives/src/transaction/eip4844.rs#L149

2024-02-14 02:33 UTC, Rjected commented on crates/transaction-pool/src/validate/eth.rs
> +            }
would remove this

2024-02-14 02:33 UTC, Rjected commented on crates/transaction-pool/src/error.rs
> +    },
would create a new variant here instead
https://github.com/paradigmxyz/reth/blob/1cc52ff73cbe268e863434ee3eb8c646787831bf/crates/primitives/src/transaction/sidecar.rs#L30

2024-02-14 02:35 UTC, Rjected commented
adding a link to the spec, or even quoting the spec code verbatim around those lines would be useful as an artifact of this

2024-02-14 02:40 UTC, jtraglia commented
Sounds good. I'll make this change tomorrow.

2024-02-15 15:11 UTC, jtraglia commented
Should be ready now!

2024-02-15 17:15 UTC, Rjected approved these changes
awesome, this looks good to me, thanks!

2024-02-15 17:26 UTC, merged