Fix(rpc) Effective gas_price for simulations
paradigmxyz/reth pull request #6722
Opened 2024-02-21 17:31 UTC by AtomicAzzaz

Atm there is no consideration of max_priority_fee_per_gas to compute the effective gas price of a tx in RPC simulations. I was able to find a transaction that landed on mainnet but reverts when simulated via RPC. This should fix it.

Regarding the comment "If no `gasPrice` or `maxFeePerGas` is set, then the `gas_price` in the returned `gas_price` will be `0`"; I deleted it since it wasn't true: `let max_fee = max_fee_per_gas.unwrap_or(block_base_fee);`

If that's actually the behaviour wanted lmk

2024-02-21 17:44 UTC, AtomicAzzaz commented
On this commit 
`block_base_fee` + `max_priority_fee_per_gas`
may overflow. I'm not sure if I should return an error or use saturating add. Lmk

2024-02-22 09:54 UTC, mattsse requested changes
this is great!

ty

smol nits

and I'd appreciate an addtional test for this

2024-02-22 09:54 UTC, mattsse commented on crates/rpc/rpc/src/eth/revm_utils.rs
> +        fn get_effective_gas_price(
please add docs

2024-02-22 09:54 UTC, mattsse commented on crates/rpc/rpc/src/eth/revm_utils.rs
> +                None => Ok(block_base_fee + max_priority_fee_per_gas.unwrap_or(U256::ZERO)),
these need checked math,
we should treat these as errors

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/error.rs#L299-L304

2024-02-22 12:28 UTC, mattsse approved these changes
lgtm

2024-02-22 12:39 UTC, merged