feat(storage): rename tables
paradigmxyz/reth pull request #6787
Opened 2024-02-26 11:10 UTC by shekhirin

2024-02-26 13:50 UTC, joshieDo approved these changes

2024-02-26 14:04 UTC, onbjerg approved these changes

2024-02-26 15:57 UTC, mattsse approved these changes

2024-02-26 16:43 UTC, emhane requested changes
super clean, very helpful descriptive names. a lot of work though, this is why it's nice to just do proper names from the start.

comments (not caught by rustdocs) seem to check out with new naming, good!

2024-02-26 16:43 UTC, emhane commented on crates/stages/src/stages/sender_recovery.rs
> +        /// [tables::TransactionSenders] is    not empty.
```suggestion
        /// [tables::TransactionSenders] is not empty.
```

2024-02-26 16:43 UTC, emhane commented on crates/storage/provider/src/providers/database/metrics.rs
> +    InsertTransactionHashNumberss,
```suggestion
    InsertTransactionHashNumbers,
```

2024-02-26 16:43 UTC, emhane commented on crates/stages/src/stages/sender_recovery.rs
>      /// recover signer for each transaction and store entries in
```suggestion
    /// collect transactions within that range, recover signer
    /// for each transaction and store entries in
```

2024-02-27 00:09 UTC, emhane approved these changes

2024-02-27 00:09 UTC, merged