restrict max concurrent outbound dials
paradigmxyz/reth pull request #6860
Opened 2024-02-28 22:02 UTC by abhijeetbhagat

related to #6778

2024-02-28 22:09 UTC, mattsse requested changes
this looks pretty good!
I believe this is already complete.

I'd like to have another test case that adds a few peers
* starts all allowed pendingOut (until max_concurrent is satisfied)
* calls on_active_outgoing_established 
ensures peers are now `::Out` and counters are as expected

2024-02-28 22:09 UTC, mattsse commented on crates/net/network/src/peers/manager.rs
> +    pub(crate) fn on_active_session_established(&mut self, peer_id: PeerId) {
this should include `_outgoing_`

2024-02-28 22:09 UTC, mattsse commented on crates/net/network/src/peers/manager.rs
> +    num_pendingout: usize,
please move to the other counters and add serde(skip)

2024-02-29 23:15 UTC, abhijeetbhagat commented
@mattsse can you please check if the test case looks good?

2024-03-01 09:01 UTC, mattsse requested changes
last test nit

2024-03-01 09:01 UTC, mattsse commented on crates/net/network/src/peers/manager.rs
> +    }
this looks good,
I'd like to also test the emitted events by polling the peer manager, see other tests for examples

2024-03-02 23:32 UTC, abhijeetbhagat commented
@mattsse please check.

2024-03-04 17:29 UTC, abhijeetbhagat commented
@mattsse please check

2024-03-04 17:31 UTC, mattsse approved these changes
lgtm!

ty!

2024-03-04 17:44 UTC, merged