Return fetch error on response that fails verification or validation
paradigmxyz/reth pull request #6864
Opened 2024-02-28 22:43 UTC by emhane

Related https://github.com/paradigmxyz/reth/pull/6863.

Returns `FetchEvent::Error` variant if no txns left in `PooledTransactions` response after verification + validation.

2024-02-28 22:52 UTC, mattsse reviewed
this results in penalization, right?

this also happens, when a peer sends us an empty response?
we can't penalize this because this is a valid response that could just mean: the peer doesn't have any of the requested transactions

2024-02-28 22:52 UTC, mattsse commented on crates/net/network/src/transactions/fetcher.rs
> +                if verified_payload.is_empty() {
can we add a note here on when this happens?

2024-02-29 00:18 UTC, emhane commented
> this results in penalization, right?
> 
no not yet, it should eventually, issue linked in code comment
> this also happens, when a peer sends us an empty response? we can't penalize this because this is a valid response that could just mean: the peer doesn't have any of the requested transactions

empty response means the peer doesn't have the transactions?...but it should if it announced them...is this by spec or?

2024-02-29 13:40 UTC, mattsse commented
> empty response means the peer doesn't have the transactions?...but it should if it announced them...is this by spec or?

>> It is permissible to first announce a transaction via NewPooledTransactionHashes, but then to refuse serving it via PooledTransactions. This situation can arise when the transaction is included in a block (and removed from the pool) in between the announcement and the request.

>> A peer may respond with an empty list iff none of the hashes match transactions in its pool.

> update: in either case is a fetch event error, will make a new one ResponseEmpty "peer didn't serve txns it announced"

that sounds reasonable

2024-03-01 15:29 UTC, emhane commented
re-request review @mattsse

2024-03-01 16:19 UTC, mattsse requested changes

2024-03-02 15:31 UTC, mattsse approved these changes
lgtm,

pending restored error.rs

2024-03-02 15:31 UTC, mattsse commented on crates/interfaces/src/p2p/error.rs
> +                RequestError::UnsupportedCapability |
please undo changes

2024-03-02 23:38 UTC, emhane commented on crates/interfaces/src/p2p/error.rs
> +                RequestError::UnsupportedCapability |
oops, thanks

2024-03-03 14:41 UTC, merged