0x/act ts
paradigmxyz/reth pull request #6865
Opened 2024-02-28 23:15 UTC by justcode740

2024-02-29 00:45 UTC, justcode740 commented
the fmt seem even fail on current main, wonder what's the cause? @mattsse

2024-02-29 06:31 UTC, justcode740 commented
> the fmt seem even fail on current main, wonder what's the cause? @mattsse

nvm resolved @gakonst is a busy guy so could you help review this? there's todo i left in the code to see your opinion.

2024-02-29 10:34 UTC, mattsse requested changes
this is great!

a few more nits

2024-02-29 10:34 UTC, mattsse commented on crates/ethereum-forks/src/hardfork.rs
> +            }
we can remove this

2024-02-29 10:34 UTC, mattsse commented on crates/ethereum-forks/src/hardfork.rs
> +        }
this can be moved into a new scope that has the cfg

2024-02-29 10:34 UTC, mattsse commented on crates/ethereum-forks/src/hardfork.rs
> +                           * for each chain */
right, I'd like to use an exhaustive match here

2024-02-29 10:34 UTC, mattsse commented on crates/ethereum-forks/src/hardfork.rs
> +            _ => Some(0),
same

2024-02-29 10:34 UTC, mattsse commented on crates/ethereum-forks/src/hardfork.rs
> +        }
same

2024-02-29 10:34 UTC, mattsse commented on crates/ethereum-forks/src/hardfork.rs
> +            _ => Some(0),
this should use the timestamp of the first block

2024-03-01 11:41 UTC, mattsse approved these changes
thanks this is great!

2024-03-01 12:02 UTC, merged