bound hashes inflight and pending fetch size
paradigmxyz/reth pull request #6877
Opened 2024-02-29 12:12 UTC by int88

fixes: #6801

2024-02-29 15:17 UTC, Rjected requested changes
one very pedantic nit, otherwise this looks good to me

2024-02-29 15:17 UTC, Rjected commented on crates/net/network/src/transactions/fetcher.rs
> +                DEFAULT_MAX_CAPACITY_CACHE_INFLIGHT_AND_PENDING_FETCH.try_into().unwrap(),
Let's use an `expect` here with a message like the above `expect`

2024-02-29 20:46 UTC, emhane approved these changes
nice!

2024-02-29 20:46 UTC, emhane commented on crates/net/network/src/transactions/constants.rs
> +    /// 65 requests, so it is 25665.
```suggestion
    /// 65 requests, so it is 25665 hashes.
```

2024-03-01 01:58 UTC, Rjected approved these changes
looks good, thanks!

2024-03-01 02:09 UTC, merged