chore: update cargo deny to handle deprecated config entries
paradigmxyz/reth pull request #6980
Opened 2024-03-05 22:13 UTC by TomAFrench

A bunch of the [cargo deny config has been deprecated](https://github.com/EmbarkStudios/cargo-deny/pull/606) so this PR updates to target the new spec.

I don't know if you want to blanket accept MPL2.0 so I've just added exceptions for the current dependencies.

2024-03-05 22:14 UTC, TomAFrench commented on deny.toml
> +    # These dependencies are grandfathered in in https://github.com/paradigmxyz/reth/pull/#
```suggestion
    # These dependencies are grandfathered in in https://github.com/paradigmxyz/reth/pull/6980
```

2024-03-05 23:12 UTC, DaniPopes requested changes

2024-03-05 23:12 UTC, DaniPopes commented on deny.toml
> -    "LicenseRef-webpki",
Please also remove the clarify below

2024-03-05 23:12 UTC, DaniPopes commented on deny.toml
> +
```suggestion
```

2024-03-06 01:13 UTC, TomAFrench commented on deny.toml
> -    "LicenseRef-webpki",
Thanks, done now.

2024-03-06 01:33 UTC, DaniPopes approved these changes
Thanks!

2024-03-06 01:45 UTC, merged