reth/dump: setup db assert from,to block of wrong msg
paradigmxyz/reth pull request #7093
Opened 2024-03-11 09:54 UTC by jsvisa

`from` can be equal to `to`

2024-03-11 14:35 UTC, onbjerg requested changes

2024-03-11 14:35 UTC, onbjerg commented on bin/reth/src/commands/stage/dump/mod.rs
> +    assert!(from < to, "FROM block should not smaller than TO block.");
```suggestion
    assert!(from < to, "FROM block should not be smaller than TO block.");
```

2024-03-13 08:45 UTC, rkrasiuk requested changes
otherwise the semantics do not change 🤷‍♂️

2024-03-13 08:45 UTC, rkrasiuk commented on bin/reth/src/commands/stage/dump/mod.rs
> +    assert!(from < to, "FROM block should not be smaller than TO block.");
```suggestion
    assert!(from < to, "FROM block should be smaller than TO block.");
```

2024-04-12 01:48 UTC, closed without merging