feat: Extend fork activation blocks data with Arbitrum data
paradigmxyz/reth pull request #7178
Opened 2024-03-16 19:00 UTC by altugbakan

Fixes #7098 

This PR aims to extend fork activations block data with Arbitrum hard fork values. Since Arbitrum upgrades happen on a timestamp-based manner, the first block on the update timestamp is supplied as the block value. ArbOS 11 is the upgrade for including Shanghai, and ArbOS 20 is the upgrade for including Cancun.

I've found some irregularities between the provided timestamps and the on-chain data, but my questions to the Arbitrum team was not answered, so I went with the provided dates by the Arbitrum foundation.

I have put these values behind a feature flag called "arbitrum", please let me know if this is not needed.

The provided update timestamps can be found in https://docs.arbitrum.foundation/network-upgrades#network-activation-statuses.

2024-03-16 20:57 UTC, gakonst commented
We don't support Arbitrum yet so not sure we should include this?

2024-03-18 19:42 UTC, mattsse reviewed
thanks for this!

I need to figure out how to abstract away the cfgs, this is kinda related to revm evm setup

need to think about this a bit

2024-03-19 14:48 UTC, mattsse requested changes
okay, I thought about this a bit,

I don't want to introduce new arb hardfork variants and features the op hardforks are bad enough.

instead we should convert them into comments and only keep the regular eth hardforks in the match stmt

2024-03-19 14:48 UTC, mattsse commented on crates/ethereum-forks/src/hardfork.rs
> +    ArbOS20Atlas,
I'd like to not add these and instead add these as a comment that these exists on arbitrum

2024-03-19 14:48 UTC, mattsse commented on crates/ethereum-forks/src/hardfork.rs
> +            Hardfork::ArbOS20Atlas => Some(18683405),
we can keep arb hardforks as comment

2024-03-19 21:44 UTC, altugbakan commented
Hey! I've updated the PR, but is it as you requested? Should I comment out all code about Arbitrum or not?

2024-03-23 09:37 UTC, mattsse approved these changes

2024-03-23 10:03 UTC, mattsse commented
thanks, I resolved the conflicts and merged in #7305 

wasn't able to push to your main directly

2024-03-23 10:03 UTC, closed without merging