Update database_args.rs to enable nfs support with flag
paradigmxyz/reth pull request #7346
Opened 2024-03-26 22:11 UTC by argakiig

The purpose of this PR is to further extend https://github.com/paradigmxyz/reth/pull/6755/ and allow for 
`--db.exclusive=true` to be used to support nfs volumes

2024-03-27 03:34 UTC, onbjerg reviewed
Please also update the command help in the book: https://github.com/paradigmxyz/reth/tree/main/book/cli/reth

2024-03-27 15:03 UTC, shekhirin commented on crates/node-core/src/args/database_args.rs
> +    /// Open environment in exclusive/monopolistic mode. Enabling allows nfs volumes
```suggestion
    /// Open environment in exclusive/monopolistic mode. Makes it possible to open a database on an NFS volume.
```

2024-03-27 15:03 UTC, shekhirin commented on book/cli/reth/node.md
> +
This can be generated with `make update-book-cli`, the description of the argument should match the rustdoc comment.

2024-03-28 13:20 UTC, mattsse approved these changes
pending @shekhirin

2024-03-28 14:20 UTC, shekhirin approved these changes

2024-03-28 14:21 UTC, shekhirin requested changes
.

2024-03-28 15:23 UTC, argakiig commented on crates/node-core/src/args/database_args.rs
> +    #[arg(long = "db.exclusive", exclusive = false)]
Ah OK that makes sense. Thanks for the link to the docs as well. Change incoming

2024-03-28 17:41 UTC, shekhirin approved these changes
LGTM, thanks!

2024-03-28 18:00 UTC, merged