feature: eth-wire types standalone crate
paradigmxyz/reth pull request #7373
Opened 2024-03-28 12:31 UTC by JackG-eth

close #6959 

move eth-wire types to its own standalone crate to reduce the size of reth-interface crate.

2024-03-28 12:33 UTC, mattsse requested changes
great start

2024-03-28 12:33 UTC, mattsse commented on crates/net/eth-wire-types/src/lib.rs
> +//! Types for the eth wire protocol.
this needs the regular header

like this:

https://github.com/paradigmxyz/reth/blob/33c466d88c4bee67f0b4eb15b2ca1b2fc421b10b/crates/net/nat/src/lib.rs#L7-L12

2024-03-28 16:57 UTC, JackG-eth commented
@mattsse I think it can be reviewed, will clean up linting/doc issues.

1 thing, maybe my lack of knowledge but i can swap the interface dependency to types due to optimism = ["reth-eth-wire/optimism"]

2024-04-01 16:54 UTC, mattsse approved these changes
lgtm

pending @Rjected

2024-04-01 17:18 UTC, Rjected approved these changes
looks good to me, thanks!

2024-04-01 17:39 UTC, merged