feat: make more descriptive errors instead of ProviderError
paradigmxyz/reth pull request #7380
Opened 2024-03-28 16:18 UTC by allnil

#7359
@Rjected 
I found places where BlockExecutionError::ProviderError was used and tried to add more specific errors
waiting for your feedback

2024-03-28 17:44 UTC, Rjected requested changes
We should see if there is another error variant that already exists in the error enum returned by these methods, which would be appropriate instead of introducing these variants. For example, we already have an error in the fetch before the state root - mapping to a string makes this opaque to higher levels of error handling (even though it's human readable).

2024-03-30 15:16 UTC, allnil commented
@Rjected 
Hi!
I've slightly refactored the code and hope it's better now. :)
I added `LatestBlock` error to `BlockExecution` error enum which wraps `ProviderError` and used it in both places where we attempt to retrieve the latest block state during the block execution phase.
Additionally, I discovered how the account cache error is handled in OptimismBuilder  and copied the AccountLoadFailed error from there.

2024-03-30 15:44 UTC, allnil commented
and error types grew in size

2024-04-01 19:15 UTC, Rjected requested changes
nice, just one wording nit

2024-04-01 19:15 UTC, Rjected commented on crates/interfaces/src/executor.rs
> +    /// Error when fetch latest block state.
```suggestion
    /// Error when fetching latest block state.
```

2024-04-01 20:10 UTC, Rjected approved these changes
lgtm, thanks!

2024-04-02 12:01 UTC, mattsse approved these changes

2024-04-02 12:09 UTC, merged