feat(cli): add more convenient SocketAddr argument parsing
paradigmxyz/reth pull request #757
Opened 2023-01-06 19:50 UTC by lambdaclass-user

This PR adds custom parsing for the `metrics` CLI option. This enables domain name resolving, with a default of "localhost" in case of specifying only the port (both `:8080` and `8080` are translated to `localhost:8080`).

2023-01-06 20:01 UTC, MegaRedHand commented
I used a function for the parsing, although i'm not sure if using `TypedValueParser` has any advantages. @mattsse What do you think?
Also, should we add some default port? For example, in case of something like this:
```bash
$ reth node --metrics localhost:
```

2023-01-06 20:33 UTC, mattsse requested changes
this looks great, using a function is fine!

would love to see a simple test for the supported variants.

2023-01-06 20:35 UTC, mattsse commented
> Also, should we add some default port?

great idea, but I'm not sure what the default port should be @onbjerg ?

2023-01-06 21:42 UTC, MegaRedHand commented
Tests added! Also implemented the default port with a value of `9000` (the default for the _prometheus_ endpoint) for now.

2023-01-07 00:28 UTC, gakonst approved these changes

2023-01-07 00:28 UTC, merged