replace basefeeparams with alloy
paradigmxyz/reth pull request #7586
Opened 2024-04-12 03:46 UTC by rodrigoherrerai

first draft on [7530](https://github.com/paradigmxyz/reth/issues/7530)

@mattsse just to see if it is going in the right direction.

2024-04-12 10:53 UTC, mattsse requested changes
great!

one suggestion to convert the trait into constants

2024-04-12 10:53 UTC, mattsse commented on crates/primitives/src/chain/spec.rs
> +impl OptimismBaseFeeParams for BaseFeeParams {
we only use this inside this file, so I'd rather have constants for this:

`const OP_SEPOLIA_BASEFEE_PRARAMs = ...`

2024-04-12 21:59 UTC, rodrigoherrerai commented
@mattsse modified the trait to constants

2024-04-13 04:14 UTC, mattsse requested changes
great!

needs rebase.

I'm unable to make modifications because this pr was opened from main branch, please open future prs from a dedicated branch

2024-04-13 05:30 UTC, rodrigoherrerai commented
@mattsse should I open a new pr with a dedicated branch?

2024-04-13 06:27 UTC, mattsse commented
that'd would be preferred yes :)

2024-04-13 06:56 UTC, closed without merging