fix: add discv5 config to p2p cmd
paradigmxyz/reth pull request #7662
Opened 2024-04-15 20:42 UTC by joshieDo

Adds missing discv5 config and bootnodes to NetworkConfig on p2p command.

2024-04-15 21:24 UTC, Rjected approved these changes
lgtm

2024-04-15 21:27 UTC, mattsse requested changes

2024-04-15 21:27 UTC, mattsse commented on bin/reth/src/commands/p2p/mod.rs
> +            })
this should check if discv5 should be enabled `enable_discv5_discovery`

2024-04-17 14:44 UTC, mattsse approved these changes

2024-04-17 14:57 UTC, merged