feat(op): signature encoding
paradigmxyz/reth pull request #7769
Opened 2024-04-20 03:20 UTC by emhane

Adds back support for encoding null signature, that was reverted in https://github.com/paradigmxyz/reth/pull/7724

2024-04-20 10:16 UTC, mattsse requested changes
do we need all of those or now just the v value special case? for != 27/28?

2024-04-20 14:47 UTC, emhane commented
> do we need all of those or now just the v value special case? for != 27/28?

yes we need all, I'm running import on branch https://github.com/paradigmxyz/reth/tree/emhane/mainnet-op, and have encountered both of those errors.

2024-04-20 15:23 UTC, rkrasiuk approved these changes

2024-04-20 15:23 UTC, rkrasiuk commented on crates/primitives/src/transaction/signature.rs
> +                if v == 0 && r == U256::ZERO && s == U256::ZERO {
nit
```suggestion
                if v == 0 && r.is_zero() && s.is_zero() {
```

2024-04-20 23:04 UTC, mattsse requested changes
this needs docs, why we're doing this

2024-04-22 10:04 UTC, mattsse approved these changes

2024-04-22 10:15 UTC, merged