add new crate op-beacon-core
paradigmxyz/reth pull request #7830
Opened 2024-04-23 21:41 UTC by rupam-04

Addresses #7648 

Would want some insights on the current work if I'm going in the right direction or not

2024-04-23 21:43 UTC, rupam-04 commented
Also I'd like to know what is causing the following error:

```
error: failed to load manifest for workspace member `/home/runner/work/reth/reth/crates/op-beacon-core`

Caused by:
  failed to parse manifest at `/home/runner/work/reth/reth/crates/op-beacon-core/Cargo.toml`

Caused by:
  error inheriting `reth-consensus-beacon-core` from workspace root manifest's `workspace.dependencies.reth-consensus-beacon-core`

Caused by:
  `dependency.reth-consensus-beacon-core` was not found in `workspace.dependencies`
```

2024-04-24 10:14 UTC, mattsse requested changes
this is a great first step,

I also wanto to move this to the `crates/optimism` folder

2024-04-24 10:14 UTC, mattsse commented on Cargo.toml
> +    "testing/ef-tests/", "crates/op-beacon-core",
these needs to be moved up to where other crates are defined

2024-04-24 10:14 UTC, mattsse commented on Cargo.toml
the crate also needs to be added here this should fix the error

https://github.com/paradigmxyz/reth/blob/86980836b8cc7e36ecf47400485f544cd2ffe2eb/Cargo.toml#L201-L201

2024-04-24 10:14 UTC, mattsse commented on crates/op-beacon-core/src/lib.rs
this needs the regular lib.rs header, see other crates for ref

2024-04-24 10:59 UTC, rupam-04 commented on Cargo.toml
Having some issues with this. I added both
```
reth-op-beacon-core = { path = "crates/optimism/op-beacon-core" }
reth-consensus-beacon-core = { path = "crates/consensus/beacon-core" }
``` to ```reth/Cargo.toml``` but there still seems to be some issues.

2024-04-24 11:11 UTC, rupam-04 commented on Cargo.toml
This is the error I get this time:

```
error: no matching package named `reth-consensus-beacon-core` found
location searched: /home/runner/work/reth/reth/crates/consensus/beacon-core
required by package `op-beacon-core v0.2.0-beta.6 (/home/runner/work/reth/reth/crates/optimism/op-beacon-core)`
```

2024-04-24 11:19 UTC, onbjerg commented on Cargo.toml
it's called reth-beacon-consensus-core, not reth-consensus-beacon-core

https://github.com/paradigmxyz/reth/blob/4f81f3acc9fdc56b18444c6754f852b7060c57ee/crates/consensus/beacon-core/Cargo.toml#L2

2024-04-24 11:20 UTC, onbjerg commented on crates/optimism/op-beacon-core/Cargo.toml
> +
```suggestion
```

nit

2024-04-24 11:20 UTC, onbjerg reviewed
also please run `cargo +nightly fmt --all`

2024-04-24 11:20 UTC, onbjerg commented on crates/optimism/op-beacon-core/src/lib.rs
> +//! Beacon consensus implementation
```suggestion
//! Optimism beacon consensus implementation
```

2024-04-24 16:19 UTC, rupam-04 commented
Few conflicts due to the changed file location of ```crates/interfaces/src/consensus.rs``` probably due to #7813 @mattsse

2024-04-24 18:14 UTC, closed without merging

2024-04-24 18:48 UTC, rupam-04 commented
> Hey @rupam-04 it seems you accidentally force pushed main onto the branch, so the PR auto closed. Feel free to re-open a PR for this

Yeah it had some conflicts, I reopened a PR