feat: introduce external context generic in EvmConfig
paradigmxyz/reth pull request #7842
Opened 2024-04-24 15:59 UTC by Rjected

WIP, need to replace all `evm_with_env(&mut self.state, env, ());` unit types and replace with a generic

2024-04-24 16:03 UTC, mattsse requested changes
all of this is very bad,

it should not be necessary to always provide a unit context

2024-04-24 16:27 UTC, Rjected commented
> all of this is very bad,
> 
> it should not be necessary to always provide a unit context

I guess this should be a new method then?

2024-04-24 21:19 UTC, Rjected commented
maybe we should allow the user to configure the external context when implementing the trait:
```rust
pub trait ConfigureEvm {
    /// Default external context configured for non-inspector related operations
    type DefaultExternalContext;

    fn base_evm<'a>(&self) -> EvmBuilder<'a, SetGenericStage, Self::DefaultExternalContext, EmptyDB> {
        // default behavior is default evm, implementors can include external context
        EvmBuilder::default()
    }
```

the non inspector methods would then use this method before setting the db, wdyt @mattsse

2024-04-24 21:52 UTC, DaniPopes commented
I was thinking more a context that is a GAT on the trait, and is provided by the implementor in fn evm, and then all other methods build off of the return of fn evm.

2024-04-24 22:07 UTC, mattsse commented
can't return evmbuilder because its signature is not publicly accessible

2024-04-24 22:16 UTC, Rjected commented
> I was thinking more a context that is a GAT on the trait, and is provided by the implementor in fn evm, and then all other methods build off of the return of fn evm.

ah i see, that makes sense

2024-04-24 22:25 UTC, DaniPopes commented
> can't return evmbuilder because its signature is not publicly accessible

Evm can be converted back to EvmBuilder with [`modify`](https://docs.rs/revm/latest/revm/struct.Evm.html#method.modify)

2024-04-29 17:11 UTC, Rjected commented
bump @mattsse

2024-04-30 17:56 UTC, mattsse approved these changes
I guess that makes sense, 
still thinking about more improvements

2024-05-01 02:19 UTC, merged