feat: add new crate op-beacon-core
paradigmxyz/reth pull request #7848
Opened 2024-04-24 18:44 UTC by rupam-04

Addresses #7648 and based on PR #7830 which I closed due to some conflicts

2024-04-24 18:59 UTC, rupam-04 commented
@mattsse I think I have covered all the changes you requested in PR #7830

2024-04-24 22:05 UTC, mattsse requested changes
this is great!

we can simplify a few things because this is now intended for OP only

2024-04-24 22:05 UTC, mattsse commented on crates/optimism/op-beacon-core/src/lib.rs
> +        {
this crate is now specific to optimism,

we can remove all the cfgs here

2024-04-24 22:05 UTC, mattsse commented on crates/optimism/op-beacon-core/src/lib.rs
> +            if self.chain_spec.chain != Chain::goerli() && !self.chain_spec.is_optimism() {
this can be removed because this is expected to be used for OP

2024-04-24 22:05 UTC, mattsse commented on crates/optimism/op-beacon-core/src/lib.rs
> +fn validate_header_extradata(header: &Header) -> Result<(), ConsensusError> {
let's move this to consensus-common and reuse

2024-04-24 22:05 UTC, mattsse commented on crates/optimism/op-beacon-core/src/lib.rs
> +            if !self.chain_spec.is_optimism() && !header.is_zero_difficulty() {
rm non op checks

2024-04-24 22:05 UTC, mattsse commented on crates/optimism/op-beacon-core/src/lib.rs
> +        Self { chain_spec }
```suggestion
        assert!(chain_spec.is_optimism(), "optimism consensus only valid for optimism chains")
        Self { chain_spec }
```

2024-04-24 22:05 UTC, mattsse commented on crates/optimism/op-beacon-core/src/lib.rs
> +    /// Create a new instance of [OptimismBeaconConsensus]
needs 

```rust
/// # Panics
/// 
/// If given chain spec is not optimism [ChainSpec::is_optimism]
```

2024-04-25 15:17 UTC, rupam-04 commented
@mattsse there seems to be a few conflicts again

2024-04-25 17:11 UTC, mattsse requested changes
final nits

2024-04-26 10:00 UTC, mattsse approved these changes
ty

2024-04-26 10:28 UTC, merged