Replace TransactionKind with alloy_primitives::TxKind
paradigmxyz/reth pull request #7885
Opened 2024-04-25 16:00 UTC by andrzejSulkowski

I removed `TransactionKind` and imported `alloy_primitives::TxKind` everywhere where it has been used instead.

For Issue: #7871

2024-04-25 16:33 UTC, onbjerg requested changes

2024-04-25 18:22 UTC, mattsse commented
I'm merging this to prevent conflicts with #7895

2024-04-25 18:36 UTC, onbjerg approved these changes
@fgimenez will merge this now, this has a small impact on your PR

2024-04-25 19:02 UTC, merged

2024-04-26 09:39 UTC, andrzejSulkowski commented
Thank you for the clarification @onbjerg! Greatly appreciated :)

Should I open another Pull Request to implement the requested changes or is this supposed to be treated as finished?