refactor: extract Chainspec type from primitives
paradigmxyz/reth pull request #8055
Opened 2024-05-02 17:10 UTC by guha-rahul

Fixes: #7929 
The error i am facing -  
```
error: failed to load manifest for workspace member `/home/rahul/reth/bin/reth`

Caused by:
  failed to load manifest for dependency `reth-basic-payload-builder`

Caused by:
  failed to load manifest for dependency `reth-engine-primitives`

Caused by:
  failed to load manifest for dependency `reth-chainspec`

Caused by:
  failed to load manifest for dependency `reth-primitives`

Caused by:
  failed to parse manifest at `/home/rahul/reth/crates/primitives/Cargo.toml`

Caused by:
  error inheriting `reth_chainspec` from workspace root manifest's `workspace.dependencies.reth_chainspec`

Caused by:
  `dependency.reth_chainspec` was not found in `workspace.dependencies`
  ```
  Even tho i have `reth-chainspec = { path = "crates/storage/chainspec" }`  under `[workspace.dependencies]` .

2024-05-02 17:14 UTC, mattsse requested changes
nice, a few nits and suggestions

2024-05-02 17:14 UTC, mattsse commented on crates/storage/chainspec/Cargo.toml
I want to move this to `crates/chainspec`

2024-05-02 17:14 UTC, mattsse commented on crates/storage/chainspec/Cargo.toml
> +description = "Commonly used types in reth."
needs update

2024-05-02 17:14 UTC, mattsse commented on crates/storage/chainspec/src/lib.rs
needs regular lib.rs header, see other crates for ref

2024-05-02 17:14 UTC, mattsse commented on crates/primitives/Cargo.toml
> +reth_chainspec.workspace = true
I believe this is your error

```suggestion
reth-chainspec.workspace = true
```

2024-05-02 18:39 UTC, guha-rahul commented on crates/storage/chainspec/Cargo.toml
> +description = "Commonly used types in reth."
there are some extra imports, will remove them when i get back electricity.

2024-05-02 18:41 UTC, guha-rahul commented on crates/primitives/Cargo.toml
> +reth_chainspec.workspace = true
Got a cycle dependency error:- 
```
error: cyclic package dependency: package `reth-chainspec v0.2.0-beta.6 (/home/rahul/reth/crates/chainspec)` depends on itself. Cycle:
package `reth-chainspec v0.2.0-beta.6 (/home/rahul/reth/crates/chainspec)`
    ... which satisfies path dependency `reth-chainspec` (locked to 0.2.0-beta.6) of package `reth-primitives v0.2.0-beta.6 (/home/rahul/reth/crates/primitives)`
    ... which satisfies path dependency `reth-primitives` (locked to 0.2.0-beta.6) of package `reth-chainspec v0.2.0-beta.6 (/home/rahul/reth/crates/chainspec)`
    ... which satisfies path dependency `reth-chainspec` (locked to 0.2.0-beta.6) of package `reth-engine-primitives v0.2.0-beta.6 (/home/rahul/reth/crates/engine-primitives)`
    ... which satisfies path dependency `reth-engine-primitives` (locked to 0.2.0-beta.6) of package `reth-basic-payload-builder v0.2.0-beta.6 (/home/rahul/reth/crates/payload/basic)`
    ... which satisfies path dependency `reth-basic-payload-builder` (locked to 0.2.0-beta.6) of package `reth v0.2.0-beta.6 (/home/rahul/reth/bin/reth)`
    ... which satisfies path dependency `reth` (locked to 0.2.0-beta.6) of package `beacon-api-sse v0.0.0 (/home/rahul/reth/examples/beacon-api-sse)`
    ```

2024-05-02 18:48 UTC, mattsse requested changes
we also need to delete chainspec from primitives crate

2024-05-03 03:59 UTC, guha-rahul commented
hey @mattsse , just a quick clarification , when i am removing `reth-chainspec` from primitives, there are some functions that are imported to other crates, eg: `revm_spec_by_timestamp_after_merge`, so for those we have to explicitly pass the 'reth-primitives' or there is something i am missing?

2024-05-03 11:36 UTC, mattsse commented
these functions we should also move

2024-05-03 12:16 UTC, guha-rahul commented
> these functions we should also move
I have identified 5 functions in the `reth-primitives` crate that are being used in other crates and they have chainspec in params.  
eg: `revm_spec_by_timestamp_after_merge` is defined in `primitive crate` and i am having a mismatch type in `reth-engine-primitives` crate.
Can you please elaborate more on how we should move the functions?

2024-05-03 12:42 UTC, mattsse commented
any chainspec usage needs to be removed from reth-primitives

2024-05-04 00:19 UTC, guha-rahul commented
When i am using `make pr `, this error occurs
```
error[E0412]: cannot find type `ChainSpec` in this scope
   --> crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs:180:22
    |
180 |         chain_spec: &ChainSpec,
    |                      ^^^^^^^^^ not found in this scope
    |
```

Although when i try to add  `use reth_primitives::ChainSpec;`, its showing me an unused import error. Any pointers on why that might be happening?

2024-05-04 11:53 UTC, guha-rahul commented
hey @mattsse , any comments on the above commits?

2024-05-04 12:39 UTC, mattsse reviewed
hmm, need to take a closer look at all the deps, but in essence this is exactly what we want

2024-05-07 13:06 UTC, mattsse requested changes
okay, I made some progress here on figuring out how things should be structured.

what we need to do is keep a dependency on reth-primitives in the chainspec crate, so `chainspec depends on reth-primitives`

this should do it

2024-05-07 18:51 UTC, guha-rahul commented
> okay, I made some progress here on figuring out how things should be structured.
> 
> what we need to do is keep a dependency on [reth-primitives](https://linear.app/paradigm-oss/issue/ID--primitives) in the chainspec crate, so `chainspec depends on reth-primitives`
> 
> this should do it

Do we need to have the Optimism mainnet spec?

2024-05-08 22:14 UTC, mattsse reviewed
this is great, ty.

need to think about how to phase out the primitives code, but this new crate is exactly what we want

2024-05-09 12:47 UTC, guha-rahul commented
> this is great, ty.
> 
> need to think about how to phase out the primitives code, but this new crate is exactly what we want

Do we need to replace it with the alloy-primitives?

2024-05-22 21:35 UTC, Rjected commented
bump @mattsse, this looks ok, the old json genesis assets can be deduplicated probably?

2024-05-24 15:34 UTC, guha-rahul commented
Regarding the failed tests, i am struggling to understand why i am getting errors in `crates/net/eth-wire-types/src/receipt.rs`

2024-05-24 19:50 UTC, Rjected requested changes
could you remove the old chainspec now that it's in a separate crate, along with everything else that was copied to this new crate? we don't want to keep any duplicate files around

2024-05-25 10:04 UTC, mattsse commented
I also want merge this after we have merged all changes in #8214

2024-05-26 10:45 UTC, guha-rahul commented
> could you remove the old chainspec now that it's in a separate crate, along with everything else that was copied to this new crate? we don't want to keep any duplicate files around

hey when I am trying to import the new chainspec in place of the old one , I am getting cyclic dependency errors and @mattsse previously mentioned we cannot import chainspec in reth-primitives since it will cause a cyclic dependency error.

2024-06-17 13:20 UTC, mattsse approved these changes
lgtm

2024-06-17 13:35 UTC, Rjected approved these changes
lgtm

2024-06-17 13:53 UTC, merged