Rpc <> Exex example
paradigmxyz/reth pull request #8112
Opened 2024-05-05 16:46 UTC by supernovahs

closes #8008

I am trying to write a custom rpc to calculate the no of deposits in op bridge . But getting some errors. Can u point me to correct it. Thanks

2024-05-05 16:46 UTC, supernovahs commented
@onbjerg  @mattsse

2024-05-05 16:48 UTC, onbjerg commented on examples/exex/custom-rpc/src/main.rs
> +`
```suggestion

```

2024-05-05 16:50 UTC, onbjerg requested changes
pls also add the example to `examples/readme.md`

2024-05-05 16:50 UTC, onbjerg commented on examples/exex/custom-rpc/src/main.rs
> +       }
this is not correct, we want this to ask the exex what the deposit count is, we don't want to calculate it ourselves on each call

2024-05-05 16:50 UTC, onbjerg commented on examples/exex/custom-rpc/src/main.rs
> +        })
the exex is missing, pls see the other examples

2024-05-05 16:50 UTC, onbjerg commented on examples/exex/custom-rpc/src/main.rs
> +    #[method(name = "opdepositCount")]
please follow the naming convention of the other namespaces

2024-05-05 17:30 UTC, supernovahs commented
yeah , the exex is missing . I was first trying to get an idea on how to get a custom rpc .

2024-05-06 22:21 UTC, gakonst commented
Clarifying that we'd like the _ExEx_ to spawn the RPC in a custom port or path in the JSON-RPC, this is not a task for opening an additional JSON RPC namespace in the same port!

2024-07-15 01:55 UTC, closed without merging