draft pr: Add example crate for custom rlpx subprotocol #7130
paradigmxyz/reth pull request #8113
Opened 2024-05-05 17:01 UTC by owanikin

I am creating this draft pr to solicit feedback on:  1) If I am on the right track. 2) pointers/direction on how to really solve the issue. Thanks for your help.

2024-05-05 17:11 UTC, onbjerg reviewed
just as a quick side note, pls remember to add the example to `examples/readme.md`

2024-05-06 15:48 UTC, mattsse requested changes
great, this is simple yet illustrates the feature perfectly

a few nits

2024-05-06 15:48 UTC, mattsse commented on examples/custom-rlpx-subprotocol/src/main.rs
> +pub mod proto {
can we move this to a separate file?

2024-05-06 15:48 UTC, mattsse commented on examples/custom-rlpx-subprotocol/src/main.rs
> +        // node.network.add_rlpx_sub_protocol(custom_rlpx_handler);
we can uncomment this

2024-05-06 22:01 UTC, gakonst commented on examples/custom-rlpx-subprotocol/src/main.rs
> +}
@mattsse this is cool -- we should demonstrate a bridge/oracle on this, and eventually build up to a full consensus example i feel?

and this is all subprotocols for commands post-establishing a connection, but what about discv? how should we do discovery of nodes that support custom subprotocols?

2024-05-21 11:50 UTC, mattsse commented
@owanikin I rebased this, but this still needs the required protocol trait implementations

2024-06-13 19:35 UTC, gakonst reviewed
bump -- do we want to get this over the line?

2024-06-20 11:05 UTC, loocapro commented
Hi @owanikin are you still on this? I d like to get it.

2024-06-20 12:03 UTC, owanikin commented
> Hi @owanikin are you still on this? I d like to get it.

No @Luca, please do have it.

2024-06-20 15:59 UTC, shekhirin commented
Superseded by https://github.com/paradigmxyz/reth/pull/8991, thanks for starting the work @owanikin!

2024-06-20 15:59 UTC, closed without merging