Extract layers module from rpc crate
paradigmxyz/reth pull request #8163
Opened 2024-05-08 16:14 UTC by rupam-04

Closes #8161

2024-05-09 07:59 UTC, rupam-04 commented
@mattsse any updates on this?

2024-05-10 18:18 UTC, emhane approved these changes
lgtm

2024-05-10 18:18 UTC, emhane commented on Cargo.toml
> +    "testing/testing-utils", "crates/rpc/rpc-layer",
```suggestion
    "testing/testing-utils",
    "crates/rpc/rpc-layer",
```
Nitpick

2024-05-10 19:04 UTC, rupam-04 commented
@emhane any idea why some checks are failing?

2024-05-10 20:29 UTC, emhane commented
try locally 
```
rm Cargo.lock
cargo clean
cargo c
```
then commit the updated lock file, and push. that should do it. @rupam-04

2024-05-10 21:43 UTC, rupam-04 commented
> try locally
> 
> ```
> rm Cargo.lock
> cargo clean
> cargo c
> ```
> 
> then commit the updated lock file, and push. that should do it. @rupam-04

worked, ty

2024-05-11 13:40 UTC, emhane requested changes

2024-05-11 13:40 UTC, emhane commented on Cargo.toml
> -    "crates/rpc/rpc-layer",
we like this alphabetically sorted, please put it back here and remove it from down below

2024-05-11 13:41 UTC, emhane approved these changes

2024-05-11 13:56 UTC, merged