chore: use `NoopBodiesDownloader` & `NoopHeaderDownloader` on `stage unwind` command
paradigmxyz/reth pull request #8165
Opened 2024-05-08 20:23 UTC by joshieDo

Adds noop downloaders and uses them on `reth stage unwind`.

Stepping stone for a standalone unwind pipeline for [#8143](https://github.com/paradigmxyz/reth/pull/8143)

tested and unwinded with no issues

2024-05-08 23:17 UTC, mattsse requested changes
supportive, smol nits

2024-05-08 23:17 UTC, mattsse commented on crates/net/downloaders/src/bodies/noop.rs
> +pub struct NoopBodiesDownloader;
```suggestion
#[non_exhaustive]
pub struct NoopBodiesDownloader;
```

2024-05-08 23:17 UTC, mattsse commented on crates/net/downloaders/src/bodies/noop.rs
> +        Poll::Ready(None)
this should return pending

2024-05-08 23:17 UTC, mattsse commented on crates/net/downloaders/src/headers/noop.rs
> +pub struct NoopHeaderDownloader;
```suggestion
#[non_exhaustive]
pub struct NoopHeaderDownloader;
```

2024-05-08 23:17 UTC, mattsse commented on crates/net/downloaders/src/headers/noop.rs
> +        Poll::Ready(None)
should also return pending

2024-05-09 01:24 UTC, mattsse approved these changes

2024-05-09 10:10 UTC, DaniPopes commented on crates/net/downloaders/src/headers/noop.rs
> +        Poll::Pending
`Ready(None)`? Or panic, if this shouldn't be reached

2024-05-09 10:10 UTC, DaniPopes commented on crates/net/downloaders/src/bodies/noop.rs
> +        Poll::Pending
same

2024-05-09 12:17 UTC, merged