may solve issue #8171
paradigmxyz/reth pull request #8186
Opened 2024-05-09 18:18 UTC by willco-1

extracts init to reth-db-common. Let me know if there is any review notes!

2024-05-10 17:45 UTC, emhane reviewed
I can't see the issue unfortunately, think it requires specific credentials

2024-05-12 13:23 UTC, mattsse requested changes
this is great.

only stylistic nits

2024-05-12 13:23 UTC, mattsse commented on crates/reth-db-common/src/lib.rs
this needs the regular lib.rs header, see other crates

also include the `unused` lint and remove unused deps

2024-08-23 13:14 UTC, emhane commented
need any help here with merge conflicts @willco-1 ?

2024-08-23 13:15 UTC, closed without merging

2024-08-23 13:15 UTC, emhane commented
my bad, closing in favour of https://github.com/paradigmxyz/reth/pull/8373