refactor: move all alloy-compat code to a standalone module
paradigmxyz/reth pull request #8192
Opened 2024-05-10 06:09 UTC by guha-rahul

addresses #8168 
added the alloy-compact impl from block.rs and header.rs to a new module `compat`

2024-05-10 10:20 UTC, mattsse requested changes
ty,
pedantic nits

2024-05-10 10:20 UTC, mattsse commented on crates/primitives/src/compat/mod.rs
let's name this just alloy_compat.rs

2024-05-10 10:20 UTC, mattsse commented on crates/primitives/src/lib.rs
> +use compat::*;
this we don't need

2024-05-10 10:20 UTC, mattsse commented on crates/primitives/src/lib.rs
> +mod compat;
this needs a cfg(feature

2024-05-11 14:12 UTC, guha-rahul commented
@mattsse any updates?

2024-05-12 11:14 UTC, mattsse approved these changes
nice, ty

only changed the nested mod

2024-05-12 11:42 UTC, merged