chore: add _total suffix to counter metrics
paradigmxyz/reth pull request #8263
Opened 2024-05-14 19:21 UTC by estensen

Closes https://github.com/paradigmxyz/reth/issues/8150

2024-05-14 19:22 UTC, estensen commented on crates/tasks/src/lib.rs
> +        let finished_critical_tasks_total_metrics =
should the var names here map to the metrics 1-1? they do tend to become long

2024-05-14 19:22 UTC, estensen commented
I couldn't find any Grafana dashboards to update

2024-05-14 19:29 UTC, mattsse approved these changes
ty

lgtm, pending @shekhirin or @emhane

2024-05-14 19:42 UTC, onbjerg requested changes, later dismissed
please update the grafana dashboard file

2024-05-21 10:05 UTC, mattsse approved these changes
updated all used grafana variables I could find @onbjerg

2024-05-23 11:56 UTC, DaniPopes approved these changes

2024-05-29 15:18 UTC, merged