docs: add comment about potential overflow of base fee per gas
paradigmxyz/reth pull request #8280
Opened 2024-05-15 11:08 UTC by fgimenez

Base fee in EIP1559 is allowed to increase unbounded, and this is not reflected when it is converted from a `UINT256` to a `u64`. It is improbable for it to be bigger than u64 max (would mean ~18 ETH per gas), the PR adds a comment about this.

2024-05-15 13:03 UTC, mattsse requested changes
we recently unified all fee types in alloy to u128:

https://github.com/alloy-rs/alloy/blob/07611cfc9f277dc5bbfd7d21e9d70ad37b441a51/crates/rpc-types/src/eth/block.rs#L112-L122

but not the engine types:

https://github.com/alloy-rs/alloy/blob/07611cfc9f277dc5bbfd7d21e9d70ad37b441a51/crates/rpc-types-engine/src/payload.rs#L157-L165

we should unify the engine types to u128 as well: https://github.com/alloy-rs/alloy/issues/752

2024-05-15 14:10 UTC, fgimenez commented
@mattsse :+1: thx for the heads up! I see that `base_fee_per_gas` is already a `U256` in engine types https://github.com/alloy-rs/alloy/blob/07611cfc9f277dc5bbfd7d21e9d70ad37b441a51/crates/rpc-types-engine/src/payload.rs#L172 but we are casting it to `u64` here. Should we instead cast to `u128` here too?

2024-05-15 14:34 UTC, mattsse commented
yeah we should unify all of the fee fields to u128

2024-05-17 08:34 UTC, mattsse approved these changes
lgtm

I decided against unifying the engine types after having a closer look at the specs which require the types to be 64bits

2024-05-17 09:03 UTC, merged