chore(net): integrate discv5 config builder
paradigmxyz/reth pull request #8289
Opened 2024-05-16 12:39 UTC by emhane

- Integrates `reth_discv5::ConfigBuilder` into `NetworkConfigBuilder`.

The point of having the builder pattern is to build an immutable type. In this case, the config. The way that the network config is currently being built, makes this difficult. This PR tries to keep discv5 config building coherent with discv4 config building, but respecting the builder pattern.
- As many args as possible are added in `DiscoveryArgs::apply_to_builder`, but without passing more other `NetworkArgs` as parameters than necessary.
- Bootnodes, a parallel field to `DiscoveryArgs` on `NetworkArgs` type, are added in the outer scope (`NetworkArgs::load_network_config`).
- Listen sockets are added, wrt to instance, in the outer scope of `NetworkArgs`, in the same function they are added wrt to instance to discv4 (`NetworkArgs::load_network_config`).

At best, an issue is made to design the discv4 config to be immutable too, instead of modifying it after it has been built. Another issue that would make sense, is to move the `instance` flag into `NetworkArgs`.

2024-05-17 07:55 UTC, mattsse requested changes
does this supersede #7856?

2024-05-17 07:55 UTC, mattsse commented on bin/reth/src/commands/p2p/mod.rs
> +    pub network: NetworkArgs,
that makes sense

2024-05-17 07:55 UTC, mattsse commented on crates/net/common/src/ip.rs
we dont need this, please remove

2024-05-17 07:55 UTC, mattsse commented on crates/net/network/src/config.rs
> +    /// Exposes the discovery v5 config builder.
this should document was the closure actually does, like this gets only called if the builder is set.

2024-05-17 07:55 UTC, mattsse commented on crates/net/network/src/config.rs
> +    pub fn discovery_v5_with_builder(
consider renaming this function to map or modify

2024-05-17 15:10 UTC, emhane commented on crates/net/common/src/ip.rs
hm, I'm using it in some places, but will add duplicate code then in, each in the specific files

2024-05-19 09:25 UTC, mattsse approved these changes
pedantic suggestions, otherwise lgtm

2024-05-19 09:25 UTC, mattsse commented on bin/reth/src/commands/p2p/mod.rs
> +fn ipv6(ip: IpAddr) -> Option<Ipv6Addr> {
looks like this is only used once?

can we inline this simple match and remove these functions?

2024-05-19 09:25 UTC, mattsse commented on crates/node-core/src/node_config.rs
> +fn ipv6(ip: IpAddr) -> Option<Ipv6Addr> {
hmm, didn't know this is on main as well, really don't get why IpAddr doesn't have a function for this.

meh the std library does not have this for some reason.

looks like we only use this one, can we remove this function and use match instead?

2024-05-20 07:36 UTC, merged