chore(rpc): decouple op receipt response
paradigmxyz/reth pull request #8353
Opened 2024-05-22 20:49 UTC by emhane

- Adds builder for RPC receipt response
- Moves optimism response body extension logic to optimism crate
- Removes deps `dep:reth-evm-optimism` and `reth-evm-optimism/optimism` from `optimism` feature in `reth-rpc`

2024-05-22 20:51 UTC, emhane commented
blocked by `matt/scaffold-ethapi` which should be base, but isn't compiling yet, will change base when I got that code with skeleton code for type `OpEthApi` compiling

2024-05-23 14:10 UTC, mattsse requested changes, later dismissed
I like this a lot as an initial step towards rpc abstraction

have a few nits

2024-05-23 14:10 UTC, mattsse commented on crates/optimism/rpc/src/lib.rs
this needs the standard header

2024-05-23 14:10 UTC, mattsse commented on crates/optimism/rpc/src/receipts.rs
> +pub struct OptimismTxMeta {
let's move this to transaction.rs

2024-05-25 13:49 UTC, emhane commented on crates/optimism/rpc/src/lib.rs
not sure what you mean...I made it same as for the other optimism crates?

2024-05-25 14:16 UTC, mattsse commented on crates/optimism/rpc/src/lib.rs
https://github.com/paradigmxyz/reth/blob/72f2f1b850a9454789f3ebb3f6efccaee4125659/crates/optimism/node/src/lib.rs#L1-L10

2024-05-27 12:20 UTC, merged