refactor: extract init from node-core
paradigmxyz/reth pull request #8373
Opened 2024-05-23 18:24 UTC by wlawt

Resolves #8171 .

### Overview

Introduces the `reth-db-common` crate and moves `node-core/init.rs` into this new crate.

### Test Plan

- Ran unit tests

2024-05-23 18:41 UTC, mattsse commented
ah cool, I was looking for this actually.
I vaguely remember that there was a previous attempt, could be wrong

2024-05-23 18:42 UTC, mattsse requested changes
nice!

only have a style nit

2024-05-23 18:42 UTC, mattsse commented on crates/db-common/src/lib.rs
this needs the regular lib.rs header including the cfg for unused crates

2024-05-23 18:49 UTC, wlawt commented on crates/db-common/src/lib.rs
done! also cleaned up the unused dependencies

2024-05-23 20:20 UTC, wlawt commented
how can i fix the fmt issue? when i run the `cargo fmt` command used in the CI test, it changes a lot of unrelated files cc @mattsse , thank u!

2024-05-24 10:57 UTC, mattsse requested changes
last pedantic nit

to format please run `cargo +nightly fmt --all`

2024-05-24 10:57 UTC, mattsse commented on Cargo.toml
> +    "crates/db-common",
this should be moved into the crates/storage folder

also please put the new entry in the alphabetically correct position.

2024-05-24 10:57 UTC, mattsse commented on Cargo.toml
> +reth-db-common = { path = "crates/db-common" }
alphabetical order

2024-05-24 10:57 UTC, mattsse commented on crates/node-core/Cargo.toml
> -reth-codecs.workspace = true
great!

2024-05-25 10:00 UTC, mattsse approved these changes
nice

2024-05-25 10:33 UTC, merged