fix(op): filter out receipts for dup txns
paradigmxyz/reth pull request #8400
Opened 2024-05-25 17:37 UTC by emhane

- Filters out receipts for duplicate transactions, which have been filtered out for txns already
- Moves import bedrock receipts to new command
- Fixes tracing
- Coherency checks, consistency with transaction static files

After importing receipts and blocks + init state
<img width="1138" alt="Screenshot 2024-05-25 at 16 18 48" src="https://github.com/paradigmxyz/reth/assets/58548332/c9772c20-e141-4c9b-bcec-65590c5edc66">

After syncing 1M blocks
<img width="1138" alt="Screenshot 2024-05-25 at 19 18 20" src="https://github.com/paradigmxyz/reth/assets/58548332/33d1619a-6930-48d6-8bcc-44074023afc4">

2024-05-25 17:38 UTC, emhane commented on Cargo.toml
> +    "crates/optimism/primitives/",
let me know if I should remove this and put the type contained in the crate back in `reth-primitives`, wanted to make a move in this direction @mattsse

2024-05-27 09:47 UTC, mattsse reviewed
not obvious what is fix and what is refactor here.

the import receipt cmd is only useful for op mainnet, I don't think maintaining two versions of this command is useful

2024-05-27 09:47 UTC, mattsse commented on bin/reth/src/commands/import_receipts_op.rs
why is this a new file now?

2024-05-27 09:47 UTC, mattsse commented on crates/optimism/primitives/Cargo.toml
this makes sense in general, but is unrelated to this fix?

2024-05-27 10:08 UTC, emhane commented on crates/optimism/primitives/Cargo.toml
kind of unrelated

2024-05-27 10:10 UTC, emhane commented
> not obvious what is fix and what is refactor here.
> 
> the import receipt cmd is only useful for op mainnet, I don't think maintaining two versions of this command is useful

op is the only use case we have though of at least, happy if reth is used in other ways for example by researchers. in testing, the fact that `import`, `import-receipts` and `init-state` are generic commands, allows starting the chain at any given height

2024-05-27 10:20 UTC, emhane commented on bin/reth/src/commands/import_receipts_op.rs
hm realised this issue must be addressed to make it fully generic https://github.com/paradigmxyz/reth/issues/8145, i.e. allow import of receipts exported in standard rlp format and not on the branch of testinprod

2024-05-27 13:27 UTC, emhane commented
scope of the pr grew a bit to update the book @mattsse

2024-05-28 09:29 UTC, emhane commented on book/run/sync-op-mainnet.md
> +Import of >100 million OVM blocks, from genesis to Bedrock, completes in 6 hours.
running in maxperf now, let me see if this takes significantly less time first

2024-05-28 12:12 UTC, mattsse requested changes
pedantic style nit

2024-05-28 12:12 UTC, mattsse commented on crates/optimism/primitives/src/lib.rs
still needs the regular header

2024-05-28 16:43 UTC, mattsse approved these changes

2024-05-28 17:05 UTC, merged