implement `devp2p key gen`
paradigmxyz/reth pull request #8403
Opened 2024-05-27 07:35 UTC by int88

implement part of #7411

2024-05-27 07:48 UTC, int88 commented
@mattsse PTAL :)

2024-05-27 12:04 UTC, mattsse requested changes
great!

some nits

2024-05-27 13:08 UTC, DaniPopes commented on bin/devp2p/Cargo.toml
> +license.workspace = true
other keys from workspace too? see the other crates

2024-05-28 03:15 UTC, int88 commented on bin/devp2p/src/main.rs
> +    if let Err(err) = cli.run() {
Will update when some subcommands need async setup :)

2024-05-28 03:31 UTC, int88 commented
@mattsse updated!

2024-05-30 01:32 UTC, int88 commented
friendly ping @mattsse :)

2024-06-06 16:20 UTC, mattsse approved these changes
lgtm,

I thought about this a bit and my main concern rn is that porting all of these commands will be a lot of work that also adds more maintenance effort for a tool that already exists.

I can see the value in it but what like to hear what @Rjected @shekhirin @emhane think

2024-06-06 16:28 UTC, Rjected reviewed
> lgtm,
> 
> I thought about this a bit and my main concern rn is that porting all of these commands will be a lot of work that also adds more maintenance effort for a tool that already exists.
> 
> I can see the value in it but what like to hear what @Rjected @shekhirin @emhane think

adding an subset may make sense, at least the commands which are useful in infrastructure or which are otherwise impactful. I don't think we need to reach full feature parity. I don't really like it as a separate command however. We already have the `reth p2p` command which does some isolated things w.r.t p2p, so I think these would fit there. Another issue with separate binaries is that they are not documented in the book or included in the release workflow.

2024-06-06 21:08 UTC, emhane commented
agree with @mattsse and @Rjected. I didn't remember that `enr-cli` exists, my bad @int88 . see updated list https://github.com/paradigmxyz/reth/issues/7411#issuecomment-2031215333, I crossed out a bunch of stuff that shouldn't be in reth.

2024-06-06 21:08 UTC, closed without merging