feat: move core rpc server types to standalone crate
paradigmxyz/reth pull request #8515
Opened 2024-05-30 14:42 UTC by leruaa

Closes #8460

2024-05-30 17:56 UTC, mattsse requested changes
great start

with a standalone, lightweight crate we can also pull this in in reth-rpc and move the constants to reth-rpc-server-types

2024-05-30 17:56 UTC, mattsse commented on Cargo.toml
> +reth-rpc-server-types = { path = "crates/rpc/rpc-server-types" }
swap order

2024-05-30 17:56 UTC, mattsse commented on crates/node-core/Cargo.toml
> +reth-rpc-server-types.workspace = true
swap order, alphabetically

2024-05-30 17:56 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +use reth_rpc_server_types::constants::*;
this should be re-exported as `pub use reth_rpc_server_types::constants;`

2024-05-30 17:56 UTC, mattsse commented on crates/rpc/rpc-server-types/Cargo.toml
> +reth-rpc.workspace = true
it'd be great if we can do without.

no that we have a separate crate for constants we can move all constants from reth-rpc crate in here and then import in reth-rpc instead, inverting the dependency.

2024-05-31 10:23 UTC, mattsse requested changes
solid,

next we need the remaining types that are used in node-core

2024-05-31 10:23 UTC, mattsse commented on crates/node-core/Cargo.toml
>  reth-rpc-builder.workspace = true
this we want to remove

2024-05-31 10:23 UTC, mattsse commented on crates/rpc/rpc-server-types/src/lib.rs
this needs the regular lib.rs header and unused clippy attribute, see other crates

2024-05-31 10:23 UTC, mattsse commented on crates/rpc/rpc-server-types/Cargo.toml
> +reth-primitives.workspace = true
if possible depend on alloy-primitives instead

2024-05-31 17:46 UTC, leruaa commented
@mattsse Can you please have a look at my last commit and tell me if I'm heading in the right direction? Feels like I'm moving the entire `rpc-builder` crate...

2024-06-02 09:25 UTC, mattsse commented
I see, the main problem is this config trait:

https://github.com/paradigmxyz/reth/blob/e75edf3be7d2fc48e510737a06b8717d26bb09b3/crates/node-core/src/cli/config.rs#L18-L18

hmm, this is a bit tricky, I need to think about this a bit,

okay, for this pr, let's only do constants first, get the pr over the line and then continue with more incremental changes. it's fine if node-core then also depends on server-types.
but it will be easier to move stuff around once we have the crate

2024-06-03 19:43 UTC, leruaa commented on crates/node-core/Cargo.toml
>  reth-rpc-builder.workspace = true
Aborted for now

2024-06-03 20:03 UTC, leruaa commented
@mattsse I think this is ready to be reviewed.

P.S.: Don't hesitate if you can think of some good first issues for the next steps :)

2024-06-04 12:06 UTC, mattsse approved these changes
lgtm

next we can move these constants and types for cache

https://github.com/paradigmxyz/reth/blob/13fcb885c60bab1390c4525cb5a0c35ab215e833/crates/node-core/src/args/rpc_state_cache.rs#L2-L5

then I think we move the config traits

2024-06-04 12:19 UTC, merged