feature: loglevel value parser
paradigmxyz/reth pull request #8573
Opened 2024-06-03 19:54 UTC by JackG-eth

custom clap value parser for LogLevel enum

Motivation
remove clap feature from LogLevel #8465

2024-06-03 20:52 UTC, mattsse requested changes
nice, valueparser looks great

now we need to move this to node-core so we can actually get rid of the clap dep

2024-06-03 20:52 UTC, mattsse commented on crates/storage/errors/src/db.rs
> +impl TypedValueParser for LogLevelValueParser {
this should be moved to node-core

2024-06-03 22:35 UTC, JackG-eth commented on crates/storage/errors/src/db.rs
> +impl TypedValueParser for LogLevelValueParser {
of course, mb

2024-06-04 13:12 UTC, mattsse requested changes
almost there

2024-06-04 13:12 UTC, mattsse commented on crates/node-core/src/args/database.rs
> +struct LogLevelValueParser;
```suggestion
#[derive(Clone, Debug, Default)]
#[non_exhaustive]
pub struct LogLevelValueParser;
```

2024-06-04 13:12 UTC, mattsse commented on crates/node-core/src/args/database.rs
> +        Some(Box::new(values))
this needs the same code as in the issue ` fn to_possible_value` with possiblevalue name + help

2024-06-05 07:45 UTC, mattsse approved these changes
ty

2024-06-05 08:11 UTC, merged