feat(db): fuzzing & benchmark
paradigmxyz/reth pull request #86
Opened 2022-10-17 12:35 UTC by joshieDo

## Summary

Added both basic fuzzing and benchmarks. Follow-ups would be to nail down what do we actually want to fuzz (regarding encoding/decoding) and come up with some data to benchmark those same things.

## Fuzzing
Tried a couple fuzzer libraries and ended up with https://github.com/trailofbits/test-fuzz, which is very convenient frontend for https://github.com/rust-fuzz/afl.rs . I used the most basic setup, but there might be things of use for other kinds of fuzzing targets. Only implemented table encoding/decoding.

```
Requirements:
`cargo install -f cargo-test-fuzz afl`

How to run:
`cargo test` - it will generate the corpus w/ list of fuzz targets.
`cargo test-fuzz Header` - will fuzz.
```

This will generate different targets, but only one is run at a time.
`crates/tests/src/fuzz/table_codecs.rs` currently implements `Header` and `Account` targets.

We should decide on what types to fuzz and whatnot. 

For derived types, I feel like we could fuzz targets which use most types instead of fuzzing all types. (Header uses BlockNumber, u64, etc)
Custom serialized types should be fuzzed invidiually. (eg. bitfield types) 

I'm not sure if it makes sense to add them to the CI, or if we can have some kind of infrastructure in place that could run these types indefinitely.

wdyt

## Benchmark

Added both `criterion` and `iai`. You can read the differences [here](https://bheisler.github.io/criterion.rs/book/iai/comparison.html). tl;dr `iai` uses valgrind instead of statistical analysis and might be better suited for `CI`.
Limitation is that both of them do not provide a way to fit in a custom metric, and that's why i have that ugly hack of  `Size (bytes): `4232588269``.

I think they're both valuable. Here is the output of both:

```bash
$ cargo bench  --features bench-postcard`
-- criterion
postcard                time:   [1.2836 µs 1.2870 µs 1.2920 µs]
                        change: [-0.4633% +0.1730% +0.7731%] (p = 0.62 > 0.05)
                        No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
  3 (3.00%) high mild
  3 (3.00%) high severe

Size (bytes): `523`
     Running benches/encoding_iai.rs (/root/reth/target/release/deps/encoding_iai-530a302dd257946c)
-- iai
postcard
  Instructions:               25950 (No change)
  L1 Accesses:                31351 (No change)
  L2 Accesses:                   30 (No change)
  RAM Accesses:                 224 (No change)
  Estimated Cycles:           39341 (No change)
```

```bash
$ cargo bench  --features bench`

scale                   time:   [570.20 ns 571.07 ns 572.12 ns]
                        change: [-1.0265% -0.3364% +0.5378%] (p = 0.46 > 0.05)
                        No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) high mild
  4 (4.00%) high severe

Size (bytes): `290`
     Running benches/encoding_iai.rs (/root/reth/target/release/deps/encoding_iai-22d806f598e1d81b)
scale
  Instructions:                6771 (-3.861991%)
  L1 Accesses:                10290 (-3.570425%)
  L2 Accesses:                   27 (-27.02703%)
  RAM Accesses:                 227 (-0.438596%)
  Estimated Cycles:           18370 (-2.473986%)
```

2022-10-17 13:40 UTC, mattsse reviewed
some comments regarding structure.

2022-10-19 14:52 UTC, mattsse requested changes
lgtm, would like to see some additional docs for impl macros.

2022-10-19 15:17 UTC, mattsse approved these changes

2022-10-19 20:07 UTC, gakonst approved these changes
sick. @joshieDo understand we'll do this for every type right?

2022-10-19 20:08 UTC, merged