feature:  no std suppport exec crate
paradigmxyz/reth pull request #8711
Opened 2024-06-09 17:28 UTC by JackG-eth

Description
no_std support for "reth-execution-errors"

Motivation
closes #8706

2024-06-09 18:05 UTC, mattsse requested changes

2024-06-09 18:05 UTC, mattsse commented on crates/evm/execution-errors/src/lib.rs
> +        #[allow(deprecated)]
```suggestion
```

2024-06-09 18:05 UTC, mattsse commented on crates/evm/execution-errors/src/lib.rs
> +            Self::EVM { error: source, .. } => Some(source),
```suggestion
            Self::EVM { error, .. } => Some(source),
```

2024-06-09 18:05 UTC, mattsse commented on crates/evm/execution-errors/src/lib.rs
> +        #[allow(unused_variables, deprecated, clippy::used_underscore_binding)]
```suggestion
```

2024-06-09 18:05 UTC, mattsse commented on crates/evm/execution-errors/src/trie.rs
> +            Self::StorageRootError(storage_err) => write!(f, "{}", storage_err),
delegate via err.fmt(f)

2024-06-09 18:05 UTC, mattsse commented on crates/evm/execution-errors/src/trie.rs
> +            Self::DB(db_err) => write!(f, "{}", db_err),
error.fmt(f)

2024-06-09 18:06 UTC, mattsse requested changes

2024-06-09 18:06 UTC, mattsse commented on crates/evm/execution-errors/src/lib.rs
> +use core::fmt::{Display, Formatter, Result};
```suggestion

use core::fmt::{Display, Formatter, Result};
```

2024-06-09 19:38 UTC, mattsse requested changes
needs actual no-std cfg otherwise lgtm

2024-06-09 19:38 UTC, mattsse commented on crates/evm/execution-errors/src/lib.rs
this does not disable std if cfg(std) is not enabled

2024-06-10 09:24 UTC, onbjerg approved these changes
not a huge fan of the cfg for error impl and not using thiserror, but not much that can be done about it i think. when error is stabilized in core maybe thiserror will support nostd and we can revisit. we should make a follow up issue for that, tracking stabilization of error in core

2024-06-10 10:47 UTC, mattsse approved these changes
lgtm
pending @DaniPopes

2024-06-10 10:52 UTC, DaniPopes commented
why can we not use thiserror_no_std?

2024-06-10 13:18 UTC, DaniPopes commented
You're likely forgetting gating Other(..) variant to also be under `cfg(feature = "std")`, because it cannot be emulated in `no_std`.

2024-06-10 13:34 UTC, JackG-eth commented
> You're likely forgetting gating Other(..) variant to also be under `cfg(feature = "std")`, because it cannot be emulated in `no_std`.

This makes a lot of sense, i'll come back to you tonight when I've had a chance to test it.

2024-06-11 20:42 UTC, mattsse commented
superseded by #8729

2024-06-11 20:42 UTC, closed without merging