feat: support no_std for reth-execution-errors
paradigmxyz/reth pull request #8729
Opened 2024-06-10 20:37 UTC by JackG-eth

Description

I have created a seperate implementation that uses thiserror_no_std instead of manually implementing said traits as no-std will be stabilized in core in the not to distant future.

Motivation
closes #8459

2024-06-10 20:43 UTC, JackG-eth commented
@DaniPopes @mattsse

Re our conversation: https://github.com/paradigmxyz/reth/pull/8711

Regarding the comment "You're likely forgetting gating Other(..) variant to also be under cfg(feature = "std"), because it cannot be," I might be wrong, but I believe some crates, like crates/blockchain-tree-api/src/error.rs, will run into trait bound issues. This means we still need to provide manual implementations of the std::error::Error trait where '#[error(transparent)]' is used.

To ensure compatibility with both std and no_std environments, we should conditionally implement std::error::Error for our error types using cfg(feature = "std").

2024-06-10 22:22 UTC, mattsse reviewed
okay, so all thiserror-no-std gives us is no manual display and from impl?

is it worth the dependency? given that we already have it in the other pr @DaniPopes ?

2024-06-10 23:33 UTC, DaniPopes commented
> To ensure compatibility with both std and no_std environments, we should conditionally implement std::error::Error for our error types using cfg(feature = "std").

I believe you are missing propagating the std feature to thiserror-no-std, as well as it should be declared as default-features=false in the workspace. After this it should be good to merge


> okay, so all thiserror-no-std gives us is no manual display and from impl?
> 

yes

> 
> is it worth the dependency? given that we already have it in the other pr @DaniPopes ?

yes

2024-06-11 09:54 UTC, JackG-eth commented
> I believe you are missing propagating the std feature to thiserror-no-std, as well as it should be declared as default-features=false in the workspace. After this it should be good to merge

Yeah you're right, I'll push this tonight and the same for other branches.

2024-06-11 20:40 UTC, mattsse approved these changes
ah nice

2024-06-11 20:41 UTC, mattsse requested changes

2024-06-11 20:41 UTC, mattsse commented on crates/evm/execution-errors/src/lib.rs
this is missing the no_std disable

2024-06-11 21:09 UTC, JackG-eth commented on crates/evm/execution-errors/src/lib.rs
Added and builds succesfully with `no-default-features`

2024-06-11 23:06 UTC, mattsse approved these changes
great, hopefully we can remove the no-std thiserror soon

2024-06-11 23:10 UTC, JackG-eth commented
> great, hopefully we can remove the no-std thiserror soon



> great, hopefully we can remove the no-std thiserror soon

Will be happy to revert it once we can

2024-06-11 23:37 UTC, merged