feat: no_std CI integration
paradigmxyz/reth pull request #8871
Opened 2024-06-16 16:39 UTC by JackG-eth

Motivation

Closes #8716 

Description

Currently we don't check that these actually compile with --no-default-features (i.e. no std) in CI, but we should.

2024-06-16 16:41 UTC, JackG-eth commented
Hi, Few notes on this:

1. Should this be in the integration.yml or entirely seperated.
2. Should this include other crates like alloy/revm or be member specific
3. Should this include `riscv32imac-unknown-none-elf` in the build script?

2024-06-16 18:07 UTC, DaniPopes commented on .github/workflows/integration.yml
> +  no-std:
pls move to lint.yml

2024-06-17 05:57 UTC, DaniPopes requested changes

2024-06-17 05:57 UTC, DaniPopes commented on .github/workflows/lint.yml
> +  no-std:
pls move above to after clippy

2024-06-17 05:57 UTC, DaniPopes commented on .github/workflows/lint.yml
> +        clippy-binaries,
can convert to a yaml list (use dashes and remove commas)
```
- a
- b
- c
```

2024-06-17 21:47 UTC, DaniPopes approved these changes

2024-06-17 22:03 UTC, merged