chore: move different chain hardfork sets to `reth-ethereum-forks`
paradigmxyz/reth pull request #8984
Opened 2024-06-20 11:04 UTC by joshieDo

Makes them `const` as well.

2024-06-20 15:41 UTC, Rjected reviewed
thinking we might want to rename the crate if this contains op forks as well? maybe reth-hardforks or something?

2024-06-20 23:46 UTC, mattsse commented
yeah but we can this next

2024-06-20 23:50 UTC, mattsse requested changes
pedantic nits.

supportive of name change as followup

2024-06-20 23:50 UTC, mattsse commented on crates/ethereum-forks/src/chains/ethereum.rs
> +pub(crate) const PARIS_TTD_GOERLI: U256 = U256::from_limbs([10790000, 0, 0, 0]);
why does this have different pub

2024-06-20 23:50 UTC, mattsse commented on crates/ethereum-forks/src/chains/mod.rs
> +pub static DEV_HARDFORKS: [(Hardfork, ForkCondition); 14] = [
this should be under dev.rs

2024-06-20 23:50 UTC, mattsse commented on crates/ethereum-forks/src/chains/optimism.rs
> +pub static OP_MAINNET_HARDFORKS: [(Hardfork, ForkCondition); 21] = [
we probably don't need static?
wdyt @DaniPopes

2024-06-21 13:16 UTC, DaniPopes requested changes

2024-06-21 13:16 UTC, DaniPopes commented on crates/ethereum-forks/src/chains/ethereum.rs
> +const PARIS_TTD_SEPOLIA: U256 = U256::from_limbs([17000000000000000, 0, 0, 0]);
use `uint!` macro

2024-06-21 13:16 UTC, DaniPopes commented on crates/ethereum-forks/src/chains/ethereum.rs
> +        assert_eq!(ttd, PARIS_TTD_SEPOLIA);
no need with `uint!` macro

2024-06-21 13:22 UTC, mattsse approved these changes
lgtm

pending uint! and @DaniPopes

2024-06-21 13:33 UTC, DaniPopes approved these changes

2024-06-21 13:53 UTC, merged