chore: simplify OptimismGenesisInfo extraction
paradigmxyz/reth pull request #9031
Opened 2024-06-22 16:16 UTC by Vid201

Closes #8952

2024-06-24 09:55 UTC, mattsse requested changes
ty,

can we also add a simple test case for this:

```rust
  "config": {
    "chainId": 8453,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirGlacierBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "arrowGlacierBlock": 0,
    "grayGlacierBlock": 0,
    "mergeNetsplitBlock": 0,
    "bedrockBlock": 0,
    "regolithTime": 0,
    "terminalTotalDifficulty": 0,
    "terminalTotalDifficultyPassed": true,
    "optimism": {
      "eip1559Elasticity": 6,
      "eip1559Denominator": 50
    }
  },
```

2024-06-24 09:55 UTC, mattsse commented on crates/chainspec/src/spec.rs
> +use serde::Deserialize;
please use fullpath instead of feature gating the import

2024-06-24 21:02 UTC, Vid201 commented
> ty,
> 
> can we also add a simple test case for this:
> 
> ```rust
>   "config": {
>     "chainId": 8453,
>     "homesteadBlock": 0,
>     "eip150Block": 0,
>     "eip155Block": 0,
>     "eip158Block": 0,
>     "byzantiumBlock": 0,
>     "constantinopleBlock": 0,
>     "petersburgBlock": 0,
>     "istanbulBlock": 0,
>     "muirGlacierBlock": 0,
>     "berlinBlock": 0,
>     "londonBlock": 0,
>     "arrowGlacierBlock": 0,
>     "grayGlacierBlock": 0,
>     "mergeNetsplitBlock": 0,
>     "bedrockBlock": 0,
>     "regolithTime": 0,
>     "terminalTotalDifficulty": 0,
>     "terminalTotalDifficultyPassed": true,
>     "optimism": {
>       "eip1559Elasticity": 6,
>       "eip1559Denominator": 50
>     }
>   },
> ```

added

2024-06-25 09:24 UTC, mattsse approved these changes
ty!

2024-06-25 09:48 UTC, merged