refactor(net): move node record constants to network-peers crate
paradigmxyz/reth pull request #9161
Opened 2024-06-27 21:23 UTC by tcoratger

Should close #9157.

2024-06-27 21:27 UTC, joshieDo requested changes
Can you make it slightly more structured? 

```
bootnodes/mod.rs
bootnodes/ethereum.rs
bootnodes/optimism.rs
```

Probably have to fix a bunch of imports across different crates as well

2024-06-27 21:50 UTC, tcoratger commented
> Can you make it slightly more structured?
> 
> ```
> bootnodes/mod.rs
> bootnodes/ethereum.rs
> bootnodes/optimism.rs
> ```
> 
> Probably have to fix a bunch of imports across different crates as well

fixed

2024-06-27 21:50 UTC, tcoratger commented on crates/chainspec/src/net.rs
> -// Ethereum bootnodes come from <https://github.com/ledgerwatch/erigon/blob/devel/params/bootnodes.go>
fixed

2024-06-28 07:45 UTC, mattsse approved these changes

2024-06-28 07:45 UTC, merged