perf(pruner): pass `ProviderFactory` to segments
paradigmxyz/reth pull request #9184
Opened 2024-06-28 20:37 UTC by emhane

Closes https://github.com/paradigmxyz/reth/issues/9183

Possibly closes https://github.com/paradigmxyz/reth/issues/9181

2024-06-29 00:53 UTC, servusdei2018 approved these changes

2024-06-29 07:56 UTC, mattsse reviewed
@joshieDo I'm not familiar with the internals here, but I assume this now opens the actual tx later (perhaps even multiple times)

and moves away from this:

https://github.com/paradigmxyz/reth/blob/f4689f35b2013da9c48190ca3ef738e82ac7c67d/crates/prune/prune/src/pruner.rs#L130-L133

imo opening write txs and committing in the individual prune functions individually is perhaps not what we want here?

2024-07-01 13:23 UTC, shekhirin requested changes
The implementation is correct, but the motivation behind this PR is IMO wrong:
1. Opening multiple write transactions is more expensive than a single one
2. Engine message processing is blocked on the pruner being active, and not the write tx being open https://github.com/paradigmxyz/reth/blob/db191c82a57dd3eed8cf982dee197526433e7d09/crates/consensus/beacon/src/engine/mod.rs#L508-L511
3. Subjective – passing `provider_factory` and opening a new transaction manually is more error-prone, as the segment implementation can forget to commit the transaction. I like the idea that we inherited from the pipeline, that we open and commit transactions outside the stage itself.

2024-07-03 15:14 UTC, emhane commented
blocked by https://github.com/paradigmxyz/reth/issues/8746

2024-07-03 15:22 UTC, closed without merging