chore: remove `test-utils`, `arbitrary` and `proptest` from built binary
paradigmxyz/reth pull request #9332
Opened 2024-07-05 16:14 UTC by joshieDo

* Removes the dependencies from the `reth` binary.
* Adds a CI step to make sure they don't creep back in

```bash
$ git checkout joshie/rmtu
$ cargo tree -e features -e no-dev --package reth  | grep -E 'arbitrary|proptest' | wc -l
       0
$ git checkout main
$ cargo tree -e features -e no-dev --package reth  | grep -E 'arbitrary|proptest' | wc -l
      85
```

2024-07-05 17:04 UTC, DaniPopes requested changes
cc https://github.com/paradigmxyz/reth/issues/8837

2024-07-05 17:04 UTC, DaniPopes commented on .github/workflows/lint.yml
> +  no-test-deps:
move before lint-success and add it to the needs list

2024-07-05 17:04 UTC, DaniPopes commented on crates/node/builder/Cargo.toml
> +test-utils = ["reth-db/test-utils"]
pls add "insert final newline" in your editor :)

2024-07-06 04:33 UTC, mattsse approved these changes

2024-07-06 12:02 UTC, DaniPopes approved these changes

2024-07-06 12:16 UTC, merged