perf(pruner): senders not written to db in full node
paradigmxyz/reth pull request #9372
Opened 2024-07-08 14:59 UTC by emhane

Skips sender recovery stage for a full node. Instead, senders are recovered on demand in execution stage.

Execution with sender recovery on demand takes just under 2 hours on high end hw. Saves 158 GiB disk space. Comparing to [public node](https://reth.paradigm.xyz/d/2k8BXz24x/reth?orgId=1&refresh=30s&var-instance=localhost:5006&var-blockchain_tree_action=&var-database_action=).

<img width="1474" alt="Screenshot 2024-07-08 at 16 20 06" src="https://github.com/paradigmxyz/reth/assets/58548332/a0942eac-6937-4105-9fbf-c7103b449dad">

2024-07-08 15:01 UTC, shekhirin commented
Can we get a comparison between a recent full node Execution stage time, and this branch? Would be nice to understand if it's a matter of minutes of overhead, or hours.

2024-07-08 15:02 UTC, shekhirin requested changes

2024-07-09 12:23 UTC, emhane commented on crates/node/builder/src/setup.rs
> +    let is_full_node = prune_modes.receipts.is_some();
that wasn't discussed afaik, cc @mattsse

2024-07-09 14:18 UTC, emhane commented
1.0 benchmarks:
execution: 41h 14m

this branch:
execution: 45h

@shekhirin 

I'd say we include this as a temp fix, until https://github.com/paradigmxyz/reth/issues/9270 is addressed

2024-07-09 14:39 UTC, emhane commented
will take too long on regular hw

2024-07-09 14:39 UTC, closed without merging