feat: implement generalizable rpc middleware
paradigmxyz/reth pull request #9429
Opened 2024-07-10 18:21 UTC by smatthewenglish

towards more flexibility of rpc middleware in the style of `Server` from `jsonrpsee`

2024-07-11 09:14 UTC, mattsse requested changes
looking good so far, removing the intermediary type definitely helped a lot

2024-07-11 09:14 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +{
We need several implant blocks for this type, and we want to be as unrestrictive as possible, so the setters are easy to call

we only need to enforce these bounds when we start the server

2024-07-11 09:14 UTC, mattsse commented on crates/rpc/rpc-builder/tests/it/startup.rs
> +    let res = RpcServerConfig::<Identity>::ws(Default::default())
this shouldn't be necessary if we put the init functions in another impl block that doesn't require this generic

2024-07-12 11:25 UTC, mattsse requested changes
great!

the pr does change additional metric setup internals, I don't want to do this in this pr, because this is out of scope.
we can limit this pr to the introduction of the additional middleware value and then try to integrate it in a followup then it's easier.

2024-07-12 11:25 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +    pub fn with_ws(mut self, config: ServerBuilder<Identity, Identity>) -> Self {
these accept self and return Self, and don't care about the current generic, so these should be moved to the 

`impl<RpcMiddleware> RpcServerConfig<RpcMiddleware>

scope

2024-07-12 11:25 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +    pub http: Option<RpcModule<Context>>,
I wanna keep this private

2024-07-12 11:25 UTC, mattsse commented on crates/rpc/rpc-builder/src/lib.rs
> +                    .set_rpc_middleware(self.rpc_middleware)
this now puts the metrics setup on the caller, we don't want this.

can we please keep the rpc_middleware setup as it was before and then integrate the custom middleware in a next step
there's a lot that can go wrong here

2024-07-12 11:25 UTC, mattsse commented on crates/rpc/rpc-builder/src/metrics.rs
this pr should not change the any metrics setup

2024-07-12 14:29 UTC, smatthewenglish commented
> great!
> 
> the pr does change additional metric setup internals, I don't want to do this in this pr, because this is out of scope. we can limit this pr to the introduction of the additional middleware value and then try to integrate it in a followup then it's easier. I'm fine with leaving the additional rpc_middleware unused at first

sounds good. i've updated the branch accordingly

2024-07-15 12:44 UTC, mattsse approved these changes
lgtm!

next we can try merging the existing metrics layer setup with the additional rpc middleware field

2024-07-15 12:57 UTC, merged

2024-07-15 15:10 UTC, smatthewenglish commented
> lgtm!
> 
> 
> 
> next we can try merging the existing metrics layer setup with the additional rpc middleware field

Thank you for the review. This was my first pr with the prefix "feat" 🙌

That sounds good to me, I'll give it a shot!