feat: partial wasm32-wasi compilation
paradigmxyz/reth pull request #9430
Opened 2024-07-10 18:35 UTC by jtguibas

The goal of this PR is to set a foundation for supporting wasm32-wasi compilation of reth crates. 

The currently supported crates are: reth-codecs, reth-consensus, reth-db, reth-db-api, reth-ethereum-forks, reth-evm, reth-evm-ethereum, reth-network-peers, reth-primitives, reth-primitives-traits, and reth-revm with no default features but std. Overtime, we can add support for more crates as needed.

Merging this PR succesfully requires having updated releases of `revm` and `revm-inspector` following the merge of this PR: https://github.com/bluealloy/revm/pull/1601.

2024-07-10 18:38 UTC, jtguibas commented on Cargo.toml
> -revm = { version = "11.0.0", features = [
TODO: Update once https://github.com/bluealloy/revm/pull/1601 merged into `revm` and `revm-inspectors` is also updated.

2024-07-11 07:56 UTC, mattsse requested changes
supportive, but I'd like to do this in multiple steps

2024-07-11 07:56 UTC, mattsse commented on Cargo.toml
could you submit this separately?

2024-07-11 07:56 UTC, mattsse commented on crates/storage/db/src/utils.rs
> +    0
this is a bit dangerous

this is used as an option, so I think we want to make the function that is used to configure the page size return an option instead

https://github.com/paradigmxyz/reth/blob/fc4c037e60b623b81b296fe9242fa905ff36b89a/crates/storage/libmdbx-rs/src/environment.rs#L632-L637

2024-08-05 14:26 UTC, shekhirin commented
Superseded by https://github.com/paradigmxyz/reth/issues/10088

2024-08-05 14:26 UTC, closed without merging