replaced generic to box dyn
paradigmxyz/reth pull request #9443
Opened 2024-07-11 12:39 UTC by loocapro

Closes: https://github.com/paradigmxyz/reth/issues/9441

2024-07-11 14:39 UTC, mattsse requested changes

2024-07-11 14:39 UTC, mattsse commented on crates/net/network/src/manager.rs
> +    _phantom: std::marker::PhantomData<C>,
we should be able to get rid of this as well, if not possible due to some downstream requirements, I'm okay with keeping it in this pr

2024-07-11 14:39 UTC, mattsse commented on crates/net/network/src/state.rs
> +pub struct BlockNumReader(Box<dyn reth_storage_api::BlockNumReader>);
```suggestion
pub(crate) struct BlockNumReader(Box<dyn reth_storage_api::BlockNumReader>);
```

2024-07-11 14:39 UTC, mattsse commented on crates/net/network/src/state.rs
> +        write!(f, "<dyn BlockNumReader>")
should use fmt syntax for formatting structs: ` f.debug_struct(`

2024-07-12 12:37 UTC, mattsse commented on crates/net/network/src/manager.rs
> +    _phantom: std::marker::PhantomData<C>,
can we not move the generic to the function itself:

```
 pub async fn new<C>(config: NetworkConfig<C>)

```

2024-07-12 12:39 UTC, mattsse requested changes
I think we can get of the generic on the struct entirely and only enforce it on the functions that operate on Networkconfig

2024-07-12 14:15 UTC, mattsse approved these changes
nice!

2024-07-12 14:16 UTC, DaniPopes approved these changes

2024-07-12 14:28 UTC, merged