Frontier calculator
paradigmxyz/reth pull request #9495
Opened 2024-07-13 18:52 UTC by SozinM

Closes https://github.com/paradigmxyz/reth/issues/9476

2024-09-09 05:50 UTC, SozinM commented on crates/chainspec/src/spec.rs
> +            ForkCondition::TTD { total_difficulty, fork_block: None } => {
left this to keep backward compatible behaviour

2024-09-30 08:32 UTC, SozinM commented
@mattsse minibump :)

2024-11-26 03:30 UTC, onbjerg requested changes
some preliminary comments, sorry for the delay

2024-11-26 03:30 UTC, onbjerg commented on crates/chainspec/src/spec.rs
> +                    ForkId { hash: ForkHash([0x74, 0x9e, 0x0c, 0xdc]), next: 0 },
these fork ids should not change. they are used in discovery, so its important they stay fixed to line up with what every other client agrees on

2024-11-26 03:30 UTC, onbjerg commented on crates/consensus/common/src/difficulty.rs
> +**/
please use `/// ` as is standard in rust

2024-11-26 03:30 UTC, onbjerg commented on crates/consensus/common/src/difficulty.rs
> +/**
same as above

2024-11-26 03:30 UTC, onbjerg commented on crates/consensus/common/src/difficulty.rs
> +/**
same as above

2024-11-26 03:30 UTC, onbjerg commented on crates/consensus/common/src/difficulty.rs
> +// Helper to convert BombDelay to u64
this comment is not necessary

2024-11-26 10:49 UTC, mattsse commented
I noticed that geth will phase out difficulty entirely, effectively deprecating this.

So I think we also don't need to add it, especially with upcoming changes to sync

2024-11-26 10:49 UTC, closed without merging