Metrics to its own crate
paradigmxyz/reth pull request #9691
Opened 2024-07-22 09:14 UTC by loocapro

Closes https://github.com/paradigmxyz/reth/issues/9458

2024-07-22 18:07 UTC, mattsse requested changes
thanks, pedantic nits

2024-07-22 18:07 UTC, mattsse commented on Cargo.toml
> +    "testing/testing-utils", "crates/node/metrics",
should be moved to correct position, alphabetically

2024-07-22 18:07 UTC, mattsse commented on Cargo.toml
> +reth-node-metrics = { path = "crates/node/metrics" }
order alphabetically

2024-07-22 18:07 UTC, mattsse commented on crates/node/metrics/Cargo.toml
> +exclude.workspace = true
```suggestion
```

2024-07-22 18:07 UTC, mattsse commented on crates/node/core/Cargo.toml
> -metrics-util.workspace = true
cool

2024-07-23 12:00 UTC, mattsse requested changes
cool, some layout issues remain,

think of the metrics crate as something that gets all the things it uses as input, this way we don't need the buildscript etc.

2024-07-24 17:13 UTC, onbjerg submitted a review, later dismissed
looks good! one small nit

2024-07-24 17:13 UTC, onbjerg commented on crates/node/metrics/src/recorder.rs
> +    Lazy::new(|| PrometheusRecorder::install().unwrap());
imo we should still have a function for installing this instead of calling `PROMETHEUS_RECORDER_HANDLE.clone()` in the CLI

2024-07-25 09:35 UTC, mattsse requested changes
last pedantic doc nit and needs rebase

2024-07-25 09:35 UTC, mattsse commented on crates/cli/commands/src/stage/run.rs
> +                },
cool, this should unblock us from extracting the build script from node-core soon

2024-07-25 09:35 UTC, mattsse commented on crates/node/metrics/src/server.rs
> +    pub async fn serve(&self) -> eyre::Result<()> {
this should mention that this spawns the server

2024-07-25 15:47 UTC, mattsse approved these changes

2024-07-25 16:00 UTC, merged