Implement `engine_getBlobsV1`
paradigmxyz/reth pull request #9723
Opened 2024-07-23 01:54 UTC by michaelsproul

This is a prototype implementation of `engine_getBlobsV1`, which allows the CL to fetch blobs from the EL to accelerate blob propagation:

- https://github.com/ethereum/execution-apis/pull/559

Before merging there are a few things that need to be resolved:

- [ ] Work out whether error handling is required on `get_blobs` or whether we should make it infallible (don't return a result).
- [ ] Assess the performance impact of recomputing the versioned hashes during iteration (while holding the cache lock).
- [ ] Determine a good location for the `BlobAndProofV1` type.
- [ ] Add tests.
- [x] Add to engine capabilities.

2024-07-23 08:40 UTC, mattsse requested changes
cool, only a few nits

2024-07-23 08:40 UTC, mattsse commented on crates/rpc/rpc-types/src/lib.rs
> +// FIXME(sproul): move to alloy?
yeah, but we can include it in this pr, but also add it to alloy and once we have a new release we can phase it out here

2024-07-23 08:40 UTC, mattsse commented on crates/rpc/rpc-types/src/lib.rs
> +    pub blob: FixedBytes<BYTES_PER_BLOB>,
this is a bit tricky, because this can lead to stack overflow on deserialize on debug...

I encountered this here as well:

https://github.com/foundry-rs/block-explorers/blob/2a81c193938951fb0d5777cfd110c4acc55fa405/crates/blob-explorers/src/response.rs#L100-L102

see corresponding test

https://github.com/foundry-rs/block-explorers/blob/2a81c193938951fb0d5777cfd110c4acc55fa405/crates/blob-explorers/src/response.rs#L409

so we ideally want a sanity test and perhaps we also need to do 

https://github.com/foundry-rs/block-explorers/blob/2a81c193938951fb0d5777cfd110c4acc55fa405/crates/blob-explorers/src/response.rs#L183

2024-07-23 08:40 UTC, mattsse commented on crates/rpc/rpc-types/src/lib.rs
> +    pub blob: FixedBytes<BYTES_PER_BLOB>,
I think we should definitely box this because we do `vec![None; request.len()]` so each entry even if missing will be a full blob

2024-07-23 08:40 UTC, mattsse commented on crates/rpc/rpc-types/Cargo.toml
> +alloy-eips = { workspace = true }
```suggestion
alloy-eips.workspace
```

2024-07-23 08:40 UTC, mattsse commented on crates/rpc/rpc-engine-api/src/engine_api.rs
> +            .expect("get_blobs_for_versioned_hashes is infallible"))
I think we can return a servererror in this case

2024-09-09 13:44 UTC, mattsse commented
@michaelsproul sorry about the conflicts,
this looks feature complete, I'd like to get this over the line, if you're okay with me fixing the conflicts?

2024-09-09 13:51 UTC, michaelsproul commented
thanks @mattsse that would be great

I started on it locally but got drawn into other things and will likely continue getting distracted 

thanks for pushing it along!

2024-09-09 15:01 UTC, mattsse approved these changes
opening a few smaller followups for this, but this should work

2024-09-09 15:42 UTC, merged

2024-10-02 11:12 UTC, karalabe commented on crates/transaction-pool/src/blobstore/mem.rs
> +        for (_tx_hash, blob_sidecar) in self.inner.store.read().iter() {
Whilst correct, linearly iterating the pool might be a less-than-ideal solution long run?