Feat: DNS in reth.toml > trusted_nodes
paradigmxyz/reth pull request #9864
Opened 2024-07-29 12:41 UTC by loocapro

Closes: https://github.com/paradigmxyz/reth/issues/9767

2024-07-29 12:44 UTC, onbjerg approved these changes
this looks good to me

2024-07-29 12:53 UTC, onbjerg requested changes

2024-07-29 12:53 UTC, onbjerg commented on crates/net/network-types/src/peers/config.rs
> +use serde::de::{self, Deserializer, SeqAccess, Visitor};
this needs to be gated behind the serde feature flag

```suggestion
#[cfg(feature = "serde")]
use serde::de::{self, Deserializer, SeqAccess, Visitor};
```

2024-07-29 12:53 UTC, onbjerg commented on crates/net/network-types/src/peers/config.rs
> +fn deserialize_trusted_nodes<'de, D>(deserializer: D) -> Result<HashSet<NodeRecord>, D::Error>
this too

2024-07-29 12:56 UTC, mattsse requested changes

2024-07-29 18:16 UTC, mattsse requested changes
style nit

2024-07-29 18:16 UTC, mattsse commented on crates/net/network/src/peers.rs
>          for NodeRecord { address, tcp_port, udp_port, id } in trusted_nodes {
this collect is not required

2024-07-29 18:16 UTC, mattsse commented on crates/net/network/src/peers.rs
> +            .collect();
I'd also like to log a warn here in case this fails

see removed warn

2024-07-30 10:08 UTC, mattsse approved these changes

2024-07-31 12:20 UTC, onbjerg approved these changes

2024-07-31 12:33 UTC, merged