feat: Add OP cli flag to opt-in into discv4 discovery
paradigmxyz/reth pull request #9938
Opened 2024-07-31 14:27 UTC by nkysg

towards https://github.com/paradigmxyz/reth/issues/9919

2024-07-31 15:07 UTC, Rjected reviewed
just want to confirm what we want w.r.t ux

2024-07-31 15:07 UTC, Rjected commented on crates/optimism/node/src/node.rs
> +        let network_builder = network_config_builder
should this be:
```suggestion
        if disable_discovery_v4 || args.discovery.disable_discovery {
            network_config_builder = network_config_builder.disable_discv4_discovery();
        }
        let network_builder = network_config_builder
```
or rather, what is the expected behavior when both the `--disable-discovery` and `--rollup.discovery.v4` flags are provided?

2024-07-31 18:57 UTC, Rjected approved these changes
lgtm, thanks!

2024-07-31 19:25 UTC, mattsse requested changes

2024-07-31 19:25 UTC, mattsse commented on crates/optimism/node/src/node.rs
> +        let network_builder = network_config_builder
style nit, you can use the `apply` function to keep the builder style chain and perform this check in the closure

2024-08-01 11:06 UTC, mattsse approved these changes

2024-08-01 11:21 UTC, merged