feat(primitives): `k256` feature for `secp256k1` module
paradigmxyz/reth pull request #9989
Opened 2024-08-01 14:14 UTC by shekhirin

Towards https://github.com/paradigmxyz/reth/issues/9478

Inspired by https://github.com/paradigmxyz/reth/pull/9430

2024-08-01 15:37 UTC, mattsse commented on crates/primitives/Cargo.toml
> +k256 = { version = "0.13", default-features = false, features = ["ecdsa"], optional = true }
can we move this to workspace?

2024-08-01 16:38 UTC, shekhirin commented on crates/primitives/Cargo.toml
> +k256 = { version = "0.13", default-features = false, features = ["ecdsa"], optional = true }
done

2024-08-01 17:12 UTC, mattsse requested changes
needs double check on c-kzg because this obfuscates revm features even more

https://github.com/paradigmxyz/reth/blob/0fe93a8de640770dc0e24ce4811dd0d1c0edbf04/crates/primitives/Cargo.toml#L103-L103

I think this will still get pulled in because we enable c-kzg for primitives somewhere else but still we need to do a proper workspace feature review

2024-08-01 17:12 UTC, mattsse commented on Cargo.toml
> +reth-primitives = { path = "crates/primitives", default-features = false, features = ["std", "secp256k1"] }
we can probably remove "secp256k1" here seperately and enable it on the node level

2024-08-01 17:12 UTC, mattsse commented on crates/primitives/Cargo.toml
> +k256 = { workspace = true, default-features = false, features = ["ecdsa"] }
this is redundant
```suggestion
k256.workspace = true
```

2024-08-01 17:12 UTC, mattsse commented on crates/primitives/Cargo.toml
> +default = ["c-kzg", "alloy-compat", "std", "reth-codec", "secp256k1"]
we no longer enable c-kzg on workspace level, we need to be extra careful here and double check that we enable this somewhere.

I'm actually not sure where we enable revm c-kzg so we need to check and centralize these crucial settings, ideally on the node level

2024-08-01 17:12 UTC, mattsse commented on crates/primitives/src/transaction/util.rs
> +}
move above the modules

2024-08-01 17:12 UTC, mattsse commented on Cargo.toml
> +reth-primitives = { path = "crates/primitives", default-features = false, features = ["std", "secp256k1"] }
I would feel more comfortable if we don't do this in this pr and look at features separately

2024-08-01 20:02 UTC, mattsse approved these changes

2024-08-02 09:01 UTC, mattsse approved these changes

2024-08-02 12:33 UTC, mattsse approved these changes

2024-08-02 12:39 UTC, shekhirin commented on crates/ethereum/evm/Cargo.toml
> +reth-primitives = { workspace = true, features = ["secp256k1"] }
oh okay, we need it only for tests anyway, so moved to dev deps

2024-08-02 13:07 UTC, merged